댓글 기능 구현
woowacourse-teams/2022-gong-seek pull request #102
Opened 2022-07-18 12:38 UTC by hanull

- 인수테스트 작성
- comment entity 구현
- 댓글 생성 기능 구현
- 댓글 조회 기능 구현
- 댓글 수정 기능 구현

close #79

2022-07-18 13:10 UTC, brorae approved these changes
댓글 기능 구현하느라 수고 많으셨습니다!

2022-07-18 13:10 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +    }
이 부분들은 메서드를 메서드로 한번더 감쌌다는 느낌이 드는데, 따로 메서드 분리하신 이유가 있을까요?

2022-07-18 13:10 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/member/domain/Member.java
> +    }
이 부분도 이 메서드를 사용하는 부분에서 `memberA.equals(memberB)`와 같이 사용해도 되지 않을까요?

2022-07-19 01:52 UTC, Gyuchool requested changes
기능 구현하시느라 수고하셨습니다☺️

2022-07-19 01:52 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +@Service
```suggestion
@RequiredArgsConstructor
@Transactional
@Service
```
어노테이션 순서를 중요도가 낮을수록 클래스랑 멀어지게 두는 컨벤션이 좋을것 같아요!

2022-07-19 01:52 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +        commentRepository.deleteById(commentId);
commentId는 find에서 찾은 검증된 id가 아닌거 같아요!
그리고 delete를 사용하는게 성능에 더 좋아요!

2022-07-19 01:52 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/comment/domain/repository/CommentRepository.java
> +    List<Comment> findCommentsByArticleId(Long articleId);
Comment repo니깐 찾아도 Comment일것 같아서 
```suggestion
    List<Comment> findAllByArticleId(Long articleId);
```
로 하는건 어떤가요?🙄

2022-07-19 01:52 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/comment/presentation/CommentController.java
> +@RequiredArgsConstructor
```suggestion
@RequiredArgsConstructor
@RequestMapping("/api/articles")
```
모든 생성자 생성 어노테이션을 맨 상단에 두는건 어떤가요?😃

2022-07-19 02:04 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +@Service
넵 생성자 어노테이션은 가장 위로 올릴게용

2022-07-19 02:10 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +        commentRepository.deleteById(commentId);
그러네용 findById를 2번 하는거였네용
수정하겠습니다.

2022-07-19 02:12 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +    }
얘기를 해볼까요

2022-07-19 02:45 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/domain/repository/CommentRepository.java
> +    List<Comment> findCommentsByArticleId(Long articleId);
넹 수정했습니당~

2022-07-19 04:52 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/member/domain/Member.java
> +    }
변경했습니다!

2022-07-19 06:20 UTC, Gyuchool approved these changes

2022-07-19 06:20 UTC, merged