코드 스타일 통일
woowacourse-teams/2022-gong-seek pull request #150
Opened 2022-07-25 17:04 UTC by brorae

null 검증은 DTO에서만 하도록 했습니다 :)

Close #146

2022-07-26 00:23 UTC, Gyuchool requested changes
수고하셨습니다! 몇 가지 의견 남겨봤습니다

2022-07-26 00:23 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Content.java
> +    @Lob
lob을 사용하신 이유가 있을까요? 1_000자 내부면 varchar로도 충분할텐데 궁금해서 물어봅니다!

2022-07-26 00:23 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/comment/presentation/dto/CommentRequest.java
> +    @Length(max = 10000)
```suggestion
    @Length(max = 10_000)
```
요렇게하면 더 가독성있을 것 같아요!

2022-07-26 00:23 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/ContentTest.java
> +        String content = "a".repeat(1001);
테스트 명과 실제 테스트 내용이 다른 것 같네요?

2022-07-26 00:23 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/ContentTest.java
> +public class ContentTest {
SuppressWarnings(NonAscii~)이 없으면 로그 찍을 때, 불필요한 로그가 많이 쌓일 것 같은데 붙이는 게 어떤가요?

2022-07-26 04:43 UTC, jurlring reviewed
리팩터링 하시느라 수고하셨습니당~~ 👍 
리뷰는 남겼는데 확인 부탁드려요.

2022-07-26 04:43 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +    }
이 메서드의 위치가 애매한 것 같아요.
save와 checkAuthorization 메서드에서 사용되는데 해당 메서드 근처도 아니고, 맨뒤도 아니네요.
save바로 아래나 checkAuthorization 아래가 좋을 것 같아요.

2022-07-26 04:43 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +    public CommentsResponse getAll(AppMember appMember, Long articleId) {
```suggestion
    public CommentsResponse getByArticleId(AppMember appMember, Long articleId) {
```
위와 같은 메서드명은 어떤가요?
모든 댓글을 가져오는게 아니고 하나의 게시물에 대한 댓글을 가져온다는 것을 명확하게 나타내면 좋을 것 같아요.

2022-07-26 04:43 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
>      }
update에만 checkAuthorization를 하고 있네요.
delete에도 필요하다고 생각하는데 어떻게 생각하시나요?

2022-07-26 04:46 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Content.java
> +    @Lob
1000자면 varchar로 사용해도 되겠지만, 저희 팀의 방향에 따라 1000자 이상이 될 수도 있다고 생각했습니다.
API 변경에 따라 10000자로 변경했습니다.

2022-07-26 06:33 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
>      }
delete에서도 checkAuthrorization에서 수행하는 일들을 하고 있는데, 메서드를 묶지 않았네요. 수정했습니다.

2022-07-26 06:36 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/comment/application/CommentService.java
> +    public CommentsResponse getAll(AppMember appMember, Long articleId) {
get 이라고 하면 하나만 가져오는 느낌이 들어서 getAllByArticleId로 수정했습니다. ByArticleId로 해당 게시글에 대한 댓글을 모두 가져온다는 의미를 전달할 수 있을 것같아요.

2022-07-27 05:51 UTC, jurlring approved these changes
고생하셨습니다~~~~ 👍

2022-07-27 05:51 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Views.java
> +}
VO에서 initialize하는 것은 어떤가요?
그렇게 하면 검증 로직도 필요 없을 것 같아요.

2022-07-27 06:13 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Views.java
> +}
Article이 생성될 때, Views는 0부터 시작되는 것이 맞지만, Views에 값을 주입받으면 테스트에 용이하겠다고 생각했습니다. 현재 테스트에서 사용되는 부분이 없어 수정했습니다!

2022-07-27 08:44 UTC, hanull approved these changes
VO 로 만들어서 코드가 깔끔해졌네요! 수고하셨어요

2022-07-27 08:44 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Views.java
> +public class Views {
👍

2022-07-27 08:44 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/ArticleTest.java
> +        var article = new Article("title", "contetn", Category.QUESTION, member);
var 형식이 있네요?!  Article 타입으로 변경하는게 어떨까요
추가적으로 데이터를 확인하는 테스트가 있으면 더 꼼꼼한 테스트가 될 것 같아요

2022-07-28 02:37 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Content.java
> +    @Lob
varchar가 대략 65000까지 되는 걸로 아는데 LOB을 선호하는 이유가 있을까요?

2022-07-28 02:38 UTC, Gyuchool approved these changes
수고하셨습니다~

2022-07-28 02:40 UTC, brorae commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/ArticleTest.java
> +        var article = new Article("title", "contetn", Category.QUESTION, member);
안에 데이터를 확인하는 것으로 변경했습니다.

2022-07-28 05:34 UTC, merged