alert -> snackbar 로 보여주기
woowacourse-teams/2022-gong-seek pull request #189
Opened 2022-08-01 05:48 UTC by liswktjs

Close #58 

기존에 alert로 안내 문구를 보여주었던 것에서 snackBar 컴포넌트 활용하는 것으로 수정 

- createPortal를 통해서 snackBar을 구현 
- SnackBar의 열려있는 상태를 recoil를 통해서 전역변수로 관리 
- 기존에 alert를 snackBar로 이동

2022-08-01 06:20 UTC, hwangstar156 requested changes

2022-08-01 06:20 UTC, hwangstar156 commented on frontend/src/components/common/SnackBar/SnackBar.tsx
> +   return isOpen ? ReactDOM.createPortal(
여기서 snackbar 부분과 portal부분을 분리하는것이 어떨까요? 만약 이 컴포넌트에서 isOpen이 변경된다면 dom도 다시 찾고 createPortal도 다시 실행할것같아서 비용이 많이 들것같네요!



```suggestion
const SnackBarPortal = () => {
    const snackBar = document.getElementById('snack-bar');
    return React.createPortal(children)

const SnackBar = () => {

   const {isOpen, message} = useRecoilValue(snackbarState);

    return (
        <SnackbarPortal>
             {isOpen && component}
        </SnackbarPortal>
    )
}
```

이런식으로 하면 좋을것같아요!

2022-08-01 16:11 UTC, liswktjs commented on frontend/src/components/common/SnackBar/SnackBar.tsx
> +   return isOpen ? ReactDOM.createPortal(
수정했습니다!

2022-08-02 01:51 UTC, jurlring approved these changes
수고하셨습니다~

2022-08-02 01:52 UTC, merged

2022-08-02 01:52 UTC, jurlring approved these changes