투표 마감기한 등록하는 기능 구현
woowacourse-teams/2022-gong-seek pull request #201
Opened 2022-08-02 12:07 UTC by hwangstar156

close #193

2022-08-02 12:17 UTC, liswktjs requested changes
스타일링 코드 순서가 뒤로갈수록 뒤죽박죽인것같지만 이건 저도 잘 못챙겨서
날잡아서 싹 수정하죠✊️

2022-08-02 12:17 UTC, liswktjs commented on frontend/src/hooks/useLocationState.tsx
> +const useLocationState = <State = unknown,>() => {
이게, link하면서 상태보내는 거군요🤔
뭐가 상태로 들어올지 몰라서 unknown인걸까요?
이러면 | 연산자 사용해서 다 가드해주는건 안될까요????

2022-08-02 12:17 UTC, liswktjs commented on frontend/src/pages/VoteDeadlineGenerator/index.tsx
> +	}, [isSuccess]);
useMutation 커스텀 훅으로 빼죠!

2022-08-02 12:39 UTC, hwangstar156 commented on frontend/src/hooks/useLocationState.tsx
> +const useLocationState = <State = unknown,>() => {
흠 어떻게 하신다는 거죵..?

2022-08-03 01:01 UTC, liswktjs commented on frontend/src/hooks/useLocationState.tsx
> +const useLocationState = <State = unknown,>() => {
모든 state에 대한 타입 미리 정해두기?

2022-08-03 01:02 UTC, liswktjs approved these changes

2022-08-03 01:02 UTC, merged