accessToken 만료될시 로그아웃 되는 기능 추가
woowacourse-teams/2022-gong-seek pull request #208
Opened 2022-08-03 09:50 UTC by hwangstar156

close #205 

customError와 ErrorBoundary이용하여 만료될 경우 alert후 로그아웃 되도록 구현

2022-08-03 10:51 UTC, liswktjs requested changes
에러바운더리 저도 같이 개발하고 싶었는데 스밍 혼자 개발하고 커밋하니깐 
솔직히 기분이 썩 좋지 않네요 
에러 바운더리가 도입되어야 하는 이유를 충분히 설명해주고, 필요성을 제게 설득을 해주셨다면 이렇게까지 기분이 좋지 않진 않을 것 같네요 일방적인 통보 방식으로 전해지는 기분입니다. 
지금 오프라인 상태도 아니라 서로 소통도 어려운데 이런 부분 주의해주셨으면 좋겠습니다 

에러 바운더리 잘 알지도 못해서 코드에 대해서 이야기할게 없네요 절대경로 좀 신경써주세요!

2022-08-03 10:51 UTC, liswktjs commented on frontend/src/App.tsx
> +import ErrorBoundary from './components/helper/ErrorBoundary';
절대경로!

2022-08-03 10:51 UTC, liswktjs commented on frontend/src/components/helper/ErrorBoundary.tsx
> +import CustomError from './CustomError';
절대경로!

2022-08-03 10:51 UTC, liswktjs commented on frontend/src/components/helper/ErrorBoundary.tsx
> +			console.log(this.state.error?.errorCode);
불필요한 코드 삭제해주세요

2022-08-03 10:51 UTC, liswktjs commented on frontend/src/components/helper/ErrorBoundary.tsx
> +		console.log(error);
제거!

2022-08-03 12:06 UTC, hwangstar156 commented on frontend/src/components/helper/ErrorBoundary.tsx
> +}
reset이 작동하는 에러바운더리입니다..!

```jsx
	constructor(props: Props) {
		super(props);
		this.state = { error: null };
	}
```
에러 바운더리에서는 반드시 `getDerivedStateFromError` 라는 메서드를 이용해서 에러를 캐치해냅니다. 그런데 이 생명주기는 class형 컴포넌트에서밖에 없기때문에 무조건 class형 컴포넌트를 이용해야 합니다.

초기상태는 error 객체이며 type은 CustomError 입니다.

---
```jsx
	static getDerivedStateFromError(error: Error) {
		return { error: error };
	}
```
이 메서드를 통하여 에러를 캐치합니다. 인자로 던져진 에러가 오고 여기서의 return이 setState와 같다고 생각하면 됩니다. 말그대로 에러가 발생하면 상태를 바꿔주는 메서드입니다.

---
```jsx
	componentDidUpdate(_, prevState: State) {
		if (prevState.error !== this.state.error) {
			if (this.state.error && this.state.error.errorCode === '1005') {
				alert('토큰이 만료되었습니다.');

				localStorage.removeItem('accessToken');
				window.location.href = '/';
			}
		}

		if (this.state.error !== null && prevState.error !== null) {
			this.reset();
		}
	}
```

componentDidUpdate, 원래라면 useEffect 역할을 하는 친구입니다! 첫번째 인자로 prevProps, 두번째 인자로 prevState가 들어가는데 첫번째 인자는 이용하지않기에 _ 로 처리하였습니다. useEffect의 dependency array에 특정 상태를 넣으면 그 상태가 바뀔때마다 실행해주는데 componentDidUpdate는 어떤 상태가 변하든 실행을 한후
```jsx
		if (prevState.error !== this.state.error) {...}
```
이런식으로 개발자가 직접 지난값과 바뀌었는지 비교를 해주어서 처리해야합니다. 

그다음 if는 error가 발생했고 그 에러가 만료가 발생한 코드일때 로그아웃 처리하는 로직입니다!

---
```jsx
	render() {
		const { children, fallback } = this.props;

		if (this.state.error && this.props.enable) {
			return fallback;
		}

		return children;
	}
```
render 메서드입니다! 사실 에러가 있으면 fallback을 보여주고 없으면 children을 보여주는게 다입니다. 그런데 만료 에러가 발생할때는 에러페이지를 띄워주는것이 아닌 로그아웃만 시키는것이기에 보여주는것은 children 그대로 보여줘야합니다. 그래서 enable이라는 props를 전달받기로했고 enable이 false면 에러가 발생해도 그냥 children을 보여줍니다.

---
```jsx
	reset() {
		this.setState({ error: null });
	}
```

마지막 reset 입니다. 에러바운더리도 컴포넌트이기 때문에 `상태`를 기억합니다. 에러가 한번 발생한 후 새로고침하기전까지는 그 에러가 계속 남아있는거죠.
```jsx
		if (this.state.error !== null && prevState.error !== null) {
			this.reset();
		}
```

그래서 componentDidUpdate에서 현재 에러가 발생했고 그 전에도 에러가 있었다면 에러를 비우도록 작성하였습니다.

이 에러바운더리는 4가지 상황에서는 에러를 캐치하지 못합니다.
1. 비동기에러 Promise<Error> 이런식으로 오는것은 캐치하지 못합니다.
2. 이벤트 핸들러 내부에서 에러, 역시 비동기에러여서 캐치를 못합니다.
3. SSR에서의 에러처리, SSR을 안해봐서 정확히는 모르겠지만 안된다네요.
4. 에러바운더리 내에서의 에러

--- 

ErrorBoundary가 중첩되어 사용되면 가장 가까이 있는 에러바운더리가 에러를 캐치합니다.

2022-08-03 12:07 UTC, hwangstar156 commented
말없이 에러바운더리 써서 죄송합니다.. 갑자기 이슈 할당받고 빨리 해결해야되는 이슈같아서 개발하다보니 에러바운더리를 같이 하기로 한 이슈인걸 잊고 개발했네요. 다음부터는 신경써서 하겠습니다!!

일단 에러바운더리를 사용한 이유는 header에 accessToken을 걸어주는 api 통신 이라면 모두 이 만료처리를 해주어야하기 때문에 약 20개 정도의 에러를 처리해야합니다. 그렇게 되면 만료를 처리하는 하나의 로직이 20개 가까이 되는 컴포넌트에 공통으로 넣어줘야합니다. 그래서 전역에다가 에러바운더리를 설치하면 throw되는 모든 에러를 캐치하기 때문에 에러 바운더리를 이용 해야겠다고 생각했습니다. 또, 지금 커스텀 훅에서 뺀 방식도 다 에러바운더리를 쓰기 위해서 작성한 로직 이여서 그 로직을 다시 원상복귀 하면서 개발하는게 비효율적일것 같아서 했습니다.

2022-08-03 12:07 UTC, hwangstar156 commented on frontend/src/App.tsx
> +import ErrorBoundary from './components/helper/ErrorBoundary';
수정했습니다!

2022-08-03 12:07 UTC, hwangstar156 commented on frontend/src/components/helper/ErrorBoundary.tsx
> +import CustomError from './CustomError';
수정했습니다!

2022-08-03 12:07 UTC, hwangstar156 commented on frontend/src/components/helper/ErrorBoundary.tsx
> +			console.log(this.state.error?.errorCode);
수정했습니다!

2022-08-03 12:07 UTC, hwangstar156 commented on frontend/src/components/helper/ErrorBoundary.tsx
> +		console.log(error);
수정했습니다!

2022-08-04 07:43 UTC, liswktjs approved these changes

2022-08-04 07:43 UTC, merged