투표 기능 구현
woowacourse-teams/2022-gong-seek pull request #244
Opened 2022-08-05 10:08 UTC by Gyuchool

- 투표 하기 기능
- 투표 조회 기능
- 투표 생성 기능 

구현하다보니 Vote가 VoteItem을 참조할 일이 많습니다.  현재는 단방향이어서 매번 id를 통해서 가져오는데 해당 모습이 너무 테이블 중심적이라고 생각되어 `Vote` 와 `VoteItem`을 양방향 매핑으로 가져가는 것은 어떨까요?

2022-08-07 10:02 UTC, brorae requested changes
구현하시느라 수고하셨습니다!
몇가지 커멘트 남겨보았습니다. 확인 부탁드려요~!

2022-08-07 17:09 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/VoteController.java
> +    @PostMapping("/do")
해당 api를 보시면 처음 투표했을 떄는 `생성`을 하고 만약 이미 존재해서 다른 투표를 선택한다면 `수정`을 합니다.

따라서 행위를 표현하는 GET, PUT, POST, DELETE중 어느 것에 해당하기 어렵다고 생각했습니다. 그래서 자원을 `control`한다고 생각되어서 동사를 사용해서 표현했습니다. 
[REST한 api참고 자료](https://prohannah.tistory.com/156)

2022-08-07 17:13 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +        voteItemRepository.saveAll(voteItems);
voteItems에는 `Set<VoteItem>`만 있는데 그냥 생성자로 처리하면 `Vote`까지 인자로 받아서 처리해야 했습니다. 
이렇게 되면 생성자의 역할이 커지고 로직이 비대해져서 생성자의 역할이 너무 커진다고 생각했습니다. 그래서 정적 팩토리 메서드를 만들어서 해당 메서드에서 처리하도록 했습니다.

2022-08-07 17:21 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +        Vote foundVote = getVoteByArticleId(articleId);
해당 메서드가 아래 `doVote`메서드 내부에서 메서드로 만들면서 `doVote`메서드 아래로 갔네요..
위치를 위에 메서드 쪽으로 옮기겠습니다~

중복 사용하는 메서드가 사이에 있을 때가 애매하네요..사이에 적으면 아래 메서드에서 찾을 때는 위로 올려야해서요 🤔

2022-08-07 17:25 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/domain/repository/VoteItemRepository.java
> +    List<VoteItem> findAllByVoteArticleId(Long articleId);
VoteItem에서는 `Article`을 직접 가지고 있지 않아서 spring data jpa를 사용할 때는 레넌이 말씀하신 방법으로는 조회가 안됩니다!
따라서 findAllByVote를 통해서 ArticleId에 접근하는 방법밖에 없어서 해당 메서드 명명을 따랐습니다.

추후에 얘기해보고 한눈에 이해하기 어렵다면 직접 쿼리를 짜서 개선해봐요!

2022-08-07 17:30 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +
오 그렇네요! 수정했습니다

2022-08-08 04:49 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +    }
단순 변환하는 로직이어도 DTO내부에 넣게 되면 이후에 가벼운 로직도 괜찮겠지 괜찮겠지하면서 내부로 로직이 들어갈 것 같아서 우선 dto내부에서 처리하지 않고 service에서 처리했습니다.

단순히 값을 전달하는 역할을 하는 DTO가 변환하는 로직을 가지고 있어도 될까요? 레넌은 어떻게 생각하시나요?

2022-08-08 05:10 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        }
아래 checkGuest메서드에서 게스트인지 확인을 해주는데, 여기에서 한 번 더 해주는 건가요?

2022-08-08 05:11 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/VoteAcceptanceTest.java
> +    @Test
추가했습니다!

2022-08-08 05:24 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Article.java
> +    }
그렇네요! `@LastModifiedDate`를 생각 못했네요.. 수정했습니다!

2022-08-08 05:29 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        }
충돌 해결하면서 로직이 겹쳐있던 거를 제거 못했네요. 제거했습니다!

2022-08-08 06:07 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +        return new VoteResponse(foundVote, convertVoteItemResponse(voteItems), getVotedItemIdOrNull(voteHistory), foundVote.isExpired());
foundVote 대신 파라미터로 받는 articleId를 넘겨주면 될 것 같은데 이렇게 구현하신 이유가 있나요?
VoteResponse에 필드가 articleId인데, vote를 넘기는게 이해 하는데 절차를 더 거치는 느낌이라 가독성을 위해서 수정하는 것은 어떤가요?
```suggestion
        return new VoteResponse(articleId, convertVoteItemResponse(voteItems), getVotedItemIdOrNull(voteHistory), foundVote.isExpired());
```

2022-08-08 06:42 UTC, jurlring reviewed
고민을 많이 하셨다는게 느껴지네요.
구현하느라 너무너무 고생 많으셨어요!
코멘트를 몇개 남겼는데 확인 부탁드려요!

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +    }
public 메서드에서 실행된 순서대로 private메서드를 두기로 정한 것 같은데 순서가 다르네용!

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +                .orElseThrow(ArticleNotFoundException::new);
오버헤드를 줄이기 위해 readOnly를 붙여주세요 :)

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +
예외 클래스 이름이 좀 띠용하네요.

커스텀 예외를 사용하게 된 이유는 예외를 좀 더 명확하게 알기 위해서 였는데요.

대부분 예외 클래스의 이름은 원인보단 이유입니다.

vote를 생성할 수 없다는 원인이 아니라 왜 생성할 수 없는지에 대한 이유가 들어가야 하지않을까요.

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/VoteController.java
> +                voteCreateRequest));
```suggestion
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(voteService.create(appMember, articleId, voteCreateRequest));
```

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/dto/VoteCreateRequest.java
> +    private Set<String> items;
해당 검증이 도메인에서는 필요 없나요?

2022-08-08 06:42 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/dto/VoteCreateResponse.java
> +    private Long articleId;
요건 왜 필요한가용?

2022-08-08 06:42 UTC, jurlring commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/VoteAcceptanceTest.java
> +
```suggestion

```

2022-08-08 06:42 UTC, jurlring commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/VoteAcceptanceTest.java
> +        Long vottedItemId = firstGetResponse.getVoteItems()
```suggestion
        Long votedItemId = firstGetResponse.getVoteItems()
```

2022-08-08 08:30 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/dto/VoteCreateRequest.java
> +    private Set<String> items;
도메인 검증 로직 추가할게요!
dto는 입력 데이터 검증, 도메인은 도메인 로직 검증이기 때문에 둘 다 필요할 것 같아요.

2022-08-09 02:55 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +        return new VoteResponse(foundVote, convertVoteItemResponse(voteItems), getVotedItemIdOrNull(voteHistory), foundVote.isExpired());
articleId 로 생성된 투표가 있는지 확인해야 하기 때문에 foundVote 를 찾는 과정이 필요해요.
매개변수로 vote를 넘기는 부분은 불필요하다고 느껴져서 아래와 같이 vote에서 articleId 를 조회해서 넘기는 방법으로 변경했어요.
```java
return new VoteResponse(foundVote.getArticle().getId(), convertVoteItemResponse(voteItems), getVotedItemIdOrNull(voteHistory), foundVote.isExpired());
```

2022-08-09 03:00 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +    }
수정했습니다

2022-08-09 03:06 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +                .orElseThrow(ArticleNotFoundException::new);
내부적으로 호출하는 private 메서드에요! private 메서드라서 readOnly를 못붙여요

2022-08-09 03:19 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +
`UnavailableArticleException` 변경했어요

2022-08-09 03:27 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/VoteAcceptanceTest.java
> +
👍

2022-08-09 03:34 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/vote/presentation/dto/VoteCreateResponse.java
> +    private Long articleId;
왜 필요하다는게 무슨 의미일까요?articleId를 왜 반환해주는지? 라는 의마가 맞을까요?

그 의미가 맞다면, 투표 생성 후 게시글과 투표 조회를 위해서 프론트로 보내주고 있어요!

2022-08-09 03:35 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/VoteAcceptanceTest.java
> +        Long vottedItemId = firstGetResponse.getVoteItems()
👍

2022-08-09 03:50 UTC, jurlring approved these changes
리뷰 반영하시느라 고생하셨어요!! 💯 
작은 코멘트 하나 남겼는데 확인해보셨으면 좋겠어요!

2022-08-09 03:50 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/comment/domain/Content.java
> +        if (Objects.isNull(value) || value.trim().isBlank()) {
isBlack가 trim해주지 않나용?

2022-08-09 03:50 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/common/exception/ExceptionType.java
> +    private final Class<? extends ApplicationException> type;
👍

2022-08-09 03:50 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +    @Transactional(readOnly = true)
👍

2022-08-09 03:50 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/vote/domain/VoteItems.java
> +    private static final int MAX_VOTE_ITEM_COUNT = 5;
👍

2022-08-09 04:08 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/comment/domain/Content.java
> +        if (Objects.isNull(value) || value.trim().isBlank()) {
오 그러네요👍
관련 부분 모두 수정했어요!

2022-08-09 04:35 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/vote/application/VoteService.java
> +    }
저는 단순 변환로직은 DTO에 있어도 된다고 생각해요. 단순 변환로직까지 서비스에서 모두 처리해버리면 서비스가 커질 수 있다고 생각합니다.

2022-08-09 04:42 UTC, brorae approved these changes
수정 사항 확인했습니다!
그럼 엔티티간의 참조가 빈번할 때 양방향을 사용하는 건가요??

2022-08-09 06:33 UTC, hanull commented
https://github.com/woowacourse-teams/2022-gong-seek/pull/244#discussion_r940885611
dto 로직 이동은 레넌 말에 동의해서 변경했어요.

vote, voteItem 양방향을 고려했었는데 수정해보니 큰 이점을 느끼지 못해서 현재 단방향을 유지하도록 할게요!

2022-08-09 06:33 UTC, merged