데스크탑 화면에서의 대응
woowacourse-teams/2022-gong-seek pull request #247
Opened 2022-08-06 14:40 UTC by liswktjs

- PopularArticle에서 큰 부분을 차지하는 Article을 표시하는 부분을 컴포넌트로 분리 
- Header에 z-index를 부여하여 Header에 겹쳐보이는 문제 해결 
- article이 4개로 보여질 때에 데스크탑 화면에서 벗어나 보이는 문제를 3개씩 보여주는 것으로 해결

2022-08-08 06:05 UTC, hwangstar156 requested changes

2022-08-08 06:05 UTC, hwangstar156 commented on frontend/src/pages/Home/ArticleItem/ArticleItem.tsx
> +}
이미 article관련한 타입이 있는것 같은데 그거를 재활용해서 이부분을 고칠수 있을까요?

2022-08-09 04:03 UTC, liswktjs commented on frontend/src/components/layout/Header/Header.tsx
> +		window.confirm('정말로 로그아웃을 하시겠습니까?');
그렇네요! if문으로 감싼줄알았는데 안감싸져 있네요 수정했습니다~

2022-08-09 04:04 UTC, liswktjs commented on frontend/src/pages/Home/ArticleItem/ArticleItem.tsx
> +}
이 부분 해시태그 구현하면서 해당 파일을 고쳐서 해시태그 pr에서 수정 하겠습니다~

2022-08-09 08:04 UTC, hwangstar156 approved these changes

2022-08-09 08:04 UTC, merged