비회원일 때 인터셉터 거치지 않도록 수정
woowacourse-teams/2022-gong-seek pull request #249
Opened 2022-08-07 13:44 UTC by jurlring

## 리팩터링 내용

## 이슈
Close #241

2022-08-08 05:20 UTC, brorae requested changes
수고하셨습니다!
몇가지 커멘트 남겼읍니다.

2022-08-08 05:20 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/auth/presentation/AuthenticationInterceptor.java
> +    }
여기도 Anonymous일 때가 아니라 Guest일 때 인 것 같아요

2022-08-08 05:20 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/auth/presentation/AuthenticationInterceptor.java
> +    private static final String ANONYMOUS_ACCESS_TOKEN = "Bearer null";
Anonymous일 때가 아니라 Guest일 때 인 것 같아요

2022-08-08 05:20 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/auth/presentation/AuthenticationInterceptor.java
> +    }
비회원일 때 조회나 검색을하면 토큰이 아예 들어오지 않는데, 이 부분도 처리해주면 좋을 것 같습니다 👍

2022-08-08 05:50 UTC, Gyuchool approved these changes
수고하셨습니다~! 레넌이 말한 부분만 수정하면 될 것 같아서 approve 할게여~

2022-08-08 05:50 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/ArticleAcceptanceTest.java
> +        TokenResponse 비회원 = new TokenResponse(null);
어느 곳은 변수 명이 한글이고 어느 곳은 변수 명이 영어여서 헷갈리네요😅
한글로 할지 영어로 할지 얘기해봐야겠네여

2022-08-08 05:50 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/CommentAcceptanceTest.java
> +        //given
given when then 추가👍

2022-08-08 11:51 UTC, jurlring commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/ArticleAcceptanceTest.java
> +        TokenResponse 비회원 = new TokenResponse(null);
네 죠습니다~

2022-08-08 14:12 UTC, hanull approved these changes
수고하셨어요!
given when then 주석을 모두 다신 것 같은데 어떤 목적으로 하신걸까요?! 가독성이 목적일까요?
그런데 이렇게 길지않은 코드에서는 번거로운 과정이라고 느껴지네요

2022-08-09 02:20 UTC, jurlring commented
프론트 헤더 추가 머지되면 같이 머지할게용

2022-08-09 08:51 UTC, brorae approved these changes
확인했습니다!
수고하셨어요~!

2022-08-09 08:52 UTC, merged