좋아요 기능 구현
woowacourse-teams/2022-gong-seek pull request #254
Opened 2022-08-08 06:56 UTC by hwangstar156

close #251 

# 기능 명세

좋아요를 클릭했을때 로직을 관리하는 커스텀 훅 분리
좋아요 기능 추가로 변경된 api명세에 대한 코드 수정

2022-08-09 03:23 UTC, liswktjs requested changes
코멘트 남겼습니다 수정해주세요~

2022-08-09 03:23 UTC, liswktjs commented on frontend/src/api/like.ts
> +export const postLikeArticle = (articleId: string) => {
메서드 명을 조금 바꿔 보는게 어떨까요? 지금은 좋아하는 게시글을 포스트 한다 라고 느껴지네요 
조금 혼동이 올수 있을 것 같아요 좋아요를 더한다 라는 의미가 들어가도록 메서드 명을 변경하면 좋을 것 같아요

2022-08-09 03:23 UTC, liswktjs commented on frontend/src/api/like.ts
> +export const deleteLikeArticle = (articleId: string) => {
얘도 좋아하는 게시글을 삭제한다? 라는 식으로 읽혀서 메서드의 행동과 어울리지 않는 것 같아요 메서드 명 변경 부탁드립니다

2022-08-09 03:23 UTC, liswktjs commented on frontend/src/hooks/useHeartClick.tsx
> +	const [isHeartClick, setIsHeartClick] = useState(isLike);
useState에 <boolean>이라고 타입 지정해주는 거 어떨까요? 명시적으로

2022-08-09 03:23 UTC, liswktjs commented on frontend/src/hooks/useHeartClick.tsx
> +			queryClient.invalidateQueries('all-articles');
이건 무슨역할을 하는 코드인가여 all-articles 캐시 지우는 건가

2022-08-09 03:23 UTC, liswktjs commented on frontend/src/types/articleResponse.ts
>  export interface AllArticleResponse {
나중에 만나서 타입 정리 한번 같이 하죠! 뭔가 지금 혼재 되어 있는 기분이에요 코딩하면서 개인적으로 느꼈습니당

2022-08-09 03:54 UTC, hwangstar156 commented on frontend/src/hooks/useHeartClick.tsx
> +			queryClient.invalidateQueries('all-articles');
refetch 하는 기능이랑 똑같습니다! 캐시를 지워서 다시 fetch를 진행합니당!

2022-08-09 03:54 UTC, hwangstar156 commented on frontend/src/types/articleResponse.ts
>  export interface AllArticleResponse {
좋습니다!

2022-08-09 03:54 UTC, hwangstar156 commented on frontend/src/hooks/useHeartClick.tsx
> +	const [isHeartClick, setIsHeartClick] = useState(isLike);
boolean이 누락되있는건가요..? 개인적으로 저는 타입추론이 되서 useState에는 굳이 타입을 적지 않는데 굳이 적어야 할까요?

2022-08-09 03:58 UTC, hwangstar156 commented on frontend/src/api/like.ts
> +export const postLikeArticle = (articleId: string) => {
requestLikeArticle로 변경하였습니다!

2022-08-09 03:58 UTC, hwangstar156 commented on frontend/src/api/like.ts
> +export const deleteLikeArticle = (articleId: string) => {
requestUnlikeArticle로 변경하였습니다!

2022-08-09 04:49 UTC, liswktjs requested changes

2022-08-09 04:49 UTC, liswktjs commented on frontend/src/api/like.ts
> +export const requestLikeArticle = (articleId: string) => {
postAddLikeOfArticle 이런 느낌의 이름은 어떨까요? 뭔가... 뭔가... 애매하네요🤔🤔

2022-08-09 04:49 UTC, liswktjs commented on frontend/src/api/like.ts
> +export const requestUnlikeArticle = (articleId: string) => {
얘도 deleteLikeOfArticle???

2022-08-09 05:35 UTC, hwangstar156 commented on frontend/src/api/like.ts
> +export const requestLikeArticle = (articleId: string) => {
Of는 빼고 postAddLikeArticle 어떨까요..?

2022-08-10 04:51 UTC, liswktjs commented on frontend/src/api/like.ts
> +export const requestLikeArticle = (articleId: string) => {
흐으으으으으으으음 애매하네여 말이 되는 것 같기도 하고 아닌것 같기도하고 
일단은 그렇게 가시죠

2022-08-10 04:51 UTC, liswktjs approved these changes

2022-08-10 04:52 UTC, merged