해시태그 기능 구현
woowacourse-teams/2022-gong-seek pull request #262
Opened 2022-08-09 03:13 UTC by liswktjs

게시글 등록 api 수정
 게시글 수정 api 수정
 게시글 상세조회 api 수정
 게시글 조회 api 수정
 해시태그 Ui 구현
 등록 구현
 해시태그 삭제 기능 구현

* 현재, 게시글 상세 페이지에서 input 등이 theme을 사용하지 않고 rem을 사용해서 스타일링 중임 스타일을 다 같이 rem->theme으로 바꾸는 과정이 한 번 필요할 것 같음 
* 임시로 게시글 작성 페이지에서 스타일을 맞추기 위하여 theme을 활용하지 않고 rem 사용

2022-08-09 03:40 UTC, hwangstar156 requested changes

2022-08-09 03:40 UTC, hwangstar156 commented on frontend/src/components/common/HashTag/HashTag.tsx
> +	const [errorMsg, setErrorMsg] = useState<string>('');
string 안적어도 타입추론으로 string 될거에요!

2022-08-09 03:40 UTC, hwangstar156 commented on frontend/src/components/common/HashTag/HashTag.tsx
> +			);
filter 같은 경우 true를 return 하면 그 아이템을 거르는거 아닌가요..?
```suggestion
			setHashTags(
				hashTags.filter((item, index) => index < hashTags.length -1),
			);
```

이런식으로 작성해도 되지않을까요?

2022-08-09 03:40 UTC, hwangstar156 commented on frontend/src/pages/UpdateWriting/hooks/usePostUpdateWritingArticle.tsx
> +	const [hashTag, setHashTag] = useState<string[]>(tempArticle.hashTag);
여기두..! string 빼도 될거같아요

2022-08-09 04:08 UTC, liswktjs commented on frontend/src/components/common/HashTag/HashTag.tsx
> +	const [errorMsg, setErrorMsg] = useState<string>('');
이게 hashTags의 useState에 타입을 주면서 통일 감을 줄려고 타입 지정해서 넣긴 했습니당 
모든 useState에 타입 미리 지정해두는 거 어떨까요?

2022-08-09 04:09 UTC, liswktjs commented on frontend/src/pages/UpdateWriting/hooks/usePostUpdateWritingArticle.tsx
> +	const [hashTag, setHashTag] = useState<string[]>(tempArticle.hashTag);
이거 배열 같은 경우에는 string 빼면 에러 나더라고요! 빈 배열일 수 있어서 그런지 undefined일수도 있다고 하면서 자꾸 타입 에러 나길래 배열 부분에 타입 지정해주 었습니다 
그리고 하나 하는김에  useState들에 다 타입 지정해주긴 했습니다

2022-08-09 04:11 UTC, liswktjs commented on frontend/src/components/common/HashTag/HashTag.tsx
> +			);
리뷰어님 읽기 편하라고 if문으로 해서 명시적으로 해놓긴 했는데
수정하겠습니다! 
뭔가 개인적으로는 인덱스로 처리하다 보니깐 바로 return 해버리면 이상하더라고요 ㅋㅋㅋㅋㅋ
그래서 일단 if문으로 넣긴 했었는데 수정하겠습니다~

2022-08-09 05:45 UTC, hwangstar156 commented on frontend/src/pages/UpdateWriting/hooks/usePostUpdateWritingArticle.tsx
> +	const [hashTag, setHashTag] = useState<string[]>(tempArticle.hashTag);
배열일때만 string[] 적어주고 나머지 부분은 타입추론에게 맡기는것이 어떨까요?

2022-08-12 05:21 UTC, hwangstar156 approved these changes

2022-08-12 05:21 UTC, merged