refreshToken 적용
woowacourse-teams/2022-gong-seek pull request #270
Opened 2022-08-09 12:58 UTC by liswktjs

Close #267 
리프레시 토큰 적용 

리프레시 토큰의 흐름 
로그인 → accessToken과 refreshToken이 발급 됨 → 30분이 지났다 → accessToken의 유효기간이 만료됨 
→ (요청을 보냈을때) accessToken이 만료되었다는 1005번 에러가 던져짐 
→ 이때에, 리프레시 토큰을 가지고 새로운 accessToken을 달라는 요청을 보냄 → 응답으로  accessToken과 refreshToken이 발급 됨 (accessToken은 body로 보내고 refreshToken은 쿠키로) 

리프레시 토큰이 유효하지 않으면,  1008번 에러 발생 → 유저에게 로그인을 하라고 한다 
리프레시 토큰이 유효하면, accessToken 과 refreshToken을 발급해준다

* 에러바운더리에서, 클래스 컴포넌트 라는 단점 때문에 훅을 사용하지 못하는 문제가 있었음 
* 그래서 이를 처리하기 위해서 리프레시토큰 관련 처리를 하는 페이지 컴포넌트를 하나 생성하고 해당 페이지로 이동을 시켜 해당 작업을 그곳에서 처리함

2022-08-10 05:38 UTC, hwangstar156 requested changes

2022-08-10 05:38 UTC, hwangstar156 commented on frontend/src/api/login.ts
> +			withCredentials: true,
이거 2개의 차이는 뭔가요?

2022-08-10 05:38 UTC, hwangstar156 commented on frontend/src/pages/Login/RefreshTokenHandler/RefreshTokenHandler.tsx
> +	}, []);
localStorage를 지우기 위한 코드인건가요? localStorage.removeItem('accessToken')을 이용해도 되지않을까요?

2022-08-10 05:38 UTC, hwangstar156 commented on frontend/src/utils/deleteRefreshCookie.ts
> +	document.cookie = 'refreshToken=; expires=Thu, 01 Jan 1999 00:00:10 GMT;';
이건 어떤 코드인가요?

2022-08-11 06:51 UTC, liswktjs commented on frontend/src/api/login.ts
> +			withCredentials: true,
이게 아직 쿠키 관련해서 백엔드와의 실험이 안 되어 있어서, 정확한 차이는 모르겠지만 
Access-Control-Allow-Credentials는 다른 서버(=백엔드)쪽에서 프론트 서버로 쿠키를 저장할 수 있도록 하는게 CORS로 막혀 있어서 해당 부분을 풀어주는 것이라고 봤었고 
withCredentials의 경우는 프론트 서버에서 응답으로 오는 쿠키값을 자동으로 저장되는 것을 허용해주는 속성이라고 합니다 
일단은 둘다 설정을 진행해봤었고 백엔드와의 협업을 통해서 수정될수도 있을 것 같습니다!

2022-08-11 06:52 UTC, liswktjs commented on frontend/src/utils/deleteRefreshCookie.ts
> +	document.cookie = 'refreshToken=; expires=Thu, 01 Jan 1999 00:00:10 GMT;';
프론트 서버쪽에서 쿠키로 가지고 있는 리프레쉬 토큰을 무효화 시키는 코드입니다. 
쿠키의 경우 정해진 시간이 지나면 해당 값을 브라우저에서 삭제를 시킨다고 합니다. 그래서 임의로 쿠키를 삭제해주고 싶을 때에는 옛~날 시간을 입력해 넣어서 삭제를 진행한다고 합니다

2022-08-12 05:20 UTC, hwangstar156 approved these changes
수고하셨습니다! 근데 왜 file changes가 140개..?

2022-08-12 05:20 UTC, merged