투표, 좋아요에 대한 테스트 코드 작성
woowacourse-teams/2022-gong-seek pull request #279
Opened 2022-08-10 06:58 UTC by hwangstar156

close #269 

## 구현사항

- 투표, 좋아요에 대한 테스트 코드 작성
- 투표, 좋아요 msw 작성
- customHook안에서 refetch하는 로직 바깥으로 분리

2022-08-11 01:47 UTC, liswktjs commented on frontend/jest.config.js
> +		'.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
이 설정은 왜 새롭게 추가 됐나요?

2022-08-11 01:59 UTC, liswktjs requested changes

2022-08-11 01:59 UTC, liswktjs commented on frontend/package.json
> +		"jest-transform-stub": "^2.0.0",
얘네 왜 추가적으로 설치 된건가요?

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/components/common/ArticleContent/ArticleContent.tsx
> +
캐시를 지우기 위한 용도라면 removeQueries도 있는 걸로 아는데, invalidatedQueries를 사용한 이유가 있나요?

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/components/helper/ErrorBoundary.tsx
> +			if (this.state.error && String(this.state.error.errorCode) === '1005') {
이거 (property) CustomError.errorCode: 1001 | 1002 | 1003 | 1004 | 1005 | 1006 | 1007 | 2001 | 3001 | 3002 | 3003 | 3004 | 3005 | 4001 | 4002 | 4003 | 5001 | 5002 | 5003 | 5004 | 5005 | 5006 | 5007 | 5008 | 5009 |  이런식으로 타입 정해져 있어서 string으로 안하고 둘다 숫자로 비교하면 되지 않나요?

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/hooks/__test__/useHeartClick.test.tsx
> +import useHeartClick from '../useHeartClick';
절대경로!

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/components/common/ArticleItem/ArticleItem.tsx
> +
얘네 지금 쿼리 안날리면 캐시가 계속 남나요?

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/mock/vote.ts
> +// const mockVotes = data ? (JSON.parse(data) as TVote[]) : [];
얘 왜 남겨져 있는거죵???

2022-08-11 01:59 UTC, liswktjs commented on frontend/src/pages/Discussion/hooks/usePostVoteItem.tsx
> +			queryClient.invalidateQueries(`vote${articleId}`);
얘도 이렇게 한 이유가 있나요?

2022-08-12 05:23 UTC, hwangstar156 commented on frontend/package.json
> +		"jest-transform-stub": "^2.0.0",
jest에서 오류가 나서 설치했었는데 이 문제가 아니여서 지워도 될것같은 패키지네요. 삭제하겠습니다!

2022-08-12 05:28 UTC, hwangstar156 commented on frontend/src/components/common/ArticleContent/ArticleContent.tsx
> +
https://github.com/TanStack/query/discussions/3169

`removeQueries` 는 처음 들어보긴하네요! 그런데 저기서 보면 캐시를 무효화가 아닌 아예 지워버리면 불러올떄 다시 하드 로딩이 된다고 하네요..

2022-08-12 05:28 UTC, hwangstar156 commented on frontend/src/components/helper/ErrorBoundary.tsx
> +			if (this.state.error && String(this.state.error.errorCode) === '1005') {
괜찮을것 같네요!

2022-08-12 05:30 UTC, hwangstar156 commented on frontend/src/components/common/ArticleItem/ArticleItem.tsx
> +
좋아요, 좋아요 취소가 성공하면 다시 게시물을 fetch해서 최신 상태를 유지하려는 코드입니다..!

2022-08-12 05:30 UTC, hwangstar156 commented on frontend/src/mock/vote.ts
> +// const mockVotes = data ? (JSON.parse(data) as TVote[]) : [];
삭제하겠습니다!

2022-08-12 05:39 UTC, hwangstar156 commented on frontend/src/pages/Discussion/hooks/usePostVoteItem.tsx
> +			queryClient.invalidateQueries(`vote${articleId}`);
incalidateQueries가 좀더 똑똑하게 refetch를 한다고 하네요..! 

https://github.com/TanStack/query/discussions/2468

사실 대부분 invalidQueries를 써서 refetch를 해서 저렇게 작성했는데 좀더 정확한 차이를 알아봐야겠네요!

2022-08-12 05:42 UTC, hwangstar156 commented on frontend/jest.config.js
> +		'.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
에러가 나와서 추가한건데 다른문제여서 삭제해도 될것같습니다!

2022-08-12 06:33 UTC, liswktjs commented on frontend/src/components/common/ArticleContent/ArticleContent.tsx
> +
오 그렇군요 신기하네요 리액트 쿼리 옵션의 세계...

2022-08-12 06:34 UTC, liswktjs commented on frontend/src/components/common/ArticleItem/ArticleItem.tsx
> +
아 좋아요 시도 후에 바로 게시글 새롭게 로드하는 군요 알겠습니다!

2022-08-12 06:34 UTC, liswktjs commented on frontend/src/pages/Discussion/hooks/usePostVoteItem.tsx
> +			queryClient.invalidateQueries(`vote${articleId}`);
좋아요!!

2022-08-12 06:41 UTC, liswktjs requested changes

2022-08-12 06:41 UTC, liswktjs commented on frontend/src/types/image.d.ts
> +declare module '*.png';
이미지 관련 타입설정 왜 하게 된건가요????

2022-08-12 06:41 UTC, liswktjs commented on frontend/src/types/image.d.ts
> +declare module '*.png';
혹시 notFound 페이지에서 이미지 가져올 때 에러 나서 그런건가요?

2022-08-12 07:32 UTC, hwangstar156 commented on frontend/src/types/image.d.ts
> +declare module '*.png';
png 불러올때 컴파일 에러나오더라고요..!

2022-08-12 08:07 UTC, liswktjs commented on frontend/src/types/image.d.ts
> +declare module '*.png';
어디서 해당 문제가 발생하나요?

2022-08-15 15:12 UTC, hwangstar156 commented on frontend/src/types/image.d.ts
> +declare module '*.png';
NotFound에서 공식 이미지 받아올때 에러납니다!

2022-08-16 05:45 UTC, liswktjs approved these changes

2022-08-18 11:03 UTC, merged