마이페이지에 이름 수정 기능을 구현한다.
woowacourse-teams/2022-gong-seek pull request #292
Opened 2022-08-11 05:03 UTC by hwangstar156

close #288 

## 구현 사항

- 마이페이지 수정 기능에 대한 api 작성
- 마이페이지 수정 기능에 대한 mock 작성
- 마이페이지 수정 기능에 대한 UI 추가
<img width="291" alt="스크린샷 2022-08-11 오후 1 57 51" src="https://user-images.githubusercontent.com/85891751/184067685-554ebf72-b4bd-4e27-9b94-50b32be4f27c.png">
<img width="295" alt="스크린샷 2022-08-11 오후 1 57 57" src="https://user-images.githubusercontent.com/85891751/184067689-3e6e76e4-d284-43fb-9228-7636e125fe5c.png">

2022-08-11 06:47 UTC, liswktjs requested changes
체크버튼이 캡쳐에서 보이는 것으로는 너무 커보여서 수정이 필요할 것 같습니다

2022-08-11 06:47 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.styles.tsx
> +`;
checkButton 캡쳐상으로는 커보이던데 사이즈 조정이 필요할 것 같습니다

2022-08-11 06:47 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	});
의존성배열에서 isSuccess 빠진 것 같습니당

2022-08-11 06:47 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	};
해당 함수 부분을 따로 뺄 필요가 있을까요? 다른 컴포넌트 단에서는 set하는 부분은 onClick에서 화살표 함수로 다 넣어주어서 
통일성이 필요할 것 같습니다 둘 중 하나로 정하죠

2022-08-11 06:47 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/hooks/usePutUserProfile.tsx
> +	};
클릭할때 이름에 대한 유효성 평가가 필요할 것 같습니다! 
유효하지 않을 때에는 이름 input 밑에 빨간색 글로 이름 기준 작성하고 focus처리하죠

2022-08-11 06:47 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +						size={25}
이 size는 왜 있는거죠...?

2022-08-12 10:37 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.styles.tsx
> +`;
사이즈 조정 했습니다!

2022-08-12 10:37 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	});
추가하겠습니다!

2022-08-12 10:39 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	};
일단 inline으로 작성하고 나중에 한번 논의해보면 좋을것 같습니다.

2022-08-12 11:01 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/hooks/usePutUserProfile.tsx
> +	};
<img width="260" alt="스크린샷 2022-08-12 오후 7 57 57" src="https://user-images.githubusercontent.com/85891751/184341308-89303b25-95b0-44fb-b36d-40d4482cdbaf.png">
<img width="284" alt="스크린샷 2022-08-12 오후 7 57 52" src="https://user-images.githubusercontent.com/85891751/184341312-d6301f44-4760-4d22-a7e3-c91173e760db.png">

일단 빈입력일때만 유효하지 않은 입력으로 처리해서 수정했습니다!

2022-08-12 11:02 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +						size={25}
react-icons에서 size라는 옵션으로 width, height를 동일하게 줄수있다고 해서 한번 사용해봤습니다!

2022-08-15 10:06 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/hooks/usePutUserProfile.tsx
> +	};
백엔드와 협의된 최소 닉네임 길이가 없는건가요?

2022-08-15 10:08 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +						size={25}
react-icons크기 수정할때에 계속해서 font-size로 수정했었는데,,,! 해당 부분을 활용해서 크기 수정하는건 어떨까요?

2022-08-15 15:26 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/hooks/usePutUserProfile.tsx
> +	};
아직 얘기가 없어서 빈 값으로 넣었습니다! 상의후에 수정하겠습니다~

2022-08-15 15:30 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +						size={25}
좋습니다! 수정했어요~

2022-08-16 12:18 UTC, liswktjs approved these changes

2022-08-16 12:18 UTC, merged