변경된 좋아요 api 명세에 맞춰서 코드 수정
woowacourse-teams/2022-gong-seek pull request #303
Opened 2022-08-11 14:16 UTC by hwangstar156

## 구현사항
- 백엔드에서 좋아요, 좋아요 취소를 했을떄 isLike와 likeCount를 리턴해줄 경우 성능이 좋지 않다고 하여 isLike와 likeCount는 state로 관리하고 다시 게시물을 불러올때 get요청으로 최신 isLike와 likeCount를 받을수 있도록 수정

2022-08-12 01:43 UTC, liswktjs requested changes
api 명세가 변경되었으면, 타입이랑  api관련도 수정도 있어야 할 것 같은데
해당 파일들이 없어서 좀 혼란스럽네요 
좋아요 flow랑 api 명세좀 설명해줄 수 있나요? 제가 재택이라 rest docs를 확인을 못합니당

2022-08-12 01:43 UTC, liswktjs commented on frontend/src/hooks/useHeartClick.tsx
> +	} = useMutation<unknown, AxiosError, string>(`like${articleId}`, postAddLikeArticle);
이거 타입 unknown으로 한 이유가 있나요? 저번꺼는 타입이 지정되어 있어서

2022-08-12 01:43 UTC, liswktjs commented on frontend/src/hooks/useHeartClick.tsx
> +	} = useMutation<unknown, AxiosError, string>(`unlike${articleId}`, deleteLikeArticle);
이얘도...! 왜 unknown으로 하게 되었나요

2022-08-12 05:56 UTC, hwangstar156 commented on frontend/src/hooks/useHeartClick.tsx
> +	} = useMutation<unknown, AxiosError, string>(`like${articleId}`, postAddLikeArticle);
저번에는 response가 존재해서 type을 적어주었는데 지금은 reponse가 오지 않아서 void혹은 never로 바꿔도 될것같습니다!

2022-08-12 06:01 UTC, hwangstar156 commented
api명세는 현재 노션에 있는것과 동일합니다!

변경된 것은 원래 likeCount와 isLike를 받아서 사용했는데 백엔드에서 성능이 좋지 않다고 하여서 response를 주지않고 좋아요를 클릭해서 isSuccess가 되면 그때 likeCount를 1올리고 isLike를 true로 state를 통해서 관리해주었습니다. 그렇게 되면 사실 실제 서버상태를 쓰고있는건 아니지만 성공을한다면 likeCount가 1증가하고 isLike가 true가 되는건 당연한 결과니까 다시 fetch하기 전까지는 local state를 통해 보여주고 새로고침이나 다시 게시물을 받아올때는 isLike, likeCount가 response로 오기때문에 최신 상태를 유지할수 있게 하였습니다!

2022-08-12 11:05 UTC, hwangstar156 commented on frontend/src/hooks/useHeartClick.tsx
> +	} = useMutation<unknown, AxiosError, string>(`like${articleId}`, postAddLikeArticle);
never, void는 에러가 나네요.. 그냥 AxiosResponse로 변경했습니다!

2022-08-15 10:11 UTC, liswktjs approved these changes

2022-08-15 10:14 UTC, merged