모든 해시태그 조회 기능 구현
woowacourse-teams/2022-gong-seek pull request #338
Opened 2022-08-12 11:59 UTC by brorae

# 구현사항
- Article, ArticleTag 양방향으로 변경
- ArticleService에서 TagService 의존하도록 변경
- 모든 해시태그 조회 기능 구현

ArticleService에서 TagService를 의존하는 메서드는 아직은 도메인을 반환하고 있습니다. 통일성 있도록 DTO를 반환하는 것이 맞다고 생각하는데 어떻게 생각하시나요?

Close #317

2022-08-15 16:42 UTC, hanull requested changes
수고하셨어요!
몇가지 코멘트 남겼으니 확인 부탁드려요!

2022-08-15 16:42 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryTest.java
> +    private TestEntityManager testEntityManager;
TestEntityManager 가 왜 필요한가요?!
없어도 테스트 잘 통과하는 것 같아요!

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Name.java
> +        this.value = value.trim().toUpperCase();
👍

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        ArticleTags articleTags = article.getArticleTags();
```suggestion
        List<ArticleTag> articleTags = article.getArticleTags().getArticleTags();
        return articleTags.stream()
                .map(articleTag -> articleTag.getTag().getName().getValue())
                .collect(Collectors.toList());
```

List로 뽑아서 사용하는건 어떤가요?

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>          Tags tags = new Tags(getTags(articleRequest.getTag()));
getTages 메서드에서 수행하고 있는 변환 로직을 Tags 일급컬렉션 내부에서 수행하도록 변경할 수 있겠네요! 그러면 해다 Service 클래스에서 getTages는 삭제해도 되겠네요


```suggestion
        Tags tags = Tags.from(articleRequest.getTag());
```

```java
public static Tags from(List<String> tag) {
    return new Tags(tag.stream()
            .map(Tag::from)
            .collect(Collectors.toList()));
}
```

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
현재 로직이 1. 요청 데이터로 tags 를 만들고, 2. 조회하거나 저장하는 것 같아요. 그런데 첫 번째 과정이 불필요한 것 같아요.
이 과정을 한 번으로 줄일 수 있을 것 같아요.

```java
Tags tags = tagService.getOrCreateTags(articleRequest.getTag());
article.addTag(tags);
```

```java
public Tags getOrCreateTags(List<String> tagNames) {
    return new Tags(tagNames.stream()
            .map(this::getOrCreateTagIfNotExist)
            .collect(Collectors.toList()));
}
```

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Article.java
> +        this(
가독성이 훨씬 좋아졌네요 👍

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +        this.articleTags = new ArrayList<>();
```java
this(new ArrayList<>());
```

요렇게도 해볼 수 있겠네요

2022-08-15 16:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +        return TagsResponse.of(tags);
정적 팩터리 메서드 네이밍을 할 때, `of`와 `from`을 자주 사용하는데 어떤 기준으로 다르게 사용할까요?
레넌의 기준이 있나요?

2022-08-16 02:16 UTC, Gyuchool requested changes
수고하셨습니다~! 몇 가지 의견남겼습니다~.~

2022-08-16 02:16 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +    @OneToMany(mappedBy = "article", orphanRemoval = true, cascade = CascadeType.ALL)
`CascadeType`을 ALL로 거신 이유가 있나요?

2022-08-16 02:21 UTC, jurlring reviewed
레넌~~ 저번 코드에서 못남긴 리뷰가 있어서 여기에도 남겨요!
- Tags에 매직넘버를 상수화해주세요!
- Tag와 연관되어 있는 엔티티가 삭제되었을 때 생각한대로 동작하는지 테스트도 추가되야할 것 같아요.

구현하시느라 고생하셨습니다~~ 작은거 같은 코멘트를 몇개 남겼어요 👀

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>          Tags tags = new Tags(getTags(articleRequest.getTag()));
저도 getTags로직이 일급컬렉션에 있는 것이 좋다고 생각해요!

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
일급컬렉션 내부에 검증 로직이 있어서 그렇게 하면 검증 로직을 안탈 것 같아요!

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
tagService.getOrCreateTags에서 일급컬렉션을 뽑아도 괜찮지 않을까요?

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>      }
이 메서드가 먼저 사용되니까 getTags 메서드 위에 두는게 좋을 것 같아요!

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>      }
articleTags는 하나의 article에 대한 tags니까 article에서 tags를 뽑는 것은 어떨까요?

2022-08-16 02:21 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +    }
readOnly = true인데 save로직이 있네요!

2022-08-16 03:52 UTC, brorae commented on backend/src/test/java/com/woowacourse/gongseek/acceptance/TagAcceptanceTest.java
> +        // given
when, then 도 추가해주었습니다.

2022-08-16 03:54 UTC, brorae commented on backend/src/test/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryTest.java
> +    private TestEntityManager testEntityManager;
저장하고 영속성 컨텍스트를 비워주고 조회해 주어야 조회할 때, 영속성 컨텍스트에서 찾아오지 않고 디비에 쿼리를 보내서 조회해 오기 때문입니다 :)

2022-08-16 03:56 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        ArticleTags articleTags = article.getArticleTags();
수정했습니다!

2022-08-16 04:02 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>          Tags tags = new Tags(getTags(articleRequest.getTag()));
수정하였습니다!

2022-08-16 04:06 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +        this.articleTags = new ArrayList<>();
현재 생성자가 기본생성자밖에 안열려있어서 안될 것 같습니다 :)

2022-08-16 04:08 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +        return TagsResponse.of(tags);
저는 개인적으로 객체를 통해 primitive한 값을 만들때(Tag -> String)에는 of를 사용하고, primitive 값을 객체로 변환할 때(String -> tag)는 from을 쓰는 편입니다.

2022-08-16 04:10 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
주디말대로 Tags내의 검증로직(중복, 길이)을 검증하기 위해 Tags를 한번 거치도록했습니다. 더 좋은 방법이 있으면 의견 내주세요!

2022-08-16 05:58 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<Tag> foundTags = tagService.getOrCreateTags(tags);
수정했습니다!

2022-08-16 05:58 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        return articleTags.getArticleTags().stream()
동의합니다. value로 수정해주었습니다.

2022-08-16 05:58 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
수정했습니다.

2022-08-16 06:05 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>      }
그러네요! 해당 로직을 Article로 이동시켜주었습니다.

2022-08-16 06:22 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +    public List<Tag> getOrCreateTags(Tags tags) {
해당 메서드를 ArticleService에서 사용하고 있어 ArticleService에 있는 @Transactional 어노테이션으로 적용되어 정상적으로 작동되었어요. @Transactional 어노테이션을 붙이면, 해당 메서드를 현재는 컨트롤러에서 사용하고 있지 않지만, 사용하게 된다면 태그들이 정상적으로 저장될 것 같아요. 우선, @Transactional을 적용해주었지만 이 부분에 대해서도 고민해보면 좋을 것 같습니다.

2022-08-16 06:22 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +    }
https://github.com/woowacourse-teams/2022-gong-seek/pull/338#discussion_r946270807

2022-08-16 06:24 UTC, brorae commented on backend/src/test/java/com/woowacourse/gongseek/article/application/ArticleServiceTest.java
> +                .orElse(null);
특별한 이유는 없지만, Test이기 때문에 조회시에 원하지 않는 값이 나올 일이 없다고 생각하여 일단 null로 꺼내주었습니다.
get()과 별 차이가 없다고 생각되어 get()으로 변경했습니다.

2022-08-16 06:33 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +    @OneToMany(mappedBy = "article", orphanRemoval = true, cascade = CascadeType.ALL)
article저장 시에 함께 영속화 되어 저장되어야하고, 삭제될 때도 마찬가지로 삭제되어야하기 때문입니다.

2022-08-16 06:45 UTC, brorae commented
> 레넌~~ 저번 코드에서 못남긴 리뷰가 있어서 여기에도 남겨요!
> 
> * Tags에 매직넘버를 상수화해주세요!
> * Tag와 연관되어 있는 엔티티가 삭제되었을 때 생각한대로 동작하는지 테스트도 추가되야할 것 같아요.
> 
> 구현하시느라 고생하셨습니다~~ 작은거 같은 코멘트를 몇개 남겼어요 👀

Article이 삭제되었을 때 ArticleTag도 삭제되는지 확인하는 테스트를 어떻게 작성하면 좋을까요??

2022-08-16 09:00 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        article.addTag(new Tags(foundTags));
슬로 말씀대로 하면 tagNames에 중복된 값이 있으면, DB로 쿼리를 날린 후에 예외가 발생할 것 같아요 :(

2022-08-16 09:04 UTC, hanull approved these changes
리뷰 반영 확인했습니다

2022-08-16 10:15 UTC, Gyuchool approved these changes
수고하셨어요~ 마지막으로 궁금한 부분 커멘트 남겼습니다!

2022-08-16 10:15 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepository.java
> +    @Query("SELECT case WHEN (count(at) > 0) THEN true ELSE false END FROM ArticleTag at WHERE at.tag.name = :name")
위처럼 하면 count 쿼리가 나가는건가요? 나간다면 limit(1)으로 성능을 개선하면 좋을 것 같습니다.

2022-08-16 10:32 UTC, jurlring approved these changes
고생하셨습니다~

2022-08-16 10:32 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +    @OneToMany(mappedBy = "article", orphanRemoval = true, cascade = CascadeType.ALL)
그럼 Persist랑 Delete만 걸면 되지 않을까용?

2022-08-16 10:32 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Tags.java
> +        if (tags.size() > MAX_TAGS_SIZE) {
👍

2022-08-16 10:32 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Tags.java
>              throw new ExceededTagsException();
size가 넘어간다 이런 의미여야할 것 같아요!

2022-08-16 11:01 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/articletag/ArticleTags.java
> +    @OneToMany(mappedBy = "article", orphanRemoval = true, cascade = CascadeType.ALL)
저장하고 삭제되는 부분만 사용되므로 Persist와 Delete만 거는 것으로 수정했습니다.

2022-08-16 11:04 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Tags.java
>              throw new ExceededTagsException();
ExceededTagSizeException으로 변경했습니다!

2022-08-16 11:20 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepository.java
> +    @Query("SELECT case WHEN (count(at) > 0) THEN true ELSE false END FROM ArticleTag at WHERE at.tag.name = :name")
MySQL의 case when then 문법을 이용합니다. 확인해보니 count 쿼리는 나가지 않는 것 같아요.

2022-08-16 11:25 UTC, merged