해시태그를 검색 및 조회를 할 수 있도록 한다
woowacourse-teams/2022-gong-seek pull request #344
Opened 2022-08-15 07:34 UTC by liswktjs

Close #296 

develop 브랜치에 반영된 HashTag들이 필요헤서 develop에서 부터 merge작업을 진행하였습니다 

구현 사항 
해시태그로 검색하기 페이지 구현 
해당 페이지 내에서 해시태그 목록들을 조회 후 표시 
표시된 해시태그들을 클릭하면, mutate를 통해서 검색 진행 
검색 결과 들의 경우 아래에 표기됨 

*api 메서드가 GET임에도 useMutation을 사용한 이유 
같은 페이지 내에서 검색과 검색 결과가 둘다 보여 져야 하고 맨 처음 화면이 로드 될 때에는 검색이 불필요하기 때문에 useMutation를 활용하여 실험진행

2022-08-16 13:07 UTC, hwangstar156 requested changes

2022-08-16 13:07 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/HashTagSearchBox/HashTagSearchBox.tsx
> +					  ))}
<img width="214" alt="스크린샷 2022-08-16 오후 9 59 49" src="https://user-images.githubusercontent.com/85891751/184885708-99b55d41-d82c-4cac-bf44-d0075d1752ad.png">
slice는 원본 배열보다 더 커질시 원본 배열 자체를 반환하네요! 삼항 연산자를 지우고 바로 `target.slice(0,5)`로 작성해도 될것같습니다!

2022-08-16 13:07 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/HashTagSearchResult/HashTagSearchResult.tsx
> +			{articles && articles.length >= 1 ? (
type에 undefined도 null도 없는데 articles가 없는경우가 존재하나요? 타입을 변경해야 되는 부분일까요?

2022-08-16 13:07 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/index.tsx
> +		});
마지막의 return은 필요한가요?

2022-08-16 13:07 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/index.tsx
> +	}, [targetHashTags]);
selectedHashTagList가 있으면 length를 판단하는데 selectedHashTagList는 map을 돌린 결과물인데 undefined나 null이 나올 경우가 있을까요?

2022-08-17 02:33 UTC, liswktjs commented on frontend/src/pages/HashTagSearch/HashTagSearchBox/HashTagSearchBox.tsx
> +	};
함수이름을 onClickTarget으로 하라는 건가요?????🤔 어떻게 바꾸라는 건지 잘 와닿지 않네요

2022-08-17 02:34 UTC, liswktjs commented on frontend/src/pages/HashTagSearch/HashTagSearchResult/HashTagSearchResult.tsx
> +			{articles && articles.length >= 1 ? (
검색결과가 없는 경우 articles가 빈배열로 넘어오기 때문에 해당 처리를 해주었습니다

2022-08-17 02:34 UTC, liswktjs commented on frontend/src/pages/HashTagSearch/index.tsx
> +		});
map에서는 마지막 return을 적어주지 않으면 에러나 나니깐요...?

2022-08-17 02:37 UTC, liswktjs commented on frontend/src/pages/HashTagSearch/index.tsx
> +	}, [targetHashTags]);
선택된 해시태그가 존재하지 않으면 mutate까지 가지 못하도록 처리 한 것입니당
아무런 해시태그도 선택하지 않을 수 있으니깐요?

2022-08-17 08:00 UTC, liswktjs commented
해시태그로 게시물 검색해서 보여주는 거 무한스크롤로 보여주는방식이 바뀌어서 바뀐 내용이 좀 더 많아졌습니다

2022-08-17 11:30 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/HashTagSearchBox/HashTagSearchBox.tsx
> +	};
onClickTarget이 좋을것 같습니다!

2022-08-17 11:30 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/HashTagSearchResult/HashTagSearchResult.tsx
> +			{articles && articles.length >= 1 ? (
빈배열이면 article.length >= 1 만 써도 처리되는거 아닌가요?

2022-08-17 11:31 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/index.tsx
> +		});
map인지 몰랐네요! 그런데 저렇게 하면 배열에 빈부분이 생기지 않나요? isChecked에 따라서 filter를 한후 item.name만 받아오도록 map을 쓰는게 어떤가요?

2022-08-17 11:32 UTC, hwangstar156 commented on frontend/src/pages/HashTagSearch/index.tsx
> +	}, [targetHashTags]);
아무런 해시태그를 선택하지 않으면 빈배열아닌가요? 빈배열이면 length 처리만 해도 되지않나요?

2022-08-18 07:12 UTC, hwangstar156 approved these changes

2022-08-18 07:23 UTC, merged