해시태그 생성시 제한 조건 추가
woowacourse-teams/2022-gong-seek pull request #346
Opened 2022-08-15 10:05 UTC by liswktjs

Close #345 

해시태그 입력시 공백 제거 후 판단 
대소문자 상관없이 중복일 경우 입력 제한 
placeholder에 엔터를 입력하라는 문구 추가

2022-08-15 15:04 UTC, hwangstar156 requested changes

2022-08-15 15:04 UTC, hwangstar156 commented on frontend/src/components/common/HashTag/HashTag.tsx
> +		}, false);
중복처리하는 함수인것 같은데
```suggestion
	const checkIsDuplicateHashTag = (hashtag: string) => {
	   const checkSet = new Set(hashTags.map(hashTag => hashTag.toLowerCase()));
	   const prevLength = checkSet.size;
	   checkSet.add(hashtag.toLowerCase());
	   
	   return prevLength === checkSet.size;
	}
```
이런식의 변경도 가능하지 않을까요??

2022-08-15 15:04 UTC, hwangstar156 commented on frontend/src/pages/Login/RefreshTokenHandler/RefreshTokenHandler.tsx
> +			showSnackBar('재로그인 되었습니다');
이 코드의 순서변경의 이유가 있을까요?

2022-08-15 15:04 UTC, hwangstar156 commented on frontend/src/pages/Login/RefreshTokenHandler/RefreshTokenHandler.tsx
> +			showSnackBar('재로그인 되었습니다');
이 코드의 순서변경의 이유가 있을까요?

2022-08-17 08:04 UTC, liswktjs commented on frontend/src/components/common/HashTag/HashTag.tsx
> +		}, false);
엄.. 가능은 하겠지만 바꿀 이유를 잘 모르겠네요 reduce는 이럴때 쓸려고 사용한다고 개인적으로 생각해서

2022-08-17 08:04 UTC, liswktjs commented on frontend/src/components/common/HashTag/HashTag.tsx
> +		}, false);
엄... 가능은 하겠지만 굳이도 싶네요? 개인적으로 reduce로 이런거 처리하는 게 좋을 것 같아서요

2022-08-17 08:05 UTC, liswktjs commented on frontend/src/pages/Login/RefreshTokenHandler/RefreshTokenHandler.tsx
> +			showSnackBar('재로그인 되었습니다');
별 이유는 없습니다만, 코드의 흐름삼 경고메세지는 마지막에 위치해야할 것 같아서요

2022-08-17 08:05 UTC, liswktjs commented on frontend/src/pages/Login/RefreshTokenHandler/RefreshTokenHandler.tsx
> +			showSnackBar('재로그인 되었습니다');
위와 동일합니다~

2022-08-17 11:33 UTC, hwangstar156 commented on frontend/src/components/common/HashTag/HashTag.tsx
> +		}, false);
여기서는 큰 문제는 없겠지만 불필요한 시간복잡도를 이용해서 처리하는것 같아서 Set을 추천했습니다

2022-08-17 11:34 UTC, hwangstar156 approved these changes

2022-08-17 12:21 UTC, merged