투표가 없는 경우 만들수 있는 ui 추가
woowacourse-teams/2022-gong-seek pull request #374
Opened 2022-08-16 10:36 UTC by hwangstar156

close #360 

## 구현사항

투표가 없는경우에 작성자인지 판단하여 작성자일 경우 투표 만들기 버튼을 아닐 경우에는 빈 컴포넌트를 보여주도록 구현
<img width="374" alt="스크린샷 2022-08-16 오후 7 34 35" src="https://user-images.githubusercontent.com/85891751/184859360-3b639a10-74ce-4b51-a41d-709500611965.png">

2022-08-16 12:25 UTC, liswktjs requested changes
코멘트 몇개 남겼습니다 코드 수정해주세요~

2022-08-16 12:25 UTC, liswktjs commented on frontend/src/App.tsx
> +	min-height: calc(100vh - 2 * ${({ theme }) => theme.size.SIZE_126});
? develop에 min-height 반영했던 것 같은데 혹시 develop에서 push 안받고 시작했나요

2022-08-16 12:25 UTC, liswktjs commented on frontend/src/pages/DiscussionDetail/VoteGenerateButton/VoteGenerateButton.tsx
> +`;
데시크탑일 때에 대응이 필요할 것 같습니다 
데스크탑일 때까지 width가 90%로 이면 너무 거대할 것 같아요

2022-08-16 12:25 UTC, liswktjs commented on frontend/src/pages/DiscussionDetail/index.tsx
> +			{typeof articleData !== 'undefined' && typeof commentData !== 'undefined' && (
만약에 에러가 발생하지 않고 여기 까지 왔는데 articleData나 commentData가 비어있을 때에 대응 코드가 필요할 것 같아요

2022-08-16 13:25 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	min-height: calc(100vh - 2 * ${({ theme }) => theme.size.SIZE_126});
머지되기전에 만든 branch인것 같네요!

2022-08-16 13:26 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	min-height: calc(100vh - 2 * ${({ theme }) => theme.size.SIZE_126});
따로 충돌해결하겠습니다~

2022-08-16 13:48 UTC, hwangstar156 commented on frontend/src/pages/DiscussionDetail/VoteGenerateButton/VoteGenerateButton.tsx
> +`;
<img width="1378" alt="스크린샷 2022-08-16 오후 10 41 14" src="https://user-images.githubusercontent.com/85891751/184895731-ca28ad4b-0ed4-4da5-80c8-83c582783380.png">

width 수정하였습니다! 그래도 조금 이상한것 같네요.. 나중에 한번 다시 봐야겠습니당

2022-08-16 13:49 UTC, hwangstar156 commented on frontend/src/pages/DiscussionDetail/index.tsx
> +			{typeof articleData !== 'undefined' && typeof commentData !== 'undefined' && (
articleData가 빈경우는 없을것같고 commentData가 비어있는 경우에 `첫번째 댓글을 입력해주세요` 메시지로 처리해주었습니다!

2022-08-17 02:28 UTC, liswktjs commented on frontend/src/pages/DiscussionDetail/VoteGenerateButton/VoteGenerateButton.tsx
> +`;
그럼 해당 부분까지 반영해서 리뷰요청 다시 해주세요~

2022-08-18 07:10 UTC, liswktjs approved these changes

2022-08-18 07:47 UTC, merged