검색시, 유저의 이름과 게시물에 관한 검색을 분리한다
woowacourse-teams/2022-gong-seek pull request #377
Opened 2022-08-16 13:13 UTC by liswktjs

Close #373 

- 유저와 게시물 관련해서 각각 api 명세 변경에 따라서 선택할 수 있는 ui 구현 
- SortDropDown을 활용하여 유저와 게시물 중 하나를 선택하도록 구현 
- searchIndex 상태를 추가하여 searchIndex에 따라서 비동기 통신 요청을 다르게 보냄 

* 현재 관련 api 가 구현이 완료 되지 않아 추후에 추가 확인이 필요함

2022-08-16 13:22 UTC, hwangstar156 requested changes

2022-08-16 13:22 UTC, hwangstar156 commented on frontend/src/components/common/SearchBar/SearchBar.styles.tsx
> +	width: ${(props) => (props.isSearchOpen ? '75%' : '100%')};
이건 어떤 동작을 원하고 한건가요?

2022-08-16 13:22 UTC, hwangstar156 commented on frontend/src/api/search.ts
> +	}
아예 이부분과 그 뒷부분을 각각의 함수로 분리하는것이 어떨까요?

2022-08-17 02:39 UTC, liswktjs commented on frontend/src/components/common/SearchBar/SearchBar.styles.tsx
> +	width: ${(props) => (props.isSearchOpen ? '75%' : '100%')};
검색 창이 열렸을 때에만 이름, 게시물을 선택하는 부분을 보여주고 싶었습니다
SearchBar의 경우 검색 창이 열리든 열리지 않든 계속해서 보여지기 때문에  width값을 줄여야  선택하는 부분이 보여집니다

2022-08-17 11:29 UTC, hwangstar156 approved these changes

2022-08-18 08:53 UTC, merged