해시태그로 게시글 조회 기능 구현
woowacourse-teams/2022-gong-seek pull request #378
Opened 2022-08-16 15:17 UTC by brorae

- 해시태그로 게시글 조회 기능 구현

Close #376

2022-08-17 02:22 UTC, Gyuchool requested changes
수고하셨습니다~! api문서화가 안된 거 같은데 문서화 추가하시면 될 것 같아요!

2022-08-17 02:22 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Name.java
> +//package com.woowacourse.gongseek.tag.domain;
주석 지우셔도 될 것 같아요!

2022-08-17 02:22 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/repository/TagRepository.java
> +//    List<Tag> findByNameIgnoreCaseIn(List<String> names);
여기도 주석이 있네요!

2022-08-17 02:22 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/tag/domain/NameTest.java
> +//package com.woowacourse.gongseek.tag.domain;
여기도 주석이요~.~

2022-08-17 02:22 UTC, Gyuchool commented on backend/src/test/java/com/woowacourse/gongseek/tag/domain/repository/TagRepositoryTest.java
> +//    @Test
여기도요..

2022-08-17 02:26 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Name.java
> +//package com.woowacourse.gongseek.tag.domain;
사용하지 않는 클래스인데 삭제하는 것을 깜빡했네요. 삭제했습니다!

2022-08-17 02:26 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/repository/TagRepository.java
> +//    List<Tag> findByNameIgnoreCaseIn(List<String> names);
사용하지 않는 메서드인데 삭제하는 것을 깜빡했네요. 삭제했습니다!

2022-08-17 04:56 UTC, jurlring reviewed
레넌 고생하셨어요~ 
코멘트를 남겼는데 확인 부탁드려요!

2022-08-17 04:56 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>                  .forEach(tagService::delete);
stream.foreach에서 delete 실행시에 문제가 생기면 어떻게 될까요?

2022-08-17 04:56 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<String> tagNames = tagService.extract(tagsText);
단순 변환 로직인데 다른 의존성을 사용해야할까요?
그렇다면 이 메서드가 여기 있는 것이 맞을까요?

2022-08-17 05:26 UTC, hanull requested changes
수고하셨어요! 몇 가지 코멘트 남겼습니다. 확인해주세요~

2022-08-17 05:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Article.java
>                  .collect(Collectors.toList());
`articleTags.getNames()` 
ArticleTags 안에서 처리하도록 변경할 수 있겠네요

2022-08-17 05:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        return new ArticlesByTagResponse(responses);
response 반환 로직이 dto 내에서 수행되도 좋을 것 같아요

2022-08-17 05:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<String> tagNames = tagService.extract(tagsText);
tagsText 를 tagNames로 변경하고, extract를 인라인으로 변경하는 건 어떤가요??!

2022-08-17 05:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
> +    public List<String> extract(String tagsText) {
findByNameIgnoreCase 대소문자 구별없이 찾고 있기 때문에
대문자로 변경해주는 extract 메서드가 불필요해 보여요! 한 번 확인해주세요

2022-08-17 05:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/tag/domain/Tag.java
> +    @Column(name = "name", nullable = false, length = MAX_NAME_LENGTH)
👍

2022-08-17 05:26 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/article/application/ArticleServiceTest.java
> +        thirdArticle.addTag(new Tags(List.of(react)));
여기까지 given 인 것 같은데, 중간중간 공백이 있어서 헷갈리는 것 같네요.
given을 다 붙여서 쓰던가, 주석을 달아주면 좋을 것 같아요

2022-08-17 10:35 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/ArticleController.java
> +    @GetMapping("/tags")
주디 말대로 계층 관계를 나타내기 위해서 tags보다 큰 개념인 articles를 먼저 작성해주었어요. tag를 조회하는 API에서 tagId를 반환하지 않아서 tagId는 쓰기 어려울 것 같아요. `/api/articles/search/tags`로 변경했습니다!

2022-08-17 10:52 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/Article.java
>                  .collect(Collectors.toList());
그렇네요! 수정했습니다.

2022-08-17 10:54 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        return new ArticlesByTagResponse(responses);
`getArticlePreviewResponse` 메서드로 변환하는 로직이 service에 존재하여 서비스내에서 해줘야할 것 같습니다!

2022-08-17 11:00 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<String> tagNames = tagService.extract(tagsText);
요청을 받을때, tagsText로 해시태그의 이름들을 받고있어요. 해당 파라미터 이름을 유지하기 위해서 서비스에서도 동일한 이름으로 적용해주었습니다. 인라인으로 하는 것은 좋은 것 같아요!

2022-08-17 11:01 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<String> tagNames = tagService.extract(tagsText);
원래는 Tag 테이블에서 Tag 엔티티로 변환하여 줄 생각이었는데, 그렇게 사용할 필요가 없네요!
해당 로직을 ArticleService로 이동해주었습니다!

2022-08-17 11:07 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
>                  .forEach(tagService::delete);
반복문을 도는 도중에 다른 쓰레드에 의해 수정될 수 있고, 무조건 요소의 끝까지 반복을 돌아야 예외가 발생하겠네요.
향상된 for문으로 변경해주었습니다!

2022-08-17 11:39 UTC, jurlring reviewed
레넌 고생하셨어요~~ 
코멘트를 남겼는데 확인 부탁드려요~

2022-08-17 11:39 UTC, jurlring commented on backend/src/docs/asciidoc/article.adoc
> +include::{snippets}/articles-search-by-tag/response-fields.adoc[]
👍

2022-08-17 11:39 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +            tagService.delete(deletedTagName);
service가 service를 의존해야할까요?

2022-08-17 11:39 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .fetch();
😱 🙀

2022-08-17 11:39 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
>      }
삭제할 때는 대소문자 구분을 안해도 되나요?

2022-08-18 04:04 UTC, Gyuchool approved these changes
수고하셨습니다~ 작은 의견 하나 남겼습니다!

2022-08-18 05:41 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/tag/application/TagService.java
>      }
대소문자 구문없이 삭제할 수 있도록 수정했습니다!

2022-08-18 05:42 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +            tagService.delete(deletedTagName);
deleteByTagNameIn으로 List에 포함된 태그를 삭제하도록 해주었습니다!

2022-08-18 05:46 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +            tagService.delete(deletedTagName);
Tag에 관한 로직을 ArticleService에 두니 너무 많은 로직을 담당하고 있다는 생각이 들었습니다. 또, 모듈을 Article과 Tag로 나누었는데 Tag와 관련된 로직이 Article이 있는게 어색하게 느껴졌어요. 주디는 어떻게 생각하시나요??

2022-08-18 06:56 UTC, hanull approved these changes
수고하셨습니다!! 코멘트 하나 남겼어요

2022-08-18 06:56 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/article/application/ArticleServiceTest.java
> +
공백 제거하거나, 주석 달면 좋겠네요

2022-08-18 07:05 UTC, merged