깃헙 로그인시 취소누를 경우 에러핸들링 추가
woowacourse-teams/2022-gong-seek pull request #391
Opened 2022-08-17 04:50 UTC by hwangstar156

close #390 

## 수정사항
깃헙 로그인할때 취소누를시 에러를 던지는 대신 홈으로 돌려보내도록 수정

2022-08-17 05:29 UTC, liswktjs requested changes
깃허브 로그인 취소시 정해진 코드가 없는건가요???

2022-08-17 06:01 UTC, hwangstar156 commented
백엔드에서 던져주는 에러가 아니라 저희가 쿼리스트링에서 code가 Null인지 확인하는거여서 따로 코드는 없습니다!

2022-08-17 10:50 UTC, liswktjs requested changes

2022-08-17 10:50 UTC, liswktjs commented on frontend/src/pages/Login/LoginController/LoginController.tsx
> +		navigate('/');
이부분에서 바로 홈으로 이동시키지 말고 유저에게 안내메시지를 보여주면 좋을 것 같습니다 
showSnackBar활용해서 
'깃허브 로그인에 동의해주세요' 같은 문구로 보여주면 좋을 것 같습니다

2022-08-17 11:37 UTC, hwangstar156 commented on frontend/src/pages/Login/LoginController/LoginController.tsx
> +		navigate('/');
취소를 했는데 굳이 깃허브 로그인에 동의해달라고 알릴필요가 있을까요?

2022-08-18 02:08 UTC, liswktjs commented on frontend/src/pages/Login/LoginController/LoginController.tsx
> +		navigate('/');
넹 실수로 취소를 눌러서 튕기는 경우도 있을 수 있으니깐 최대한 유저 친화적으로 개발해주셨으면 좋겠습니다

2022-08-18 07:45 UTC, hwangstar156 commented on frontend/src/pages/Login/LoginController/LoginController.tsx
> +		navigate('/');
수정했습니다!

2022-08-18 08:51 UTC, liswktjs approved these changes

2022-08-18 08:51 UTC, merged