로그인, 마이페이지를 헤더에 보여주는것에서 드롭다운으로 변경한다.
woowacourse-teams/2022-gong-seek pull request #455
Opened 2022-08-30 08:05 UTC by hwangstar156

close #446 

## 구현사항
<img width="1792" alt="스크린샷 2022-08-30 오후 4 49 01" src="https://user-images.githubusercontent.com/85891751/187381763-dd9105f1-27c9-4849-8581-d600680abe8b.png">
<img width="479" alt="스크린샷 2022-08-30 오후 5 03 24" src="https://user-images.githubusercontent.com/85891751/187383875-578d30bd-620d-40c5-8de7-17b83287a23e.png">

2022-08-30 08:35 UTC, liswktjs requested changes

2022-08-30 08:35 UTC, liswktjs commented on frontend/src/App.tsx
> +import { dropdownState } from './store/dropdownState';
절대경로 🚨

2022-08-30 08:35 UTC, liswktjs commented on frontend/src/components/common/UserProfileIcon/UserProfileIcon.tsx
> +			)}
실패했을 경우에 대응 코드도 있어야 할 것 같아요 
공식 이미지를 default로 보여주는 것도 좋을 것 같네요

2022-08-30 08:35 UTC, liswktjs commented on frontend/src/components/layout/TabBar/TabBar.tsx
> +	if (isLoading) return <Loading />;
tabBar 로딩 중일 때에 로딩 스피너를 보여주게 되면 UI가 깨질 것 같은데 고민되긴 하네요 
로딩 중일 때는 다른 스피너를 보여주거나 기본 이미지를 보여주는 것도 좋을 것 같네요

2022-08-30 08:35 UTC, liswktjs commented on frontend/src/components/layout/TabBar/TabBar.tsx
> +					<UserProfile src={data?.avatarUrl} onClick={() => navigate('/my-page')} />
해당 경우에도 유저 프로필 이미지 로딩에 실패했을 때에 대비책이 있으면 좋을 것 같네용

2022-08-31 06:09 UTC, hwangstar156 commented on frontend/src/App.tsx
> +import { dropdownState } from './store/dropdownState';
수정했습니다!

2022-08-31 06:10 UTC, hwangstar156 commented on frontend/src/components/common/UserProfileIcon/UserProfileIcon.tsx
> +			)}
수정했습니다! 다른것들도 로딩중일때는 공식 기본 이미지를 보여주도록 수정했습니다.👍

2022-09-06 04:45 UTC, liswktjs approved these changes

2022-09-08 02:11 UTC, merged