투표 글 작성시 에러 메세지 보여주기
woowacourse-teams/2022-gong-seek pull request #483
Opened 2022-09-06 04:24 UTC by hwangstar156

close #468 
close #471 

- 중복된 상황, 빈 입력일때 에러메시지를 보여줌
- 유효한 입력일때는 `유효한 입력입니다`를 보여줌

<img width="658" alt="스크린샷 2022-09-06 오후 1 23 29" src="https://user-images.githubusercontent.com/85891751/188546649-b33f2afc-04d2-4370-b919-c81e4a8299a6.png">

<img width="773" alt="스크린샷 2022-09-06 오후 1 23 39" src="https://user-images.githubusercontent.com/85891751/188546661-c2298f72-29e1-4225-aaae-fb5bf93f7507.png">

<img width="724" alt="스크린샷 2022-09-06 오후 1 23 48" src="https://user-images.githubusercontent.com/85891751/188546626-5969152b-9257-4293-8af1-21dd5b8faa9f.png">

2022-09-06 06:10 UTC, liswktjs requested changes

2022-09-06 06:10 UTC, liswktjs commented on frontend/src/pages/VoteGenerator/index.tsx
> +			return '투표목록은 최소 1글자이상 이여야합니다.';
최대 글자수에 대해서도 추가해줘야 겠네요!

2022-09-16 05:29 UTC, hwangstar156 commented on frontend/src/pages/VoteGenerator/index.tsx
> +			return;
focus를 주어서 수정하였습니다!

2022-09-16 05:29 UTC, hwangstar156 commented on frontend/src/pages/VoteGenerator/index.tsx
> +			return '투표목록은 최소 1글자이상 이여야합니다.';
1글자이상 300글자이하로 다시 설정해주었습니다!

2022-09-16 06:11 UTC, liswktjs approved these changes
굿굿

2022-09-16 06:24 UTC, merged