게시물 임시저장 기능을 구현한다
woowacourse-teams/2022-gong-seek pull request #509
Opened 2022-09-12 17:25 UTC by hanull

## 구현 내용
- 임시 게시글 저장
- 임시 게시글 전체 조회
- 임시 게시글 단건 조회
- 임시 게시글 삭제

## 이슈 및 고민사항
- Article과 비슷한 부분을 어떻게 처리할 것인가?
- TempArticle 엔티티의 Tags 값을 @ElementCollection 사용했을 때, 테이블을 초기화할 수 없었음 
  - 구분자(&)를 기준으로 String 값 객체를 만들어서 저장하는 방법으로 해결
- 클래스 위치를 Article 패키지에 두는 것이 괜찮을까? (현재 엔드 포인트는 다름)

Close #450

2022-09-13 13:16 UTC, Gyuchool requested changes
수고하셨습니다. 파일 체인지가 많아 리뷰를 남기다보니 많아졌네요 😅

2022-09-13 13:16 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/ArticleRequest.java
> +    private Long articleTempId;
해당 필드는 어떤 용도인가요?

2022-09-13 13:16 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/TempArticleDetailResponse.java
> +    public static TempArticleDetailResponse from(TempArticle tempArticle) {
필드가 너무 많은데 빌더패턴 적용하는거 어때요?

2022-09-13 13:16 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/TempArticleRequest.java
> +    private Boolean isAnonymous;
`@NotNull`을 걸고 래퍼타입으로 정의하신 이유가 있을까요?

2022-09-14 01:17 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/TempArticleController.java
> +                tempArticleRequest);
개행이 어색한 것 같아요!

2022-09-14 01:20 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +
다른 곳에는 final이 붙어있지 않은데 통일하는 것이 좋을 것 같아요

2022-09-14 01:23 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final TempArticle articleTemp = getArticleTemp(articleTempId);
Entity 이름과 변수 이름을 통일하면 어떨까요? 메소드 이름도요!

2022-09-14 01:27 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +            return;
예외를 안터뜨려도 괜찮을까요??

2022-09-14 01:41 UTC, jurlring approved these changes
고생하셨습니다~

임시저장에 대한 restdocs가 없네요! 추가 부탁드리고 코멘트를 달았는데 확인 부탁드려요!

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final Member member = getMember(appMember.getPayload());
```suggestion
        final Member member = getMember(appMember);
```
AppMember 그대로 넘기는게 더 가독성이 좋을 것 같아요.

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        return articleTempId != null && tempArticleRepository.existsById(articleTempId);
me too

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +                .get();
agreement

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final TempArticle tempArticle = getArticleTemp(tempArticleRequest.getId());
지역 변수마다 final을 붙이신 이유가 있나요?

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final List<TempArticle> tempArticles = tempArticleRepository.findAllByMemberId(member.getId());
```suggestion
        final List<TempArticle> tempArticles = tempArticleRepository.findAllByMember(member);
```

이렇게는 안되나요?

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/TempArticle.java
> +    private LocalDateTime createdAt;
updatedAt은 필요 없나요?

2022-09-14 01:41 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/ArticleRequest.java
> +
articleResponse를 재활용해도 될까요?

2022-09-14 03:42 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +    @Transactional
delete 부분이 빠졌네요. 추가했습니다

2022-09-14 04:09 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +                .get();
조회 및 예외 발생하는 메서드를 만들어두고 활용을 안하고 있었네요.
예외 던지도록 변경했습니다

2022-09-14 04:11 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        return articleTempId != null && tempArticleRepository.existsById(articleTempId);
articleTempId가 null 일 경우에 existsById() 를 호출하면 NPE 예외가 발생해요. 그래서 null 체크를 해줬습니다.

2022-09-14 05:56 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        }
로직을 줄일 수 있지만 줄인다면, articleTempId가 잘못되었는지 memberId가 잘못되었는지 구분이 안될 것 같아요.
이러한 이유로 현재 코드 유지할게요!

2022-09-14 06:51 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/TempArticle.java
> +    public void update(TempArticleRequest updateRequest) {
dto 변경될 때마다 도메인 코드가 변경이 생길 수도 있겠네요. 변경할게요!

2022-09-14 08:41 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/TempArticleDetailResponse.java
> +    public static TempArticleDetailResponse from(TempArticle tempArticle) {
같은 String 타입의 변수가 연속적으로 들어오기 때문에 문제가 발생할 수도 있겠네요.
빌더패턴 적용할게요!

2022-09-14 09:49 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/TempArticleController.java
> +                tempArticleRequest);
아래와 같이 변경했어요

```java
return ResponseEntity.status(HttpStatus.CREATED)
              .body(tempArticleService.createOrUpdate(appMember, tempArticleRequest));
```

2022-09-14 10:10 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +
미션하면서 적용했었는데 프로젝트에도 적용됐네요..
제거했습니다

2022-09-14 10:11 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final TempArticle articleTemp = getArticleTemp(articleTempId);
변경했습니다!

2022-09-14 10:15 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +            return;
일부로 예외를 발생시키지 않았어요.
만약 임시 저장글이 없을 때, 게시글을 생성하면 예외가 발생하게 되고 게시글 번호를 반환할 수 없어요.
그리고 delete의 경우 id 값이 null이 아니고 존재하지 않아도 예외가 터지지 않아요!

2022-09-14 10:18 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final Member member = getMember(appMember.getPayload());
getMember에서 getPayload()를 굳이 2번 호출할 필요가 없다고 생각해서 id값으로 넘겨줬어요!

2022-09-14 10:18 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final TempArticle tempArticle = getArticleTemp(tempArticleRequest.getId());
https://github.com/woowacourse-teams/2022-gong-seek/pull/509#discussion_r970604975
코멘트 참고해주세요

2022-09-14 10:25 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/application/TempArticleService.java
> +        final List<TempArticle> tempArticles = tempArticleRepository.findAllByMemberId(member.getId());
아래와 같은 방법도 가능하긴해요! 그런데 아래처럼 했을 때의 장점이 뭔지 잘 모르겠어요!

2022-09-14 10:53 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/ArticleRequest.java
> +
음 Response를 재활용해서 Request를 만드는게 아니라 ArticleRequest를 재활용해서 임시 게시글 요청에도 사용하라는 말이겠죠..?

ArticleRequest, TempArticleRequest 중복되는 부분이 많아서 TempArticleRequest 삭제하고, ArticleRequest 재활용하도록 변경했어요!

2022-09-15 08:22 UTC, jurlring approved these changes
수고하셨습니다~

2022-09-15 11:05 UTC, Gyuchool approved these changes
리뷰 반영하시느라 수고하셨어요!

2022-09-15 11:09 UTC, brorae approved these changes
수정사항 확인했습니다.
수고하셨습니다~!

2022-09-15 11:12 UTC, merged