임시 저장글을 보여줄 Item 컴포넌트를 만든다
woowacourse-teams/2022-gong-seek pull request #523
Opened 2022-09-14 07:32 UTC by liswktjs

Close #515

임시저장 게시물 리스트들 에서 저장된 것을 확인 할 수 있는 Item 컴포넌트 구현

* 임시저장 게시물 리스트 컴포넌트 구현하기 위해서는 리액트 쿼리와 합쳐진 컴포넌트가 필요하기에 api 완성까지 뒤로 미루기로 함

2022-09-16 04:23 UTC, hwangstar156 requested changes
<img width="341" alt="스크린샷 2022-09-16 오후 1 22 00" src="https://user-images.githubusercontent.com/85891751/190556255-fe18a3b9-dcb1-4be2-9be9-0b1896271941.png">

시간에 대해서 사용자 친화적으로 변경하는것이 어떨까요??

2022-09-16 04:23 UTC, hwangstar156 commented on frontend/src/storybook/Article/TemporaryArticleItem.stories.tsx
> +};
onClick: () => action('clicked') 도 넣어주어야 되지 않나요?

2022-09-19 08:00 UTC, liswktjs commented on frontend/src/storybook/Article/TemporaryArticleItem.stories.tsx
> +};
추가하였습니다!

2022-09-19 08:02 UTC, hwangstar156 approved these changes
수고하셨습니다!

2022-09-19 08:03 UTC, merged