투표에 대한 UI를 수정한다.
woowacourse-teams/2022-gong-seek pull request #581
Opened 2022-09-20 10:48 UTC by hwangstar156

close #470 
close #472 

## 구현사항

- 데스크탑에서 투표에 대해서 가로로 볼수있도록 수정
<img width="1059" alt="스크린샷 2022-09-20 오후 7 29 45" src="https://user-images.githubusercontent.com/85891751/191238744-897947d7-4f90-4235-be03-1ad23a8f30a6.png">

- 모바일에서는 세로로 볼수있으며 인풋창을 아래로 투표 항목을 위로 올림
<img width="467" alt="스크린샷 2022-09-20 오후 7 46 50" src="https://user-images.githubusercontent.com/85891751/191238505-74d39cf7-6435-4380-b633-5c27d0a2e551.png">

2022-09-21 04:40 UTC, liswktjs requested changes
<img width="466" alt="스크린샷 2022-09-21 오후 1 37 19" src="https://user-images.githubusercontent.com/60773373/191415464-38d7b2bb-a5a6-4da5-be49-e3305cd1e60e.png">
글자수가 많으면 삭제 버튼이 보이지 않습니다! 
해당 부분 수정이 필요한 것 같습니다

2022-09-21 08:36 UTC, hwangstar156 commented
<img width="1397" alt="스크린샷 2022-09-21 오후 5 36 05" src="https://user-images.githubusercontent.com/85891751/191456787-33d597bd-f22e-4e40-aaf2-52eb62d17558.png">

텍스트의 영역과 삭제 버튼의 영역을 나누어서 해결하였습니다!

2022-09-22 01:52 UTC, liswktjs requested changes
여전히 삭제 버튼이 보이지 않네용~ 다시 확인 부탁드립니다

2022-09-22 02:38 UTC, liswktjs approved these changes
확인했습니다 merge하겠습니다

2022-09-22 02:38 UTC, merged