반응형 커버를 올린다.
woowacourse-teams/2022-gong-seek pull request #586
Opened 2022-09-20 14:36 UTC by hwangstar156

close #585 

## 구현사항

현재 1280px이상, 그 외의 상태로 모든 반응형을 처리하고 있어 700px, 1000px에 대해서 중간과정을 더 넣어서 자연스럽도록 구현하였습니다.

- 기본 모바일 (700px) 이하
<img width="668" alt="스크린샷 2022-09-20 오후 10 51 48" src="https://user-images.githubusercontent.com/85891751/191279083-701eb4f6-cd3d-439f-8e93-c73ca23bb135.png">

<img width="651" alt="스크린샷 2022-09-20 오후 11 23 55" src="https://user-images.githubusercontent.com/85891751/191284288-50e23cf7-c664-4290-9269-ef566b77f44a.png">

- 700px이상 1000px 이하
<img width="757" alt="스크린샷 2022-09-20 오후 11 05 54" src="https://user-images.githubusercontent.com/85891751/191279477-2057ce82-5955-4184-bcd1-780500c2b799.png">

<img width="651" alt="스크린샷 2022-09-20 오후 11 23 55" src="https://user-images.githubusercontent.com/85891751/191284151-eaa39205-6de3-4e09-a363-37b6346fdb30.png">

- 1000px 이상 1280px이하
<img width="1107" alt="스크린샷 2022-09-20 오후 11 05 23" src="https://user-images.githubusercontent.com/85891751/191279537-ab2e6af7-6cdb-4cdc-a7f0-df6e2013e902.png">

<img width="1019" alt="스크린샷 2022-09-20 오후 11 24 10" src="https://user-images.githubusercontent.com/85891751/191284065-e83fab5c-f261-41a2-b533-3790e1d1c921.png">

- 1280px 이상
<img width="1791" alt="스크린샷 2022-09-20 오후 10 52 08" src="https://user-images.githubusercontent.com/85891751/191279575-fdff3eac-46c3-42a4-b63c-c442e781a059.png">

<img width="1539" alt="스크린샷 2022-09-20 오후 11 26 45" src="https://user-images.githubusercontent.com/85891751/191284678-a2f7426b-9804-4cac-9f64-32d9071816a8.png">

현재 사이트의 너비가 모니터의 크기에따라 끝까지 늘어나기때문에 매우 큰 모니터를 사용하게 될시 컴포넌트가 굉장히 길어지는 문제가 발생하여`max-width` 를 1500px을 주어서 해결하였습니다.

WritingArticles또한 `max-width` 를 900px로 주어서 너무 길어지는 문제를 방지하였습니다!

<img width="1234" alt="스크린샷 2022-09-20 오후 11 28 37" src="https://user-images.githubusercontent.com/85891751/191285245-5b4ed0e0-3650-4f13-8cd4-e93e71873dd5.png">

<img width="1792" alt="스크린샷 2022-09-20 오후 11 28 46" src="https://user-images.githubusercontent.com/85891751/191285327-f39a97b6-5387-46a2-9aa8-7e4f1dfd3785.png">

네이버 역시 동일하게 max-width를 주어서 일정이상 부터는 양옆의 여백이 생기도록 관리하는것을 보고 참고하였습니다!

## 리뷰 중점사항

- 탭바에 대해서 언제부터 생기게 해야될지 포인트를 정해야될것 같습니다.
- 현재 700, 1000, 1280 이런 숫자로 나누어지는데 자연스러운 기준을 정한것이여서 한번 괜찮은지 봐주셨으면 합니다!
- 700, 1000, 1280을 DESKTOP_SMALL, DESKTOP_MIDDLE, DESKTOP_LARGE라는 상수로 관리하려는데 어떻게 생각하시나요?
- 다른 반응형 더 처리해야될것 있으면 코멘트로 날려주세요.

2022-09-21 05:13 UTC, liswktjs requested changes
700px 1000px  나누는 기준은 좋은 것 같습니다 해당 부분들을 theme내에서 변수로  관리하면 좋을 것 같습니다 

추가적으로 해시태그 검색 결과를 보는 곳에도 반응형 구현 해주세요~~

2022-09-21 05:13 UTC, liswktjs commented on frontend/src/App.tsx
> +	@media (min-width: 700px) {
700px도 Theme의 breakpoint로 가지고 있으면서 관리하는게 좋을 것 같습니다

2022-09-21 05:13 UTC, liswktjs commented on frontend/src/App.tsx
> +	@media (min-width: 1000px) {
해당 1000px도요!

2022-09-21 05:13 UTC, liswktjs commented on frontend/src/pages/CategoryArticles/CategoryArticles.styles.tsx
> +	@media (min-width: 700px) {
theme 변수로 관리해요~

2022-09-21 05:15 UTC, liswktjs commented
TabBar와 관련되서는 모바일 화면 대응이다보니 최소 화면에서만 보여주면 될 것 같아요 700과 1000에서는 nav를 보여주는 것이 좋을 것 같습니다

2022-09-21 08:04 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	@media (min-width: 700px) {
수정했습니다!

2022-09-21 08:04 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	@media (min-width: 1000px) {
수정했습니다!

2022-09-21 08:05 UTC, hwangstar156 commented
- 700px, 1000px theme으로 관리
- 해시태그 검색페이지 반응형 적용
- header, footer에 대해서 반응형 적용

2022-09-22 01:58 UTC, liswktjs approved these changes
작동되는것 확인했습니다 수고하셨습니다

2022-09-22 01:58 UTC, merged