임시저장 페이지를 만든다
woowacourse-teams/2022-gong-seek pull request #591
Opened 2022-09-21 04:17 UTC by liswktjs

Close #563 

 - 임시저장 글 리스트 컴포넌트를 제작한다
  - 임시저장 페이지를 제작한다
-  임시저장 페이지로 이동하는 링크를 만든다
- 임시저장 글을 삭제하는 버튼을 만든다
 - 글을 작성하는 곳에서 임시저장 버튼을 생성한다
-  글을 작성하는 곳에서 2분마다 임시저장이 되도록 기능을 추가한다
- 기존의 WritingAriticles 컴포넌트를 재활용하기 위해서 WritingArticle에 props로 tempArticleId를 넘겨주게 됨 
- WritingArticles가 렌더링 될때에 임시저장된 글이 있다면 (tempArticleId 의 타입이 number) 임시저장글 상세조회를 해와서 해당 글의 내용을 보여줌

2022-09-21 09:32 UTC, hwangstar156 requested changes
리팩토링할 부분들은 나중에 한번에 진행할거기때문에 따로 코멘트 날리지 않았습니다!

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/api/tempArticle.ts
> +}: postTempArticleProps) => {
어짜피 인자로 받은거 다 주는거면 props로 받아서 {...props}로 전달하면 어떨까요?

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/hooks/article/usePostWritingArticles.tsx
> +	const [categoryOption, setCategoryOption] = useState<string>(category ? category : '');
타입스크립트 부분은 나중에 한번 토의해보죠!

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/hooks/tempArticle/useDeleteTempArticle.tsx
> +					);
이건 에러바운더리에서 한번 캐치되는지 확인해보고 이용하는게 좋을것 같네요! 

현재 develop을 pull받은후 현재 만들어진 useThrowCustomError랑 컨벤션을 지키면 괜찮을것 같네요! onSuccess도 한번 얘기해보고 바꿀꺼면 리팩토링 discussion에 올리면 좋을것 같습니다.

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/hooks/tempArticle/useGetTempArticles.tsx
> +	}, [isError]);
이 부분도 pull 받은후 수정한다면 좋을것 같습니다!

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/hooks/tempArticle/usePostTempArticle.tsx
> +			{ title, content, category, tag, isAnonymous, tempArticleId },
이것도 props로 받고 {...props}를 한다면 어떨까 싶군요.. 안에 뭐가있는지는 typescript에게 맡기고 실제는 props로 받아도 될것같아요!

2022-09-21 09:32 UTC, hwangstar156 commented on frontend/src/pages/TemporaryArticles/TemporaryArticleList/TemporaryArticleList.tsx
> +	const nav = useNavigate();
이거는 왜 네이밍이 nav인가요? 이때까지 navigate로 이용하고 있었지 않나요?

2022-09-21 12:09 UTC, liswktjs commented on frontend/src/api/tempArticle.ts
> +}: postTempArticleProps) => {
넘겨주는 요소들이 많아서 그편이 더 좋을 수도 있겠네요!

2022-09-21 13:18 UTC, liswktjs commented on frontend/src/hooks/tempArticle/useDeleteTempArticle.tsx
> +					);
비녀의 useEffect의 사이드 이펙트 위헙성을 듣고 나서 onError도 사용해보고 싶어서 일단 적용해보았습니다 그런데 새롭게 개발된 error boundary와는 호환이 안 되는 것 같네요 
실험해보내 onError에서 던진 에러는 에러바운더리에서 잡지 못하는 것 같아서 기존에 있는 방식대로 구현하였습니다

2022-09-21 13:23 UTC, liswktjs commented on frontend/src/hooks/tempArticle/usePostTempArticle.tsx
> +			{ title, content, category, tag, isAnonymous, tempArticleId },
이부분에서 props로 넘겨주는 경우에 대한 타입이 변수화 되어 있지 않아서 (타입스크립트 리팩토링하면서 어차피 다 고치겠구나 싶더라고요) 추후에 리팩토링할 때 편하도록 다 펼쳐놓기는 하였습니다! 다음 주 에 있을 타입스크립트 리팩토링하면서 진행하면 좋을 것 같습니다

2022-09-21 13:23 UTC, liswktjs commented on frontend/src/pages/TemporaryArticles/TemporaryArticleList/TemporaryArticleList.tsx
> +	const nav = useNavigate();
변경하였습니다!

2022-09-21 14:10 UTC, hwangstar156 requested changes

2022-09-21 14:10 UTC, hwangstar156 commented on frontend/src/hooks/tempArticle/useGetTempDetailArticles.tsx
> +	}, [isError]);
여기도 `useThrowCustomError`로 바꿔야 될것 같네요!

2022-09-22 01:02 UTC, liswktjs commented on frontend/src/hooks/tempArticle/useGetTempDetailArticles.tsx
> +	}, [isError]);
수정했습니다~

2022-09-22 01:48 UTC, hwangstar156 approved these changes
수정된거 확인했습니다~

2022-09-22 01:49 UTC, merged