정렬되지 않은 텍스트들을 정렬한다.
woowacourse-teams/2022-gong-seek pull request #663
Opened 2022-09-28 06:46 UTC by hwangstar156

close #660 

- [x] dropdown 글자를 중앙 정렬을 한다. ( 메인, 검색, 유저 프로필)
-[x] 투표 왼쪽 정렬

## dropdown 데스크탑

<img width="1028" alt="스크린샷 2022-09-28 오후 3 24 10" src="https://user-images.githubusercontent.com/85891751/192707309-7de79acd-ba68-440e-a0fe-6afc2e2ed172.png">

## dropdown 모바일
<img width="405" alt="스크린샷 2022-09-28 오후 3 24 21" src="https://user-images.githubusercontent.com/85891751/192707349-3319f0e2-b20b-49e2-86f3-ea7802c59ced.png">

## 투표 데스크탑
<img width="325" alt="스크린샷 2022-09-28 오후 3 42 26" src="https://user-images.githubusercontent.com/85891751/192707360-f7f27591-a81f-433e-a8df-3cc02bc798f4.png">

## 투표 모바일

<img width="388" alt="스크린샷 2022-09-28 오후 3 46 19" src="https://user-images.githubusercontent.com/85891751/192707523-308dd45e-d604-47ab-add7-cd25fcd86a5e.png">

2022-09-28 07:15 UTC, liswktjs requested changes
좋아요순을 추천순으로 교체하자는 주디의 의견이 있었는데 반영하면 어떨까요?

2022-09-28 07:19 UTC, liswktjs commented
<img width="253" alt="스크린샷 2022-09-28 오후 4 18 34" src="https://user-images.githubusercontent.com/60773373/192713806-481d3b87-19ae-4390-8e02-fd8852c04d26.png">
추가적으로 배경인 게시물에 포커스가 가져있을 때에 dropdown 이 투명해 지는데 이 부분도 같이 수정하면 좋을 것 같습니다

2022-09-30 07:35 UTC, liswktjs requested changes

2022-09-30 07:35 UTC, liswktjs commented on frontend/src/pages/Home/index.styles.tsx
> +	position: relative;
postiion : relative는 없어도 되지 않을까요? position relative로 한 이유가 있을 까요? 
로컬에서는 relative 설정이 없어도 작동이 잘 되네요

2022-10-01 17:00 UTC, hwangstar156 commented on frontend/src/pages/Home/index.styles.tsx
> +	position: relative;
z-index가 활성화되려면 요소의 position이 static이 아니여야 되기때문에 relative를 주었습니다!

2022-10-01 17:00 UTC, hwangstar156 commented on frontend/src/pages/Home/index.styles.tsx
> +	position: relative;
아마 기존 z-index가 이미 더 낮아서 z-index가 작동이 안되더라도 로컬에서 되는것 같네요!

2022-10-03 06:41 UTC, liswktjs commented on frontend/src/pages/Home/index.styles.tsx
> +	position: relative;
relative가 없을 때에 로컬에서 작동이 되는데 있어야 하는 이유가 있을까요???

2022-10-04 01:28 UTC, hwangstar156 commented on frontend/src/pages/Home/index.styles.tsx
> +	position: relative;
z-index로 두개의 계층을 나누는데 한곳에는 z-index를 주고 한곳에는 주지 않으면 나중에 이 부분을 다시 작업할 일이 있으면 헷갈릴수도 있을것 같네요.

2022-10-05 01:19 UTC, liswktjs approved these changes

2022-10-05 01:21 UTC, merged