데스크탑 화면에서 MenuSlider가 안보이도록 한다.
woowacourse-teams/2022-gong-seek pull request #665
Opened 2022-09-28 07:02 UTC by hwangstar156

close #664 

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/85891751/192710429-61dbb5dd-720b-40a9-97bb-26a9f596d054.gif)

media query에서 모바일이 아닐시 `display: none`으로 설정하였습니다.

2022-09-28 07:23 UTC, liswktjs requested changes
<img width="519" alt="스크린샷 2022-09-28 오후 4 21 07" src="https://user-images.githubusercontent.com/60773373/192714353-0ae140ab-c58e-4b44-bcee-362f087765f5.png">
해당 이슈에서 menuSlider 뒤 쪽에서 스크롤이 내려가는 이슈도 같이 해결하면 좋을 것 같습니다 
<img width="935" alt="스크린샷 2022-09-28 오후 4 22 46" src="https://user-images.githubusercontent.com/60773373/192714719-370186bb-e233-4bae-a74f-416017e274aa.png">
발리스타 블로그에 올라온 글을 참고하면 좋을 것 같네요

2022-09-29 00:53 UTC, hwangstar156 commented
올려주신 방법으로 했는데 원하는대로 작동을 하지 않네요;

찾아보니 modal이 mount됬을때 overflow를 hidden으로, unmount됬을때 overflow를 auto로 바꿔주는 방식으로 구현하였습니다.
<img width="1384" alt="스크린샷 2022-09-29 오전 9 53 09" src="https://user-images.githubusercontent.com/85891751/192914166-7976bc94-fd49-4c1b-9863-7af177d105a2.png">

브라우저 지원은 문재 없을것 같네요!

2022-09-30 07:41 UTC, liswktjs requested changes
dimmer가 제대로 보여지지 않는 이슈가 있네요 한 번 더 확인 부탁드립니다

2022-10-02 08:31 UTC, hwangstar156 commented
dimmed의 position이 absolute로 되있어서 생긴 문제였네요! fixed로 수정하였습니다!

2022-10-03 06:44 UTC, liswktjs approved these changes
작동 확인했습니다~ 
position이 absolute로 되어 있어서 고정이 되어 있었나 보군요

2022-10-03 06:46 UTC, merged