임시저장 게시글 제목이 길면 삭제버튼이 보이지 않는 에러를 수정한다
woowacourse-teams/2022-gong-seek pull request #666
Opened 2022-09-28 07:06 UTC by liswktjs

Close #635 

- 임시저장글 리스트에 카테고리 정보 추가 
- width값을 조정하여 임시저장글 제목이 길어지더라도 삭제버튼이 보이도록 조치

2022-09-29 02:10 UTC, hwangstar156 requested changes

2022-09-29 02:10 UTC, hwangstar156 commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +	article: { title: string; createAt: string; category: string };
잡았다.. createAt!

2022-09-29 02:10 UTC, hwangstar156 commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +				{article.category === 'question' ? '질문' : '토론'}
옛날에 이부분 `한글 카테고리`라는 변수로 했던것 같은데 동일하게 통일하는건 어떨까요?

2022-09-30 08:37 UTC, liswktjs commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +	article: { title: string; createAt: string; category: string };
서버에서 createAt으로 오고 있어서 여기서 creatAt으로 하게되었습니다
서버에서 이름을 교체한 후 에 createdAt 으로 수정해야될 것 같습니다

2022-09-30 08:37 UTC, liswktjs commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +				{article.category === 'question' ? '질문' : '토론'}
이 부분을 util로 바꿔도 좋을 것 같네요

2022-09-30 08:49 UTC, liswktjs commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +				{article.category === 'question' ? '질문' : '토론'}
이 부분이 변수로 선언하면, 바로 반환하는 구조가 바뀌여서 이대로 가져가는게 낫지 않을까요?

2022-10-03 05:38 UTC, liswktjs commented on frontend/src/pages/TemporaryArticles/TemporaryArticleItem/TemporaryArticleItem.tsx
> +				{article.category === 'question' ? '질문' : '토론'}
코드를 살펴보니 한글 카테고리로 이름이 많이 사용되고 있어서 converter 함수를 만들어 리팩토링 진행했습니다

2022-10-04 01:26 UTC, hwangstar156 approved these changes

2022-10-04 03:01 UTC, merged