마이페이지의 UI를 수정한다
woowacourse-teams/2022-gong-seek pull request #679
Opened 2022-09-29 08:37 UTC by liswktjs

Close #668 

- 마이페이지 내에서 카테고리 선택해야 컴포넌트가 렌더링 되도록 변경 
- 임시저장글 보여주는 페이지 삭제 
- 유저의 정보가 불러오는 것을 성공해야 유저가 작성한 댓글과 글을 보이도록 한다 
<img width="758" alt="스크린샷 2022-09-29 오후 5 36 32" src="https://user-images.githubusercontent.com/60773373/192982846-a268ee81-b746-4bad-bcfa-b61aaef190ef.png">

2022-09-29 12:17 UTC, hwangstar156 requested changes
확인했습니다! 코드적으로는 크게 피드백 드릴게 없네요! UI에 대한 제안 및 수정사항만 봐주세요!

## 제안 및 수정사항

### 반응형 이슈

- 1280px 이하
<img width="1035" alt="스크린샷 2022-09-29 오후 9 02 51" src="https://user-images.githubusercontent.com/85891751/193028195-03785109-d38a-4df5-9e68-d02119b4cb7b.png">

- 1280px 이상
<img width="1214" alt="스크린샷 2022-09-29 오후 8 59 26" src="https://user-images.githubusercontent.com/85891751/193028212-d700ebe3-92f1-4df4-83dc-b0889086d86a.png">

현재 1280px를 기준으로 ui가 깨지고 있습니다. 확인부탁드립니다!

## 버튼 hover color
<img width="434" alt="스크린샷 2022-09-29 오후 8 59 39" src="https://user-images.githubusercontent.com/85891751/193028487-9d63009a-be3b-4a77-a3d4-fc1817e5eac0.png">

현재 상태는 하나는 selected고 하나는 hover를 한 상태입니다. 2개 색깔이 같으니까 혼동이 오는것 같습니다. 색깔의 구분이 필요할것 같습니다!

## 버튼 크기
<img width="434" alt="스크린샷 2022-09-29 오후 8 59 39" src="https://user-images.githubusercontent.com/85891751/193028487-9d63009a-be3b-4a77-a3d4-fc1817e5eac0.png">
현재 버튼이 위 아래가 좁아 보입니다. 약간의 패딩을 줘서 키우는 것도 괜찮을것 같습니다!

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserArticleBox/UserArticleBox.tsx
> +	return (
사소하지만 한칸씩만 띄워주세요!

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserCommentBox/UserCommentBox.tsx
> +	}
현재 isCommentsIdle을 한다고 별로 의미가 없을것 같습니다. 원래라면 isLoading, isIdle을 같이 이용할시 자동으로 data는 undefined가 아니라는 타입가드때문에 이용했었는데 커스텀 훅으로 뺀 현재는 작동하지 않을것 같네요!

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserCommentItem/UserCommentItem.tsx
> +	return (
return과 한칸씩 띄워주세요!

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	const isValidInput: boolean = validatedEditInput(editedName);
확인해보니 저절로 `boolean`타입으로 추론하는데 이렇게 명시한 이유가 있나요?

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/index.tsx
> +);
컴포넌트 단에서는 React.lazy가 따로 필요하지않을것 같습니다. 이미 MyPage가 lazy loading되어서 완료된 번들을 불러오는데 들어가서 다시 컴포넌트들을 React.lazy하면 로딩이 2번 보이게 될것 같네요.

2022-09-29 12:17 UTC, hwangstar156 commented on frontend/src/pages/MyPage/index.tsx
> +	if (isInfoLoading || isInfoIdle) {
역시 Idle 부분 제거해도 될것 같습니다.

2022-10-03 06:18 UTC, liswktjs commented on frontend/src/pages/MyPage/UserCommentBox/UserCommentBox.tsx
> +	}
타입 가드의 용도도 있겠지만, 서버에서 부터 정보를 받아오는 동안의 로딩 시간 동안 보여줄 UI를 표시하는 용도로도 쓰이고 있어서 그대로 사용하였습니다

2022-10-03 06:19 UTC, liswktjs commented on frontend/src/pages/MyPage/UserCommentBox/UserCommentBox.tsx
> +	}
idle인 경우만 제거하면 되겠네요

2022-10-03 06:21 UTC, liswktjs commented on frontend/src/pages/MyPage/UserCommentItem/UserCommentItem.tsx
> +	return (
전 UserCommentBox에서 수정된 PR에서 반영되었습니다

2022-10-03 06:23 UTC, liswktjs commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	const isValidInput: boolean = validatedEditInput(editedName);
alidatedEditInput의 반환값으로 값이 들어가고 있어서 타입을 명시적으로 넣어주면 어떤 값이 들어올지 다른 사람들이 기대할 수 있게 할 수 있게 정보를 더 제공하는 역할로  넣어주게 되었습니다

2022-10-03 06:26 UTC, liswktjs commented on frontend/src/pages/MyPage/index.tsx
> +);
Article Box의 경우에는 Default로 마이페이제에 들어왔을 때에 보여지지만 
CommentBox와 TemporaryArticleList의 경우 카테고리를 선택해야만 비동기 통신이 이루어지게 되어서 나중에 불러오기 때문에 레이지 로딩을 하게 되었습니다 이런 경우에도 필요 없을까요?

2022-10-03 06:32 UTC, liswktjs commented
마우스가 hover되었을 때에 selected가 된 곳과 같은 색깔이 나와야 '선택될'이라고 기대된다고 생각이 들어서 hover의 경우에는 색깔을 변경하지 않았습니다

2022-10-04 01:31 UTC, hwangstar156 commented on frontend/src/pages/MyPage/UserProfile/UserProfile.tsx
> +	const isValidInput: boolean = validatedEditInput(editedName);
타입추론이 가능한데 굳이 작성할 필요는 없을 것 같습니다. 충분히 validated 라는 네이밍과 is라는 prefix로도 충분할것 같습니다.

2022-10-04 01:34 UTC, hwangstar156 commented on frontend/src/pages/MyPage/index.tsx
> +);
CommentBox, TemporaryArticleList는 페이지 같은 느낌이라 React.lazy를 작성하면 되겠네요. ArticleBox의 React.lazy만 제거하면 될것 같습니다.

2022-10-05 01:14 UTC, hwangstar156 approved these changes

2022-10-05 01:14 UTC, merged