모바일에서 글 작성시 포커스를 수정한다.
woowacourse-teams/2022-gong-seek pull request #680
Opened 2022-09-29 11:40 UTC by hwangstar156

close #670 

## 문제 현상

현재 모바일 글 작성페이지에서 스크롤을 아래로 내리고 글을 쓰면 현재 작성중인 글이 보이지 않는다.

## 문제 원인

현재 포커싱은 멀쩡히 작동하지만 헤더가 fixed로 덮어버리기 때문에 가려져서 보이지 않는다.

## 문제 해결 방법

스크롤을 아래로 내릴시에는 컨텐츠를 보려고 하는것이기 때문에 헤더를 가리고 스크롤을 위로 할떄는 다시 홈이나 다른 항목을 이용하고 싶은것이기 때문에 헤더를 다시 보여주는 식으로 구현하였습니다.

## useInterval

useEffect내에서 setInterval을 사용하면 정상적으로 작동되지 않는다고 합니다. 그래서 Dan Abramov가 react와 setInterval자체가 맞지 않는다고 하여 useInterval이라는 훅을 만들어서 이용할것을 권장하였습니다.

[useInterval 참고자료](https://overreacted.io/making-setinterval-declarative-with-react-hooks/)

## 구현 모습
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/85891751/193021600-ba573d6c-d4e0-446c-8ff5-b6aee1f4460e.gif)

2022-09-30 08:20 UTC, liswktjs requested changes
코드 관련해서 몇가지 코멘트를 남겼습니다 
추가적으로 몇몇 페이지에서는 Header가 제대로 접히지 않고 있어요 확인 해주세요
<img width="383" alt="스크린샷 2022-09-30 오후 4 53 10" src="https://user-images.githubusercontent.com/60773373/193225424-c1b3a70c-c272-4e30-a319-b22757c620f2.png">

<img width="371" alt="스크린샷 2022-09-30 오후 4 52 08" src="https://user-images.githubusercontent.com/60773373/193225455-c90544a3-89b8-4d06-9cd4-195fdabd41a5.png">

<img width="399" alt="스크린샷 2022-09-30 오후 4 51 36" src="https://user-images.githubusercontent.com/60773373/193225473-3bb6757f-5bec-45b5-ba1c-28398c3332df.png">


<img width="376" alt="스크린샷 2022-09-30 오후 4 51 01" src="https://user-images.githubusercontent.com/60773373/193225492-c7e7c1e8-4cda-493d-ac87-772c0ae2a98b.png">

2022-09-30 08:20 UTC, liswktjs commented on frontend/src/hooks/common/useScroll.tsx
> +const useScroll = (callback: (...args: unknown[]) => void) => {
handleHeaderViewByScroll에 넘겨지는 인자가 없는데  unknown[ ] 으로 타입 지정을 한 이유가 있나요?

2022-09-30 08:20 UTC, liswktjs commented on frontend/src/App.tsx
> +	const handleHeaderViewByScroll = () => {
이곳에 handleHeaderViewByScroll을 선언해서 App 파일이 너무 복잡해지고 방대해진 것 같은데 util로 분리하는게 어떨까요?

2022-09-30 08:20 UTC, liswktjs commented on frontend/src/App.tsx
> +	const headerElement = useRef<HTMLDivElement>(null);
Header에서 해당 값들을 관리해도 상관없을 것 같아요!

2022-09-30 08:20 UTC, liswktjs commented on frontend/src/App.tsx
> +	const handleHeaderViewByScroll = () => {
추가적으로 headerElement를 인자로 넘기면 둘이 같은 파일 내에 있을 필요가 없어지지 않을까요?

2022-10-02 08:07 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	const minDelatScroll = useRef(10);
사실 상수 선언과 같은데 component내에서 상수 선언은 useRef로 해서 진행을 해서 useRef로 선언했습니다.

`lastScrollTop`은 처음에 스크롤이 안되어있기에 0으로 설정을 하였고, `minDeltaScroll`은 최소 스크롤 이동 범위입니다. 10px 이상 움직이면 그때부터 함수가 동작하도록 하였습니다!

2022-10-02 08:08 UTC, hwangstar156 commented on frontend/src/hooks/common/useInterval.tsx
> +		if (delay !== null) {
!로 설정할시 0, undefined등에도 걸러져서 예상치 못한 동작을 할 수도 있을것같습니다. null이나 undefined를 거를때는 좀더 확실하게 거르는게 좋다고 생각됩니다.

2022-10-02 08:10 UTC, hwangstar156 commented on frontend/src/hooks/common/useScroll.tsx
> +const useScroll = (callback: (...args: unknown[]) => void) => {
useScroll은 범용적으로 사용되는 훅이여서 callback으로 인자가 들어있는 함수가 들어올 수도 있기에 unknown[]으로 설정하였습니다.

2022-10-02 08:10 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	const handleHeaderViewByScroll = () => {
확실히 로직이 길어져서 분리의 필요성이 있는것 같습니다. `util`이라고 하기에는 App에서 사용되는 주요기능이기에 hook으로 따로 분리하여 관리를 하였습니다.

2022-10-02 08:18 UTC, hwangstar156 commented on frontend/src/App.tsx
> +	const headerElement = useRef<HTMLDivElement>(null);
굳이 App에서 관리할 필요가 없었네요. 헤더로 모든 로직들 이동하였습니다!

2022-10-03 06:48 UTC, liswktjs commented on frontend/src/hooks/common/useInterval.tsx
> +		if (delay !== null) {
기존에 사용하던 typeof를 사용하지 않고 null 확인을 한 이유가 있나요?

2022-10-03 06:51 UTC, liswktjs commented on frontend/src/hooks/common/useScroll.tsx
> +const useScroll = (callback: (...args: unknown[]) => void) => {
오 그렇다면 unknown[]로 한 것도 이유가 있을까요? 범용적이라면, [] 인것도 모를 수 있지 않을까요?

2022-10-03 06:55 UTC, liswktjs requested changes

2022-10-03 06:55 UTC, liswktjs commented on frontend/src/hooks/common/useHeaderViewByScroll.tsx
> +const useHeaderViewByScroll = () => {
네이밍이 애매한데 혹시 다른 이름 없을까요? ㅋㅋㅋㅋㅋㅋ

2022-10-04 01:36 UTC, hwangstar156 commented on frontend/src/hooks/common/useInterval.tsx
> +		if (delay !== null) {
typeof null을 할 경우 object가 나오기 때문에 null체크는 이런식으로 밖에 할수없습니다!

2022-10-04 01:36 UTC, hwangstar156 commented on frontend/src/hooks/common/useScroll.tsx
> +const useScroll = (callback: (...args: unknown[]) => void) => {
...args로 작성할시 무조건 배열형태로 인자들이 들어오게 됩니다.

2022-10-06 05:05 UTC, hwangstar156 commented on frontend/src/hooks/common/useHeaderViewByScroll.tsx
> +const useHeaderViewByScroll = () => {
useActiveHeaderByScroll로 변경하였습니다!

2022-10-06 07:12 UTC, liswktjs requested changes

2022-10-06 07:12 UTC, liswktjs commented on frontend/src/components/layout/Header/Header.tsx
> +import useActiveHeaderByScroll from '@/hooks/common/useActiveHeaderByScroll';
useHandleHeaderByScroll은 어떤가요? Active는 뭔가 껐다 켰다? 라는 느낌이 들어서 보였다가 안 보였다가라는 것에 의미가 맞는지 확신이 안 서네요

2022-10-07 02:32 UTC, liswktjs approved these changes

2022-10-07 02:33 UTC, merged