N+1 문제 해결
woowacourse-teams/2022-gong-seek pull request #693
Opened 2022-10-03 14:28 UTC by jurlring

## N+1 문제 해결 사항
- [x]  getOne(게시글 단건 조회)
- [x]  getAll(게시글 전체 조회)
- [x]  getLikes
- [x]  searhByText(제목이나 내용으로 검색)
- [x]  searchByAuthor(작성자 이름으로 검색)
- [ ]  searchByTag(태그 이름으로 검색)

## N+1 문제 해결해야하는 이유
부하테스트를 통해 병목현상이 DB에서 일어난다는 것을 알게 되었고, 서비스 특성상 Article과 많은 테이블이 엮여있습니다.
그래서 Article을 조회할 때 너무 많은 쿼리가 나가는 것을 원인으로 보고 해결하고자합니다.
또한 서비스에 N을 위한 메서드들이 없어져서 가독성이 좋아질 것으로 생각됩니다.

하지만 서비스의 로직이 그대로 repository로 옮겨가게 되고, View에 의존적인 Domain이 되어버린다고 생각합니다.

그래서 저번에 3기 웨지의 말을 듣고 꼭 모든 API에서 N+1를 해결해야할까? 라는 생각이 들었어요!
이 부분은 화요일에 다 같이 얘기하고 일단 N+1쿼리가 나가는 API를 다 해결해보려고 했는데 태그이름으로 검색할 때는 테이블이 복잡하게 연결되어 있어서 해결이 안되네용

그래서 일단 확인하시라구 PR날립니다~

2022-10-07 08:47 UTC, Gyuchool requested changes
오우 정말 수고가 많으셨군요! 
리뷰 남겼으니 확인해주세요~!

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .exists();
```suggestion
       return queryFactory.selectOne()
                .from(vote)
                .where(vote.article.id.eq(articleId))
                .exists();
```
위 방식과 뭐가 다른건가요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .where(
한 줄로 적어도 될거같네요 ㅎㅎ

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        if (Objects.isNull(articleId) || memberId.equals(0L)) {
0L과 비교한 이유는 뭘까요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        return tagCount != null;
```suggestion
       return queryFactory.selectOne()
                .from(articleTag)
                .where(articleTag.tag.id.eq(tagId))
                .fetchFirst() != null;
```
이렇게는 어떤가요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .transform(groupBy(article.id).as(GroupBy.list(tag.name)));
해당 쿼리는 article.id기준으로해서 tag.name list를 반환하는 쿼리라고 보면 될까요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +    private JPAQuery<ArticlePreviewDto> getAllArticlePreviewDto(Long articleId, Long memberId) {
지금도 좋지만 selectXX 네이밍이 더 직관적이라고 생각하는데 어떤가요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    @Accessors(fluent = true)
해당 어노테이션은 어떤 역할인가요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    private Boolean isLike;
요거만 참조타입인 이유가 있나요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticlePreviewDto.java
> +    public ArticlePreviewDto(Long id,
사용하지 않는 생성자 같습니다!

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/MyPageArticleDto.java
> +@NoArgsConstructor
해당 어노테이션이 필요한가요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/MyPageArticleDto.java
> +    public String toString() {
여기에만 toString이 존재하네요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/MyPageArticleDto.java
> +    private long commentCount;
여기만 원시타입인 이유가 있나요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/ArticleController.java
> +    public ResponseEntity<ArticleDto> getOne(@AuthenticationPrinciple AppMember appMember, @PathVariable Long id) {
네이밍을 Dto로 바꾼 이유가 있을까요?

2022-10-07 08:47 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/dto/ArticlePageResponseNew.java
> +public class ArticlePageResponseNew {
사용하지 않는 클래스네요!

2022-10-07 10:33 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .exists();
JPAExpressions는 서브쿼리를 사용할 때 이용합니다. 서브쿼리이기 때문에  fetch와 tranform과 같은 메서드들은 사용할 수 없습니다.
queryFactory는 일반적인 쿼리를 만들 때 사용합니다.

2022-10-07 10:36 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        if (Objects.isNull(articleId) || memberId.equals(0L)) {
비회원이 조회를 요청했을 때, 서비스에서 파라미터로 넘겨주는 memberId가 AppMember에서 나오는 Id이기 때문입니다. 좋은 방법이 있을까요?

2022-10-07 10:37 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .transform(groupBy(article.id).as(GroupBy.list(tag.name)));
네 맞습니다. Map<Long, List<String>> Long이 article.id List<String>이 tag.name.list 입니당~

2022-10-07 10:39 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +    private JPAQuery<ArticlePreviewDto> getAllArticlePreviewDto(Long articleId, Long memberId) {
get보단 select가 문맥에 맞네요 ! 감사합니다~

2022-10-07 10:41 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/presentation/ArticleController.java
> +    public ResponseEntity<ArticleDto> getOne(@AuthenticationPrinciple AppMember appMember, @PathVariable Long id) {
Response는 Service에서 반환하는 Dto이고 ~Dto는 Repository에서 반환하는 것의 차이를 두기 위해서 입니다~

2022-10-07 10:46 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/MyPageArticleDto.java
> +    public String toString() {
디버깅 하다가 지우지 못했네요. 삭제했습니다.

2022-10-07 10:52 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        Map<Long, List<String>> tags = articleRepository.findTags(foundArticleIds);
일대다는 fetch 조인으로 페이징이 불가능해서  하나의 쿼리로 불가능하더라구요. 좋은 방법이 있을까요?

2022-10-07 11:27 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        List<Long> deletedTagIds = new ArrayList<>(existingTagIds);
참조를 끊으려던게 아니라, 가독성을 높이기위한 의도였는데 불필요한 부분을 제거했습니다~

2022-10-07 11:45 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepository.java
> +    @Modifying
이런 옵션이 있었군요! 추가했습니다~

2022-10-07 12:00 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticlePreviewDto.java
> +    public ArticlePreviewDto(Long id,
queryDsl에서 사용되고 있어요!

2022-10-07 12:08 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/MyPageArticleDto.java
> +    private long commentCount;
Wrapper 타입으로 통일했습니다~

2022-10-07 12:15 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    @Accessors(fluent = true)
@Accessors(fluent = true) 해당 어노테이션은 getter와 setter에 대한 prefix를 붙이지 않고 하는 방식입니다~

2022-10-09 06:56 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .exists();
옹 서브쿼리 안에서 사용할 땐 JPAExpressions를 사용해야한단 말이군요?!

2022-10-09 07:05 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .exists();
그런데 해당 쿼리는 어느 부분에서 서브쿼리로 이용할까요? 서브쿼리가 안보이는 것 같아서욤

2022-10-09 07:09 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        if (Objects.isNull(articleId) || memberId.equals(0L)) {
아하 비회원일 때의 경우군요. 이해했습니다~

2022-10-09 07:19 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticlePreviewDto.java
> +    public ArticlePreviewDto(Long id,
![image](https://user-images.githubusercontent.com/60054318/194743187-3f3a3f60-90a6-45a2-a51f-7ce9a5cb2267.png)
사용되고 있네요.. 근데 제 IDE에선 왜 저렇게..삭제할뻔..

2022-10-09 07:23 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        Map<Long, List<String>> tags = articleRepository.findTags(foundArticleIds);
자동으로 반환되는 형태였군요~ 그럼 메서드들만 묶어줘도 좋을 것 같네욤

2022-10-09 07:24 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +        Map<Long, List<String>> tags = articleRepository.findTags(foundArticleIds);
이해했습니다~ 우선 이 상태로 가야할것 같네욤

2022-10-09 07:44 UTC, Gyuchool approved these changes
수정하신거 확인했습니다~ 반영하시느라 고생하셨어요!
마지막 커멘트만 반영해주시면 저는 머지해도 될것 같습니당~!

2022-10-09 07:44 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/application/ArticleService.java
> +//        List<Long> deletedTagIds = new ArrayList<>(existingTagIds);
주석이 있네요~

2022-10-09 07:44 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    private static final String ANONYMOUS_NAME = "익명";
ArticleDto가 익명의 상태를 가지고있는 것보단 AuthorDto가 가지고 있도록 하는게 더 적합해보이는데 어떠신가요?

2022-10-10 08:18 UTC, hanull approved these changes
수고하셨어요!
코멘트 몇개 남겨봤는데 확인 부탁드려요!

2022-10-10 08:18 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        List<ArticlePreviewDto> fetch = sort(sortType, query);
정렬을 application 단이 아니라, repo 쪽에서 하신 이유가 있을까요?

2022-10-11 05:34 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticlePreviewDto.java
> +    public ArticlePreviewDto(Long id,
제 IDE에서도 나오진 않더군요.. QueryDSL 이슈인듯?

2022-10-11 06:04 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticlePreviewDto.java
> +                category.getValue().toLowerCase(),
구웃

2022-10-11 06:07 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +        List<ArticlePreviewDto> fetch = sort(sortType, query);
동적 쿼리(sortType이 views일 때는 view 기준 정렬, latest일 때는 최신 기준 정렬)를 작성해야하기 때문에 QueryDsl 안에서 처리하였습니다 ~

2022-10-11 06:52 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    private Boolean isLike;
is prefix때문입니다!

2022-10-11 06:53 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepositoryImpl.java
> +                .exists();
서브 쿼리를 실행할 경우 최종 연산을 할 수 없어서 limit을 쓸 수 없어요!
일단 저희가 생각하기엔 최선이였는데, 방법이 있는지 찾아볼게요!

2022-10-11 07:48 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/ArticleRepository.java
> +    @Modifying(clearAutomatically = true)
벌크연산을 위해서 사용한 것은 아니고, 조회 시 DTO를 반환하고 있기 때문에 더티 체킹을 할 수가 없어서 해당 어노테이션을 활용하여 update문을 날려주었습니다.

2022-10-11 08:11 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/article/domain/repository/dto/ArticleDto.java
> +    private AuthorDto author;
API 명세 상에서 한번 감싸서 반환을 해줘야하기 때문에 위와 같이 코드를 작성했어요. 프론트와 상의 후에 수정하도록 하겠습니다~

2022-10-12 04:01 UTC, merged