웹팩 빌드속도를 향상 시킨다.
woowacourse-teams/2022-gong-seek pull request #705
Opened 2022-10-05 18:21 UTC by hwangstar156

close #704 

## 문제 상황

현재 개발환경에서의 첫 빌드 17초, 리빌드 7.5초가 걸려 개발에 불편함을 주고 있다. (+ 배포 환경에서는 13초가 소비됨)

## 문제 해결 방안

다음과 같은 webpack 설정을 하여 해결하였다.

### 개발 환경
- runtimeChunks 분리
- source-map 변경
- babel-loader 캐싱
- 불필요한 플러그인 및 로더 제거
### 배포 환경
- cache 설정

## 개선 결과

### 개선 전 (개발 - yarn start)

>first-build (첫 yarn start)
<img width="777" alt="Untitled" src="https://user-images.githubusercontent.com/85891751/194131854-144b1035-477f-4f13-945f-02c1d8537184.png">

>rebuild (auto save)
<img width="806" alt="Untitled-1" src="https://user-images.githubusercontent.com/85891751/194132111-cde2c3a4-6353-4c72-b429-ae97fa34391d.png">

### source-map: eval-cheap-module-source-map으로 변경

>first-build 
<img width="797" alt="Untitled-2" src="https://user-images.githubusercontent.com/85891751/194132308-3ee873c4-492a-4ece-aff6-c77df38b3cc7.png">

>rebuild
<img width="666" alt="Untitled-3" src="https://user-images.githubusercontent.com/85891751/194132388-30a7285a-1d89-44eb-9231-b425371d27d5.png">

### runtimeChunks: true

>first-build
<img width="795" alt="Untitled-5" src="https://user-images.githubusercontent.com/85891751/194132629-c7a821ae-1e81-468a-b4ed-342aae9f6bb0.png">

>rebuild
<img width="939" alt="Untitled-6" src="https://user-images.githubusercontent.com/85891751/194132673-83505b67-a11c-41da-8847-d5745ab70d2c.png">

### babel-loader 캐싱

>first-build
<img width="1202" alt="Untitled-7" src="https://user-images.githubusercontent.com/85891751/194132869-85d911e3-f0c9-4773-99da-f0d59492e0c9.png">

>rebuild

<img width="1064" alt="Untitled-8" src="https://user-images.githubusercontent.com/85891751/194132934-3c4a50b7-9b48-4a4b-b91b-ccf14c61ea7e.png">

### 개선전(배포 - yarn build)
<img width="1270" alt="Untitled-10" src="https://user-images.githubusercontent.com/85891751/194133125-6257d2b6-40a4-42df-8119-ab79280ede74.png">

### cache: filesystem

<img width="1237" alt="Untitled-11" src="https://user-images.githubusercontent.com/85891751/194133240-0ebf79a0-11eb-4b6b-b0ac-0d83b805607f.png">

## 이슈

esbuild-loader를 이용하여 빌드 속도를 더 개선하려했으나 트리쉐이킹이 되지않는 문제로 babel-loader로 그대로 진행하였습니다.

2022-10-06 01:55 UTC, liswktjs requested changes
기본설정을 바꾸는 거라 이유가 중요해서 코멘트들을 남겼습니다 확인하고 답글 달아주세요~

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +		pathinfo: false,
production 모드에서는 자동으로 false가 되고 development에서는 true가 된다고 하는데 false를 명시적으로 표기한 이유가 있나요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +		symlinks: false,
해당 옵션을 추가한 이유는 무엇인가요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.prod.js
> +	},
cache type을 filesystem으로 한 이유가 무엇인가요? 현재 nginx에서 gzip으로 바꿔서 보내주고 있는데 의미있는 적용인가요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +					cacheCompression: false,
cacheComporession옵션은  develop 모드일 때 false인데 공통 웹팩에 지정한 이유가 있나요?  이렇게 되면 development에서는 의미없는 옵션이 되지 않을까요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +					cacheDirectory: true,
cache Directory의 기본값이 string으로 되어있는데 해당 옵션은 어떤 설정인가요? 
https://webpack.kr/configuration/cache#cachecachedirectory

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> -		minimize: true,
해당 옵션 제거한 이유가 뭔가요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +		runtimeChunk: true,
이 옵션은 어떤 역할을 하나요?

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.dev.js
> +	devtool: 'eval-cheap-module-source-map',
eval-cheap-module-source-map이 빌드가 느리고 rebuild가 빠르다고 되어 있는데 development환경에서 만 속도을 올리고 싶다면 아예 devtool 옵션을 none으로 하면 어떨까요? none일 때 build와 rebuild속도가 가장 빠르다고 하네요

2022-10-06 01:55 UTC, liswktjs commented on frontend/webpack/webpack.prod.js
> -	},
해당 옵션을 제거한 이유가 있을까요?

2022-10-06 04:01 UTC, hwangstar156 commented on frontend/webpack/webpack.common.js
> +		pathinfo: false,
development에서의 빌드속도 개선을 위해서 false를 주었습니다.

2022-10-06 04:02 UTC, hwangstar156 commented on frontend/webpack/webpack.common.js
> +		symlinks: false,
webpack 공식문서에서 yarn link같은명령어를 쓰지 않는다면 `symlinks`를 false로 하는것이 좋다고 합니다!

2022-10-06 04:03 UTC, hwangstar156 commented on frontend/webpack/webpack.prod.js
> +	},
development모드에서는 기본으로 cache가 되어있지만 production에서는 filesystem이라고 명시를 해줘야지 캐싱을 진행합니다.

2022-10-06 04:12 UTC, hwangstar156 commented on frontend/webpack/webpack.common.js
> +					cacheCompression: false,
이건 production으로만 이동하겠습니다!

2022-10-06 04:17 UTC, hwangstar156 commented on frontend/webpack/webpack.common.js
> +					cacheDirectory: true,
webpack cache의 cacheDirectory랑은 다르게 동작하는것으로 알고 있습니다! babel-loader의 옵션으로 true를 줄시 babel-loader에서 실행하는 과정을 캐싱하는것으로 알고있습니다!

2022-10-06 05:09 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +		pathinfo: false,
해당 옵션을 주면 왜 빌드속도개 개선되죠?

2022-10-06 05:10 UTC, liswktjs commented on frontend/webpack/webpack.common.js
> +		symlinks: false,
어떤면에서 좋아지는 거죠?

2022-10-06 05:35 UTC, hwangstar156 commented
개발환경에서 ts-loader로 변경

## 변경전
babel-loader의 캐싱까지 적용했을떄 5300ms가 나왔습니다.(위의 pr 참조)

## 변경후
<img width="1212" alt="스크린샷 2022-10-06 오후 2 29 29" src="https://user-images.githubusercontent.com/85891751/194222320-408cafe9-fcb0-423d-b0ad-b5374fa60fde.png">

ts-loader에서 transpileOnly:true를 주고 ForktsCheckerWebpackPlugin과 함께 이용하여 ts-loader는 트랜스파일링만 하고 ForktsCheckerWebpackPlugin가 타입체크를 진행하여 babel-loader랑 비슷한 시간이 나오게 되었습니다.

2022-10-07 07:51 UTC, liswktjs requested changes

2022-10-07 07:51 UTC, liswktjs commented on frontend/webpack/webpack.dev.js
> +		new ForkTsCheckerWebpackPlugin(),
해당 플러그인은 어떤 역할을 하나요?

2022-10-07 07:56 UTC, liswktjs requested changes
lighthouse 성능 측정 결과도 올려주세요 현재 제 로컬에서 돌려봤을 때에 production 모드임에도 성능점수가 60점대가 나오네요 추가적인 확인이 필요할 것 같습니다

2022-10-07 07:56 UTC, liswktjs commented on frontend/package.json
> +		"build": "webpack --mode=production --config webpack/webpack.prod.js",
현재 prod일 때에 map 파일을 생성하고 있지 않나요?

2022-10-07 08:01 UTC, liswktjs commented
추가적으로 폴더구조 pr merge되면 , 현재 에러로 표시되는 곳들 반영해서 커밋에 포함해도 좋을 것 같네요

2022-10-07 09:33 UTC, hwangstar156 commented on frontend/package.json
> +		"build": "webpack --mode=production --config webpack/webpack.prod.js",
prod일때 devtool:false이기때문에 생성하지않습니다.

2022-10-07 09:35 UTC, hwangstar156 commented on frontend/webpack/webpack.dev.js
> +		new ForkTsCheckerWebpackPlugin(),
forktscheckerwebpackplugin은 플러그인에서 타입검사를 진행해주게 됩니다.

ts-loader에서 transpileOnly:true를 주면 타입검사를 하지않고 트랜스파일링만 진행합니다. 

ts-loader가 할일을 loader와 plugin으로 분리하면서 좀 더 빠르게 빌드가 되게 됩니다.

2022-10-07 18:10 UTC, hwangstar156 commented
확인해보니 소스맵을 바꾸지 않고 실행시킨게 아닌가 싶네요. development에서 sourcemap이 eval-cheap-module-source-map이 되어있어서 그런것 같습니다. 

<img width="1429" alt="스크린샷 2022-10-08 오전 2 59 39" src="https://user-images.githubusercontent.com/85891751/194622471-6ba6e3e3-23f3-4022-a1f9-639af43219cd.png">

문제없이 100점이 나옵니다!

2022-10-10 09:26 UTC, liswktjs commented
해당 pr에서 타입 에러 나는 것을 다 수정하고 가야할 것 같습니다! 
안 그러면 develop 모드에서 에러가 표기되고 있을 것 같네요

2022-10-12 05:47 UTC, liswktjs approved these changes
수고하셨습니다~

2022-10-12 05:51 UTC, merged