공통 모달을 개발한다.
woowacourse-teams/2022-gong-seek pull request #724
Opened 2022-10-08 08:17 UTC by hwangstar156

close #714 

## 어떤 문제를 해결하려고 했나요?

현재 모달(snack-bar, commentInputModal, MenuSlider)에 대해서 동일한 로직이 들어가지만 각자의 컴포넌트에서 `열기, 닫기`, `dimmed`, `스크롤 막기`, `react Portal` 등등의 모달 공통 동작을 선언하고 있다.

이렇게 될시 나중에 모달이 하나 더 추가되더라도 이에 대한 로직을 재사용하지못하고 또 모든 공통동작을 선언할 것이다.

## 어떻게 해결했나요?

useModal이라는 훅과 GlobalModal 그리고 recoil의 조합으로 해결하였습니다. 이번에 이용한 방식은 공식에서 이용했던 에러핸들링 방식과 유사합니다. 컴포넌트가 오직 알아야 할 정보만 가지고 있는것이죠. 

>예를 들면 컴포넌트내에서 `어떤 에러가 발생하면 어떠한 동작을 한다.`라는 것이 있으면 이 컴포넌트가 어떠한 동작을 하는지 한눈에 파악하기 어렵다는 단점이 있습니다. 그래서 이 에러를 부모컴포넌트에게 위임을 하여 처리를 하면 컴포넌트는 오직 자신이 해야할 일만 알고 있을 수 있습니다.

기존에 모달을 불러오는 로직과 모달 컴포넌트자체가 이용하는 컴포넌트내에 존재하였습니다. 하지만 굳이 이용하는 컴포넌트에서 이 모달에 대해서 알 필요는 없습니다. 그래서 오직 `showModal`, `hideModal` 이라는 함수를 호출함으로써 어떤 모달을 보여주고 숨길지 요청을 보낼 수 있습니다.

이렇게 되면 모달을 이용하는 컴포넌트에서는 showModal, hideModal만 이용하고 실제로 이 모달은 GlobalModal이 처리하게 되는것이죠.

### GlobalModal
GlobalModal은 사용하는 모든 모달 컴포넌트에 대한 조합을 가지고 있습니다. ex) CommentInputModal, MenuSlider

또한 GlobalModal컴포넌트 내부에서 공통컴포넌트 동작(`dimmed`, `모달 열릴시 스크롤 막기`, `React Portal 선언`)을 선언을 합니다. 이렇게 될시 어떤 모달 컴포넌트에도 이 기본 동작이 적용될수 있습니다.

GlobalModal에서는 recoil에서 modalState를 받아와서 어떤 모달을 보여줄지 결정을 합니다. modalState의 default값은 null이기에 없다면 아무것도 렌더링하지않는것으로 구현하였습니다.

### useModal

useModal에는 `showModal`, `hideModal`을 내보냅니다. 단순히 recoil의 상태를 바꾸는 함수들입니다. `showModal`을 통해서 어떤 모달을 보여주고 그 모달의 props를 전달하고 `hideModal`을 이용하면 현재 모달을 지워버립니다.

2022-10-08 10:26 UTC, jurlring commented
라벨 붙여주세요~!

2022-10-10 07:44 UTC, liswktjs requested changes

2022-10-10 07:44 UTC, liswktjs commented on frontend/public/index.html
> +		<div id="comment-modal"></div>
portal과 modal의 차이가 무엇이죠?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@common/MenuSlider/MenuSlider.tsx
> +import useModal from '../../../hooks/common/useModal';
절대경로!

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +import ModalPortal from './ModalPortal';
절대경로

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +	const { modalProps, modalType, isMobileOnly } = modal ?? {};
modal ?? {}로 로직을 처리한 이유는 무엇인가요?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +		if (modalType) {
modalType이 true이면 아래의 동작을 행한다는 것은 if문을 통해서는 알겠지만, 
modalType이라는 이름만을 가지고 어떤 의미를 가지는지는 파악하기 힘든 것 같습니다. modalType이 어떻길래 hidden을 해야해야하는 거지 싶네요 이름을 바꾸는게 좋을 것 같습니다

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +	modalId: string;
modalId의 값들이 이미 정해져있으니깐 string 보다는 타입을 좁히는 것이 좋겠네요

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +const ModalPortal = ({ modalId, children }: PropsWithStrictChildren<ModalPortalProps>) => {
Portal이 helper에 있어야 하는지 의문이 드네요 왜 helper에 두셨죠?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/comment/CommentInputModal/CommentInputModal.tsx
> +import useModal from '../../../hooks/common/useModal';
절대경로

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/hooks/common/useModal.tsx
> +import { GetInsideRecoilState } from '../../types/util';
절대경로

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/hooks/common/useModal.tsx
> +	const showModal = (modalInfo: NonNullable<GetInsideRecoilState<typeof modalState>>) => {
modalnfo가 무슨 타입인거죠?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/pages/Detail/index.tsx
> +import useModal from '../../hooks/common/useModal';
절대경로

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/types/util.ts
> +export type GetInsideRecoilState<T> = T extends RecoilState<infer R> ? R : never;
파일 이름을 단순히 util로 하면 어떤 함수들이 위치하고 있는지 혼동이 올 수 있을 것 같으니 더 자세한 이름을 적는게 좋겠네요

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/types/util.ts
> +export type GetInsideRecoilState<T> = T extends RecoilState<infer R> ? R : never;
해당 타입이 어떤 타입인건가요?

2022-10-10 07:44 UTC, liswktjs commented on frontend/public/index.html
> +		<div id="comment-modal"></div>
왜 이름을 바꾼거죠?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +const MODAL_COMPONENTS: any = {
이곳에 왜 타입 any가 선언되어야 하나요

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +const MODAL_COMPONENTS: any = {
이미 들어올 수 있는 것들이 정해져 있으니 타입을 더 좁힐 수 있지 않을까요?

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +const ModalPortal = ({ modalId, children }: PropsWithStrictChildren<ModalPortalProps>) => {
사실상 ModalPortal이 포탈을 만드는 역할만을 수행하는 곳인데 컴포넌트 이름이 ModalPortal로 더 광범위 해서 함수이름이 명확하지 않은 것 같습니다.

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/components/comment/CommentInputModal/CommentInputModal.tsx
>  import reactDom from 'react-dom';
더 이상 사용하지 않는 import 문은 제거합시다

2022-10-10 07:44 UTC, liswktjs commented on frontend/src/store/modalState.ts
> +	modalProps: Record<string, never>;
이곳은 왜 {string: never} 타입인건가요

2022-10-10 14:03 UTC, hwangstar156 commented on frontend/public/index.html
> +		<div id="comment-modal"></div>
portal은 comment modal을 보여주기 위한 도구라고 생각됩니다.

그래서 comment-portal이라는 네이밍보다는 모달이 위치할곳이다 라고 알려줄수 있는 comment-modal이 좋다고 생각됩니다.

예를들면 modal을 하나만 보여준다고 생각하면 id="portal" 보다는 id="modal"이 더 의미가 맞다고 생각됩니다.

2022-10-10 19:04 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +const ModalPortal = ({ modalId, children }: PropsWithStrictChildren<ModalPortalProps>) => {
이것 역시 ui를 그리기위한 목적이 아닌 컴포넌트 이기에 helper로 두었습니다. 단지 children받은거에 포탈기능을 부여하는것인데 이것이 ui를 관리하는 폴더에 있는것이 이상하다고 생각됩니다.

2022-10-10 19:06 UTC, hwangstar156 commented on frontend/src/hooks/common/useModal.tsx
> +	const showModal = (modalInfo: NonNullable<GetInsideRecoilState<typeof modalState>>) => {
modalType, modalProps 그리고 isMobileOnly를 지니고 있는 객체타입입니다.

2022-10-10 19:10 UTC, hwangstar156 commented on frontend/src/types/util.ts
> +export type GetInsideRecoilState<T> = T extends RecoilState<infer R> ? R : never;
modalState는 recoil의 상태입니다. recoil에서 타입을 정하여 이용했을때는 RecoilState<{modalType: string}> 이런식으로 제네릭에 감싸져서 나오게 됩니다. 

하지만 modalState의 타입을 이용해서 modalInfo타입을 재사용하고 싶어서 RecoilState제네릭의 내부 타입만 빼오는 타입을 만들었습니다.

GetInsideRecoilState타입은 만약 들어오는 타입이 RecoilState에 속해있는 타입이라면 infer 키워드를 이용하여 내부 타입을 추론하고 그 타입을 반환하는 식으로 구현하였습니다.

2022-10-10 19:11 UTC, hwangstar156 commented on frontend/src/store/modalState.ts
> +	modalProps: Record<string, never>;
빈객체의 타입을 선언할때는 Record<string, never> 타입을 이용합니다.

2022-10-11 07:54 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +	modalId: string;
👍 `ModalStateType['modalType'] | 'snack-bar'`로 변경하였습니다!

2022-10-11 07:56 UTC, hwangstar156 commented on frontend/src/types/util.ts
> +export type GetInsideRecoilState<T> = T extends RecoilState<infer R> ? R : never;
getInside.ts로 변경하였습니다!

2022-10-11 17:17 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/ModalPortal.tsx
> +const ModalPortal = ({ modalId, children }: PropsWithStrictChildren<ModalPortalProps>) => {
CreatePortal이라는 네이밍으로 변경하여 관리하였습니다!

2022-10-11 17:25 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +		if (modalType) {
modalType을 if안에 넣어서 하는것은 확실히 어떤 동작을 원하는지 헷갈릴 수 있을것 같습니다. 하지만 사용하는 용도는 modalType이 맞는것 같아 네이밍은 유지하되 if문을 처리할떄 hasModal이라는 함수를 이용하여 명시적으로 어떤 행동을 하는지 보여주도록 하였습니다.

2022-10-14 05:15 UTC, liswktjs requested changes
getInside라는 파일에서 어떤 함수들이 있을까 생각해봤는데, 잘 떠오르지 않네요 
좀 더 자세히 파일 명을 적으면 좋을 것 같습니다 
아니면 만약 이곳에 다른 함수들을 더 넣는다면, 어떤 것을 넣어야할지도 생각해보면 좋을 것 같네요

2022-10-14 05:15 UTC, liswktjs commented
추가적으로 충돌 나는 것들도 해결하신 다음에 리뷰요청 해주세요~

2022-10-18 06:05 UTC, liswktjs requested changes
몇가지 절대경로가 빠졌어요! 추가 확인 해주세요~

2022-10-18 06:05 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +import { hasModal } from '../../../utils/validateInput';
절대경로! 😡

2022-10-18 06:05 UTC, liswktjs commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +import CreatePortal from './CreatePortal';
절대경로!

2022-10-18 06:05 UTC, liswktjs commented on frontend/src/utils/validateInput.ts
> +import { ModalStateType } from '../store/modalState';
절대경로!

2022-10-18 07:08 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +import { hasModal } from '../../../utils/validateInput';
수정했습니다!

2022-10-18 07:08 UTC, hwangstar156 commented on frontend/src/components/@helper/Modal/GlobalModal.tsx
> +import CreatePortal from './CreatePortal';
수정했습니다!

2022-10-18 07:08 UTC, hwangstar156 commented on frontend/src/utils/validateInput.ts
> +import { ModalStateType } from '../store/modalState';
수정했습니다!

2022-10-18 10:33 UTC, liswktjs approved these changes

2022-10-18 10:34 UTC, merged