커스텀 훅을 server data와 client data로 나눈다.
woowacourse-teams/2022-gong-seek pull request #726
Opened 2022-10-09 08:38 UTC by hwangstar156

close #725 

## 문제상황

react-query의 목적인 server state와 client state의 분리를 무시하고 코드를 작성하고 있었다. react-query의 커스텀 훅 네이밍을 `useGet...`, `usePost...`으로 가져갔으나 그안에 react의 ui를 관리하는 client state까지 같이 섞여있는 훅이 되버렸다.

따라서 client state와 server state각각의 관심사의 분리가 필요했다.

## 어떻게 문제를 해결하였나요??

기존에 존재하는 `useGet...`, `usePost...`등의 react query 커스텀 훅을 분리하는 기준을 재정립하였습니다.

server state를 관리하는 훅은 오직 useQuery와 useMutation 그리고 이것이 `성공` `실패` `로딩` 중일때만을 알고 있으면 됩니다.

성공할때 client의 상태를 바꾸고 싶다면 client state를 바꾸는 함수를 `react query 커스텀 훅`으로 인자로 전달하여 이용합니다.

```jsx
const useGetTempDetailArticles = ({
	tempArticleId,
	setEditorContent,
	setWritingArticlesInfo,
	content,
}: useGetTempArticlesProps) => {
          {...}
	useEffect(() => {
		if (isSuccess) {
			if (data && data.data) {
				setWritingArticlesInfo(data);
			}
			setEditorContent(content, data);
		}
	}, [isSuccess]);
}
```

useMutation훅을 이용할때는 `mutate를 하는 함수` 혹은 `mutate 그자체`를 커스텀 훅의 반환값으로 전달하여 client 단에서 호출할 수 있도록 설정하였습니다.

## 중심 리뷰 사항

현재는 테스트 상으로 WrtingArticles에 있는 로직들만 분리해보았습니다. 이 방식이 괜찮으면 그대로 전체 리팩토링 진행하겠습니다.

또한 react query에 사용되는 훅은 hooks 내의 quries라는 훅으로 분리하였습니다. client state의 모든것을 훅으로 빼는것은 불 필요하다고 생각되어서 너무 비대해진 로직이나 중복되는 로직만 분리하는것으로 하였습니다.

2022-10-10 09:24 UTC, liswktjs requested changes
리액트 쿼리 리팩토링 방향은 괜찮은 것 같습니다 
그렇지만, 함수이름등을 수정해야할 것 같습니다

2022-10-10 09:24 UTC, liswktjs commented on frontend/src/hooks/common/useAutoSaveTempArticle.tsx
> +	const preventRefresh = (e: BeforeUnloadEvent) => {
음.... preventRefreshEvent 어떤가요? 함수이름

2022-10-10 09:24 UTC, liswktjs commented on frontend/src/hooks/common/useAutoSaveTempArticle.tsx
> +	const preventRefresh = (e: BeforeUnloadEvent) => {
이벤트 타입 지정 해준 건 좋네요 👍

2022-10-10 09:24 UTC, liswktjs commented on frontend/src/hooks/common/useConvertImageUrl.tsx
> +const useConvertImageUrl = (content: MutableRefObject<Editor | null>) => {
converter도 좋긴하지만, 길이를 줄여준다는 함수 이름에 들어가면 좋을 것같습니다

2022-10-10 09:24 UTC, liswktjs commented on frontend/src/pages/WritingArticles/index.tsx
> +	const content = useRef<Editor | null>(null);
이 state들은 page component에서 관리할 예정인가요?

2022-10-11 17:26 UTC, hwangstar156 commented on frontend/src/__test__/article/useGetCategoryArticles.test.tsx
> +import useGetCategoryArticles from '@/hooks/queries/article/useGetCategoryArticles';
대부분 queries를 많이 사용하더라고요..👻

2022-10-11 17:29 UTC, hwangstar156 commented on frontend/src/hooks/common/useAutoSaveTempArticle.tsx
> +const useAutoSaveTempArticle = (handleTempSavedButtonClick: () => void) => {
음 common보다는 tempArticle아래에 있는것이 좋을것 같습니다. queries와 별개로 이러한 로직들을 처리하는 훅에 대해서의 폴더이름은 어떤것이 좋을까요? `bussiness`, `service`, `logic` 등등 괜찮은거 있으신가요?

2022-10-11 17:33 UTC, hwangstar156 commented on frontend/src/hooks/common/useAutoSaveTempArticle.tsx
> +	useInterval(handleTempSavedButtonClick, 120000);
추가적으로 스낵바에 있는 시간도 상수로 관리했습니다!

2022-10-11 17:34 UTC, hwangstar156 commented on frontend/src/pages/WritingArticles/index.tsx
> +	const content = useRef<Editor | null>(null);
넵 일단은 client state들은 page Component에 두고 분리할 필요성을 가진다면 hook으로 빼면 좋을것 같습니다.

2022-10-11 17:38 UTC, hwangstar156 commented on frontend/src/hooks/common/useConvertImageUrl.tsx
> +const useConvertImageUrl = (content: MutableRefObject<Editor | null>) => {
길이를 줄이다는 Shorten이라는 영어를 이용하네요! useShortenImageUrl로 변경하였습니다.

2022-10-19 01:51 UTC, closed without merging