게시글 자세히 보기에서 수정 , 삭제 버튼이 잘 보이도록 UI 수정하기
woowacourse-teams/2022-gong-seek pull request #732
Opened 2022-10-10 12:13 UTC by liswktjs

Close #689 

- 수정 삭제 버튼을 아이콘으로 대체하여 더 잘 보이도록 조정 
![스크린샷 2022-10-10 오후 9 13 14](https://user-images.githubusercontent.com/60773373/194863874-fb04544a-84e4-462f-a231-fb888aee73ed.png)

2022-10-11 18:29 UTC, hwangstar156 requested changes

2022-10-11 18:29 UTC, hwangstar156 commented on frontend/src/components/article/ArticleContent/ArticleContent.tsx
> +								<S.ModifyButton onClick={navigateUpdateArticle} />
저희가 Modify라고 쓰고 있는 단어가 있나요? Edit가 좀더 저희 도메인 용어에 맞다고 생각되네요!

2022-10-17 08:28 UTC, jurlring approved these changes
수고하셨습니다~

2022-10-17 08:29 UTC, hwangstar156 approved these changes

2022-10-17 08:30 UTC, merged