S3를 이용해서 이미지 저장 기능을 구현한다
woowacourse-teams/2022-gong-seek pull request #734
Opened 2022-10-11 03:06 UTC by hanull

## 변경 사항
- 이미지 서버를 S3로 변경

Close #572

2022-10-11 03:28 UTC, jurlring requested changes
슬롱쿤 수고하셨습니당
코멘트 확인 부탁드려요.

2022-10-11 03:28 UTC, jurlring commented on backend/build.gradle
> +    implementation 'software.amazon.awssdk:s3'
어떤 dependency인가용?

2022-10-11 03:28 UTC, jurlring commented on backend/build.gradle
> +    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
이 implementation은 왜 추가하신건가요!? 어떤 의미인가요?!

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/config/S3Configuration.java
> +                .region(Region.AP_NORTHEAST_2)
왜 설정해줘야하나요?

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/domain/FileExtension.java
> +    BMP("bmp");
4개밖에 없나요?

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    private String cloudFrontUrl;
cloudFrontUrl보다 ServerUrl이 낫지 않을까요?
cloudFront는 캐시 서버 느낌인데 이게 저희 도메인이랑 같은 의미인가요?

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    public String upload(final MultipartFile uploadImageFile) {
MultipartFile 은 어떤 타입인가용?

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +            s3Client.putObject(getPutObjectRequest(uploadImageFile), getRequestBody(uploadImageFile));
putObject메서드의 파라미터는 RequestHeader와 RequestBody인가요?

2022-10-11 03:28 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    }
메서드 위치가 여기가 맞을까요?

2022-10-11 03:28 UTC, jurlring commented on image-storage/src/main/java/com/gongseek/imagestorage/config/S3Configuration.java
> +public class S3Configuration {
image-storage 패키지랑 backend 패키지 두 곳에 모두 있어야하는 이유가 있나요?

2022-10-11 07:43 UTC, hanull commented on backend/build.gradle
> +    implementation 'software.amazon.awssdk:s3'
s3를 위한 의존성입니다!

2022-10-11 07:44 UTC, hanull commented on backend/build.gradle
> +    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
aws api를 localstack이라는 컨테이너 위에서 돌리기 위해서 추가했습니다!

2022-10-12 01:06 UTC, Gyuchool commented on backend/build.gradle
> +    implementation 'software.amazon.awssdk:s3'
platform은 일반적인 gradle 의존성 옵션과 무엇이 다른가요요요요요?

2022-10-12 01:12 UTC, Gyuchool approved these changes
수고하셨습니다~ 궁금한게있는데 이미지 디렉토리랑 백엔드 디렉토리에 중복되는 파일들이 보이는데 어떤 이유일까요~?

2022-10-12 01:12 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/image/domain/FileName.java
> +        Objects.requireNonNull(value);
요건 몬가요?

2022-10-12 01:33 UTC, brorae reviewed
수고하셨습니다 ~~!
간단하게 궁금한 부분 커멘트로 남겨보았습니다.
Backend 패키지와 Image-storage 패키지 두 곳에 코드가 모두 있는 것 같은데 따로 이유가 있을까요?

2022-10-12 01:33 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    @Value("${application.bucket.name}")
bucket name은 S3에서 지정해준 이름인가요?

2022-10-12 01:33 UTC, brorae commented on backend/src/test/java/com/woowacourse/gongseek/config/LocalStackS3Config.java
> +            DockerImageName.parse("localstack/localstack")).withServices(LocalStackContainer.Service.S3);
"localstack/localstack"은 무엇일까요?

2022-10-12 01:33 UTC, brorae commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +        }
그냥 RuntimeException으로 잡아도 괜찮을까요??

2022-10-12 01:33 UTC, brorae commented on backend/src/test/resources/application.yml
> -    active: test
제거하신 이유가 있을까요?

2022-10-12 02:25 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/config/S3Configuration.java
> +                .region(Region.AP_NORTHEAST_2)
S3Client 가 aws s3 버킷에 접근하는 역할을 하기 때문에 필요합니다

2022-10-12 02:26 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/domain/FileExtension.java
> +    BMP("bmp");
엄청나게 많지만, 먼저 주로 사용하는 확장자만 처리하도록 구현하는 것이 좋다고 생각해서 4개만 처리했습니다

2022-10-12 02:27 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    private String cloudFrontUrl;
말 그대로 cloudFront의 URL이기 때문에 명시적으로 표현하는 것이 더 좋다고 생각했어요

2022-10-12 04:06 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    public String upload(final MultipartFile uploadImageFile) {
사진, 동영상 등 여러 형태의 파일과 폼 요청(multipart/formdata)을 받아서 처리해주는 역할을 합니다.

2022-10-12 04:09 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +            s3Client.putObject(getPutObjectRequest(uploadImageFile), getRequestBody(uploadImageFile));
넵 PutObjectRequest, RequestBody를 매개변수로 받습니다.
PutObjectRequest는 S3 버킷 정보를 담고, RequestBody는 바이트코드를 요청 바디 형태로 만들어서 보냅니다.

2022-10-12 04:11 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    }
넵 위에서 아래로 순서대로 읽히도록 위치시켰어요.  upload 메서드를 보면, getPutObjectRequest, getRequestBody, getUrl 순서로 진행되는 것을 알 수 있어요

2022-10-12 04:12 UTC, hanull commented on image-storage/src/main/java/com/gongseek/imagestorage/config/S3Configuration.java
> +public class S3Configuration {
s3로 변경이 완료되면 , 기존에 있던 image-storage는 제거할 예정입니다.

2022-10-12 04:13 UTC, hanull commented
> 수고하셨습니다~ 궁금한게있는데 이미지 디렉토리랑 백엔드 디렉토리에 중복되는 파일들이 보이는데 어떤 이유일까요~?

2022-10-12 04:15 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/domain/FileName.java
> +        Objects.requireNonNull(value);
value null 체크 과정입니다 

> 수고하셨습니다~ 궁금한게있는데 이미지 디렉토리랑 백엔드 디렉토리에 중복되는 파일들이 보이는데 어떤 이유일까요~?

참고해주세요 
- https://github.com/woowacourse-teams/2022-gong-seek/pull/734#discussion_r992978961

2022-10-12 04:16 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +    @Value("${application.bucket.name}")
넵 맞아요. S3에 파일을 업로드하려먼 버킷이 있어야 하는데요. 그 버킷 이름입니다.

2022-10-12 04:21 UTC, hanull commented on backend/src/test/java/com/woowacourse/gongseek/config/LocalStackS3Config.java
> +            DockerImageName.parse("localstack/localstack")).withServices(LocalStackContainer.Service.S3);
Localstack은 AWS 클라우드 서비스 에뮬레이터이고, 이를 도커 허브에 localstack/localstack으로 이미지가 올라가 있기 때문에 localstack/localstack 으로 도커 이미지를 불러옵니다.

2022-10-12 04:27 UTC, hanull commented on backend/src/test/resources/application.yml
> -    active: test
test yml 파일을 서브모듈로 관리하려고 했다가 secret 디랙터리를 찾지 못하는 문제가 있어서 기존의 방법으로 롤벡했습니다.

2022-10-12 04:37 UTC, hanull commented on backend/src/main/java/com/woowacourse/gongseek/image/infra/S3Uploader.java
> +        }
커스텀 예외로 `파일 업로드에 실패했습니다` 처리하도록 변경했어요.
그런데 Bad Request Exception로 처리할 지, RuntimeException으로 처리할지 고민이네요.

2022-10-13 03:09 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/image/domain/FileName.java
> +        Objects.requireNonNull(value);
저렇게 하면 null이 들어오면 어떤 예외가 터지는거죠? 
커스텀 예외에 안잡히지 않나요?

2022-10-20 01:34 UTC, merged