외부 api는 트랜잭션을 물지않도록 수정했습니다.
woowacourse-teams/2022-gong-seek pull request #758
Opened 2022-10-12 07:54 UTC by Gyuchool

외부 api와 소통하는 로직을 트랜잭션에서 분리했습니다.

Close #742

2022-10-12 10:15 UTC, jurlring requested changes
수고하셨습니다~
코멘트를 확인해주세요~

2022-10-12 10:15 UTC, jurlring commented on backend/src/main/java/com/woowacourse/gongseek/auth/infra/GithubOAuthClient.java
> +    @Transactional(propagation = Propagation.NEVER)
왜 붙이신건가요??
어차피 Transactional을 안붙이면 같지 않나요?

2022-10-12 10:33 UTC, Gyuchool commented on backend/src/main/java/com/woowacourse/gongseek/auth/infra/GithubOAuthClient.java
> +    @Transactional(propagation = Propagation.NEVER)
안붙여도 같은데 약간 해당 메서드를 트랜잭션안에서 호출하지 말자라는 의미를 담으려고 추가했어요!

2022-10-12 12:58 UTC, brorae approved these changes
수고하셨습니다~

2022-10-12 13:17 UTC, hanull approved these changes
수고하셨습니다!@

2022-10-13 03:07 UTC, jurlring approved these changes

2022-10-13 03:07 UTC, merged