이벤트 핸들러에 대한 컨벤션을 맞춰 수정한다.
woowacourse-teams/2022-gong-seek pull request #762
Opened 2022-10-13 03:26 UTC by hwangstar156

close #740 

## 변경사항

- 이벤트 핸들러를 모두 함수로 빼서 관리한다.
- 이벤트 핸들러의 네이밍은 기본적으로 handle${EventName}${Component} 식으로 구현한다. 하지만 props로 이벤트 핸들러를 넘겨줄때는 on${Event}식으로 전달한다.

2022-10-14 05:30 UTC, liswktjs requested changes
바꿀 함수명이 많았을 텐데 수고하셨습니다 
함수명 관련해서 몇가지 코멘트들 남겼습니다 확인하고 수정해주세요~

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/@common/AnonymousCheckBox/AnonymousCheckBox.tsx
> +	const handleChangeAnonymouseCheckInput = (e: ChangeEvent<HTMLInputElement>) => {
익명을 확인하는 함수여서 Input과 Change라는 네이밍이 들어가는 것 보다 handleToggleAnoymouseCheck이런식으로 toggle이 들어가는 게 낫지 않을까요? 현재 익명이 체크 방식이라 toggle이 더 나을 것 같다는 생각이 드네요

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/@layout/TabBar/TabBar.tsx
> +	const handleClickMenuLink = () => {
Menu보다 Slider가 낫지 않을까요? 해당 함수의 동작이 슬라이드를 열어주는 것이라 해당 네이밍이 더 좋을 것 같습니다

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.tsx
> +			<S.Title onClick={handleClickTitle}>{title}</S.Title>
ArticleTitle이라고 어떤 타이틀인지 더 자세하게 써주는 게 좋을 것 같습니다

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/comment/Comment/Comment.tsx
> +	const handleClickEditButton = () => {
어떤걸 Edit하는지도 명시해 주면 좋지 않을까요? Comment 파일 밑에 있긴 하지만 좀 더 자세히 함수명을 써주면 다른 사람들이 볼 때에 함수의 동작을 이름만으로 이해하기 편할 것 같습니다

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/comment/CommentInputModal/CommentInputModal.tsx
> +	const handleClickCommentPostButton = () => {
👍

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/tempArticle/TemporaryArticleList/TemporaryArticleList.tsx
> +	const handleClickDeleteButton = (id: number) => {
해당 함수도 어떤 Article를 Delete하는지 더 자세히 써주면 좋을 것 같습니다

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/user/UserProfile/UserProfile.tsx
> +	const handleClickEditIcon = () => {
Icon이라는 정보까지 들어갈 필요가 없을 것 같다는 생각도 드네요 저희가 Icon을 버튼처럼 사용하고 있어서 어떻게 생각하시나요?

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/user/UserProfile/UserProfile.tsx
> +	const handleClickConfirmButton = ({ editedName }: { editedName: string }) => {
이것도 어떤 것을 Confirm하는지 명시해 주면 좋지 않을까요? 앞부분의 UserEditInput의 경우 엘리먼트의 이름만으로 함수의 의도들이 다 들어나는데 해당 함수의 경우 추상적으로 느껴지긴 하네요

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/components/vote/VoteItem/VoteItem.tsx
> +						handleChangeRadioButton(articleId, voteItemId);
해당 함수도 Radio버튼 보다는 vote라는 키워드가 들어가는게 다른 사람이 해당 함수를 보았을 때 함수의 동작을 예측하기 쉬울 것 같습니다

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/constants/url.ts
> +} as const;
이곳에 왜 as const 를 넣으셨나요?

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/hooks/comment/useDeleteComment.tsx
> +	const handleClickDeleteButton = (id: number) => {
해당 부분도 Comment라는 추가적인 정보를 넣어주면 좋을 것 같아요

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/hooks/user/usePutUserProfile.tsx
> +	return { handleClickConfirmIcon, isLoading, isSuccess, data };
요것도요! 좀 더 자세하게 적으면 좋을 것 같네요

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/hooks/vote/usePostVoteItem.tsx
> +	const handleChangeRadioButton = (articleId: string, idx: number) => {
앞 부분에 언급했던 함수네요~

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/pages/DiscussionDetail/index.tsx
> +	const handleClickVoteGenerateButton = () => {
👍

2022-10-14 05:30 UTC, liswktjs commented on frontend/src/pages/Home/index.tsx
> +	};
해당 함수명을 보고 해당 함수가 어떤 역할을 할지 잘 생각해내지 못할 것 같다는 생각이 드네요 스밍 생각은 어떤가요?

2022-10-18 07:25 UTC, hwangstar156 commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.tsx
> +			<S.Title onClick={handleClickTitle}>{title}</S.Title>
이 부분은 carousel pr에서 수정하겠습니다! 불필요한 충돌이 발생할것 같아서요~

2022-10-18 07:35 UTC, hwangstar156 commented on frontend/src/components/user/UserProfile/UserProfile.tsx
> +	const handleClickEditIcon = () => {
`handleClickUserNameEditButton` 으로 변경했습니다! Icon을 빼고 버튼이라는 의미를 주었고 정확하게 어떤것을 edit하는지 명시하였습니다!

2022-10-18 07:36 UTC, hwangstar156 commented on frontend/src/components/user/UserProfile/UserProfile.tsx
> +	const handleClickConfirmButton = ({ editedName }: { editedName: string }) => {
`handleClickUserNameConfirmButton` 으로 수정하였습니다!

2022-10-18 07:39 UTC, hwangstar156 commented on frontend/src/components/vote/VoteItem/VoteItem.tsx
> +						handleChangeRadioButton(articleId, voteItemId);
`handleChangeVoteSelectButton`으로 변경하였습니다!

2022-10-18 07:43 UTC, hwangstar156 commented on frontend/src/constants/url.ts
> +} as const;
설정하지 않으면 URL이 `[key: string]: string` 식으로 추론되서 좀 더 엄격한 타입으로 이용하고자 as const를 작성하였습니다! 추후에 상수에는 모두 as const를 붙히는 컨벤션을 정해도 좋을것 같네요!

2022-10-18 07:55 UTC, hwangstar156 commented on frontend/src/pages/Home/index.tsx
> +	};
`handleLinkToArticleDetail`로 변경해보았습니다!

2022-10-19 05:08 UTC, merged