상세페이지가 스크린 리더기에서 올바르게 읽히도록 웹 접근성을 높인다
woowacourse-teams/2022-gong-seek pull request #780
Opened 2022-10-17 11:26 UTC by liswktjs

close #773 

tabIndex를 부여하여 tab만으로 상세페이지의 모든 요소에 tab으로 접근이 가능하도록 한다

2022-10-18 06:59 UTC, hwangstar156 requested changes
detail의 라이트하우스 점수도 같이 스크린샷 남겨주세요~

2022-10-18 06:59 UTC, hwangstar156 commented on frontend/src/components/comment/Comment/Comment.tsx
> +						alt="작성자의 프로필"
저는 이것을 `프로필 이미지`로 적어놨는데 한번 맞추는게 좋을것 같네요!

2022-10-18 06:59 UTC, hwangstar156 commented on frontend/src/pages/Detail/index.tsx
> +		<S.Container role="tabpanel" tabIndex={1}>
tabpanel을 쓰려면 위에 tablist를 써야되는거 아니였나요?? 또 aria-controls로 연결해야되는걸로 알고 있어요!
한번 알아보면 좋을것 같아요.

2022-10-18 06:59 UTC, hwangstar156 commented on frontend/src/pages/Detail/index.tsx
> +		<S.Container role="tabpanel" tabIndex={1}>
혹시 여기에 tabIndex=1을 설정한 이유가 있을까요?

2022-10-18 06:59 UTC, hwangstar156 commented on frontend/src/components/article/ArticleContent/ArticleContent.tsx
> +								#{item}
이 해시태그부분 아마 `파운드 기호` 이런식으로 읽게 될텐데 `aria-label="해시태그"`로 작성하는게 어떨까요?

2022-10-19 01:16 UTC, liswktjs commented on frontend/src/components/comment/Comment/Comment.tsx
> +						alt="작성자의 프로필"
누구의 프로필 이미지로 명시하는게 좋지 않을까요? 작성자의 프로필로 가시죠

2022-10-19 01:17 UTC, liswktjs commented on frontend/src/pages/Detail/index.tsx
> +		<S.Container role="tabpanel" tabIndex={1}>
삭제해야할 요소였는데, 둘 다 남아있었네요 둘다 제거하겠습니다!

2022-10-19 01:37 UTC, liswktjs commented
<img width="468" alt="스크린샷 2022-10-19 오전 10 37 44" src="https://user-images.githubusercontent.com/60773373/196576808-ccb25fdd-7f3e-4214-86f5-348e41e4b762.png">

2022-10-19 01:58 UTC, hwangstar156 approved these changes

2022-10-19 02:26 UTC, merged