carousel ui를 변경한다. + 홈페이지으
woowacourse-teams/2022-gong-seek pull request #786
Opened 2022-10-18 04:03 UTC by hwangstar156

close #657
close #785

2022-10-18 05:34 UTC, liswktjs requested changes
몇가지 고쳤으면 하는 점들 적을께요
1. 페이지를 열자 마자 한개가 넘어간다 
페이지가 로드 되자마자 바로 슬라이더가 바뀌어서 혼동이 올 것 같아요 이게 첫 번째인지 두번째 게시글인지? 
2. 게시글 마다 크기가 달라서 하나는 위로 올라오는 애니메이션이 된 것 같아요 
해시태그 있는 것과 없는 것의 높이 차이가 있다보니 해시태그 있는 게시글의 경우 애니메이션 효과가 들어 간것같아 보여요 이 점이 혼동이 올 수 있으니 모든 게시글의 높이를 동일하게 가져가는게 좋을 것 같습니다 
3. width값도 좀 늘리면 좋을 것 같네요! 현재 dev라서 게시글 제목이 길지 않지만 prod에 있는 게시글들은 제목들이 긴 편이기 때문에 width를 늘려도 괜찮을 것 같습니다

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/Card/Card.styles.tsx
> +			filter: blur(2px) brightness(50%);
2px 해당 요소 theme을 활용해서 사용넣어줄 수 있지 않을까요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/Card/Card.tsx
> +			`}
왜 다 파일 체인지가 되었다고 뜰까요? 몇가지 요소만 추가 된게 아닌가요? 🤔

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/Dropdown/Dropdown.tsx
> +				onClick={() => navigate('/my-page')}
이 navigate는 인라인으로 처리한 이유가 있나요? handle로 다 빼기로 하지 않았었나요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/ProgressiveBar/ProgressiveBar.styles.tsx
> +`;
progressBar이제 사용 안해서 지워도 될 것 같네요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/ProgressiveBar/ProgressiveBar.tsx
> +export default ProgressiveBar;
이 파일도요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/SortDropdown/SortDropDown.tsx
> +	const [isLog, setIsLog] = useState(false);
IsLog라는게 무슨 뜻인가요? 뭔가 이름만으로 추측이 힘드네요 🥲

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@common/SortDropdown/SortDropDown.tsx
> +	const [isLog, setIsLog] = useState(false);
이름을 바꾸는 작업도 필요할 것 같아요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/@layout/Header/Header.tsx
> +	const { ref } = useEnterToClick();
이 ref도 as를 통해서 이름을 명확히 해주는 건 어떨까요? ref가 추상적인 단어라 상세히적으면 역할이 뚜렷하게 드러날 것 같네요

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/ArticleItem/ArticleItem.tsx
> +					<S.Views>조회 수 {article.views.toLocaleString()}</S.Views>
이게 10만단위 넘어거서 써준 조치인가요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/ArticleItem/ArticleItem.tsx
> +						</S.HashTagItem>
👍

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticle/PopularArticle.styles.tsx
> +	// justify-content: center;
주석 제거!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticle/PopularArticle.styles.tsx
> +	}
theme이 3개이상 쓰이고 있으니 묶어서 처리해줘야할 것 같네요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticle/PopularArticle.styles.tsx
> +	padding: 1rem;
theme사용해주세요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticle/PopularArticle.tsx
> +						rightSlide={handleRightSlideEvent}
prop가 rightSlide이름인데 해당 이름으로는 이곳에서 이 prop이 어떤 것을 가지게 되는지 추측하기 힘든 것 같아요 한 단계 타고 들어가서 확인해야할 것 같은 함수 네이밍이 필요해보이네요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +	padding: 0.5rem;
theme사용!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +		linear-gradient(to bottom, #ff3300 7%, #66ffcc 96%);
흠...... 색상도 theme으로 해야 좋을 것 같네요!

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +		margin-bottom: 1rem;
theme! 😡

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +	margin: 1rem 0;
😡

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/search/SearchBar/SearchBar.styles.tsx
> +	margin: -1px;
😡 theme 좀....

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/user/UserProfileIcon/UserProfileIcon.styles.tsx
> +	margin: -1px;
으악! 😡

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/vote/VoteItem/VoteItem.tsx
> +			<ProgressiveBar
아 vote에서 사용되기로 했었나 보군요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/components/vote/VoteItem/VoteItem.tsx
> +				time={1}
이 타임도 채워지는 시간이면 상수로 관리해주어야 하지 않을까요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/hooks/common/useCarousel.tsx
> +			carouselItemWidth.current = carouselElementRef.scrollWidth / 15;
왜 15로 나눈거죠?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/hooks/common/useCarousel.tsx
> +			carouselElementRef?.scrollTo({
carouselElementRef왜 타입가드가 되어 있지 않나요?

2022-10-18 05:34 UTC, liswktjs commented on frontend/src/hooks/common/usePrevState.tsx
> +export default usePrevState;
얘는 왜 필요하죠?

2022-10-18 08:59 UTC, hwangstar156 commented on frontend/src/components/@common/Card/Card.tsx
> +			`}
흠흠..? 그러게요?!

2022-10-18 09:02 UTC, hwangstar156 commented on frontend/src/components/@common/Dropdown/Dropdown.tsx
> +				onClick={() => navigate('/my-page')}
이 부분은 원래 이렇게 되어있어서 건들지 않았는데 어짜피 handler 변경이 머지되면 충돌 날것 같아서 충돌 해결할때 바꿀 예정이였습니다!

2022-10-18 09:04 UTC, hwangstar156 commented on frontend/src/components/vote/VoteItem/VoteItem.tsx
> +			<ProgressiveBar
넵넵 2군데에서 쓸것 같아서 분리를 하였는데 vote가 리팩토링되었네요! 저는 progressiveBar자체는 따로 분리하는게 좋을것 같아서 롤백할 필요는 없을것 같습니다!

2022-10-18 09:04 UTC, hwangstar156 commented on frontend/src/components/@common/ProgressiveBar/ProgressiveBar.styles.tsx
> +`;
https://github.com/woowacourse-teams/2022-gong-seek/pull/786#discussion_r997930031 코멘트 남겼습니다~

2022-10-18 09:04 UTC, hwangstar156 commented on frontend/src/components/@common/ProgressiveBar/ProgressiveBar.tsx
> +export default ProgressiveBar;
위와 동일합니다!

2022-10-19 05:19 UTC, hwangstar156 commented on frontend/src/components/@common/SortDropdown/SortDropDown.tsx
> +	const [isLog, setIsLog] = useState(false);
접근성을 위해서 `esc`를 누를시 `닫힘`이라는 알림을 말할 수 있도록 isLog를 통해서 키고 끌수 있도록 하였습니다!

하지만 이름이 좀 더 명확할 필요가 있는것 같아서 `isShowAlertLog`라는 네이밍으로 변경하였습니다!

2022-10-19 05:24 UTC, hwangstar156 commented on frontend/src/components/@layout/Header/Header.tsx
> +	const { ref } = useEnterToClick();
`enterRef`라는 네이밍으로 변경하였습니다!

2022-10-19 05:26 UTC, hwangstar156 commented on frontend/src/components/article/ArticleItem/ArticleItem.tsx
> +					<S.Views>조회 수 {article.views.toLocaleString()}</S.Views>
10000단위부터 숫자를 붙혀서 쓴다면 스크린리더가 하나하나 따로 읽게되는데 `toLocaleString()`을 이용할 시 똑바로 만단위로 읽습니다!

2022-10-19 05:33 UTC, hwangstar156 commented on frontend/src/components/search/SearchBar/SearchBar.styles.tsx
> +	margin: -1px;
이 부분은 스크린리더기를 위해서 사용한 옵션인데 rem자체를 이용할 필요가 없다고 생각되네요!

2022-10-19 05:33 UTC, hwangstar156 commented on frontend/src/components/user/UserProfileIcon/UserProfileIcon.styles.tsx
> +	margin: -1px;
위와 동일합니다!

2022-10-19 06:21 UTC, hwangstar156 commented on frontend/src/hooks/common/useCarousel.tsx
> +			carouselItemWidth.current = carouselElementRef.scrollWidth / 15;
<img width="1327" alt="스크린샷 2022-10-19 오후 3 21 29" src="https://user-images.githubusercontent.com/85891751/196612333-0b4a8b01-d3cd-49c2-bdae-14d872106310.png">

`scroll-snap-align: center`를 주어서 다음요소에 닿으면 중앙으로 정렬이 됩니다. 캐러셀의 아이템이 10개이기 때문에 13에서 30정도로 나누면 모두 가능하긴 하지만 이때 적당한 숫자로 15로 골랐던것 같습니다!

지금 생각해보니 명시적으로 아이템길이의 50%만 이동하는것이 좋을것 같아서 20으로 수정하였습니다! 또한 상수화하여 관리했습니다.

2022-10-19 06:27 UTC, hwangstar156 commented on frontend/src/hooks/common/useCarousel.tsx
> +			carouselElementRef?.scrollTo({
타입가드 할 부분이 너무 많아서 동일한 코드가 많아질것 같아서 진행하지 않았습니다! 일단 타입가드를 하도록 코드를 수정하였습니다! 한번 확인부탁드립니다!

2022-10-20 04:59 UTC, liswktjs commented
충돌 해결해주세요~

2022-10-20 05:12 UTC, liswktjs approved these changes

2022-10-20 05:59 UTC, merged