댓글의 임시저장 기능을 구현한다
woowacourse-teams/2022-gong-seek pull request #788
Opened 2022-10-18 07:36 UTC by liswktjs

close #772 

- 댓글의 입력값을 state로 관리하여 임시저장 
- inputModal을 ref로 관리하고 있어, 1초마다 임시저장 요청을 보내도록 수정 
- commentInputModal 컴포넌트 내에 너무 많은 로직이 존재하고 있어 훅으로 분리 
- commentPost관련 함수 분리

2022-10-18 08:52 UTC, hwangstar156 requested changes

2022-10-18 08:52 UTC, hwangstar156 commented on frontend/src/utils/takeToastImgEditor.ts
> +};
이 로직 제가 지난 pr에서 뺀것 같은 기억이있네요..!

2022-10-18 08:52 UTC, hwangstar156 commented on frontend/src/hooks/comment/useHandleCommentInputModalState.tsx
> +			handleCreateComment();
현재 https://github.com/woowacourse-teams/2022-gong-seek/pull/726 이 pr과 많이 충돌이 날것 같네요! 현재 server state와 client state를 나누기로 하였는데 여기에는 하나로 뭉쳐져있어서 개선을 해야될것 같습니다!

또한 https://github.com/woowacourse-teams/2022-gong-seek/pull/724 현재 공통 모달 부분에 commentInputModal부분을 많이 변경하였기에 이것을 머지한 후에 다시 작업을 진행하면 좋을 것 같습니다!

2022-10-18 08:52 UTC, hwangstar156 commented on frontend/src/utils/takeToastImgEditor.ts
> +};
빠르게 https://github.com/woowacourse-teams/2022-gong-seek/pull/724 https://github.com/woowacourse-teams/2022-gong-seek/pull/726 를 머지하고 다시 확인해야될것 같습니다!

2022-10-18 08:52 UTC, hwangstar156 commented on frontend/src/hooks/comment/useHandleCommentInputModalState.tsx
> +	}, []);
현재 로컬에서 저장하는 로직인가요?

2022-10-19 01:42 UTC, liswktjs commented on frontend/src/hooks/comment/useHandleCommentInputModalState.tsx
> +	}, []);
state에 저장하는 로직입니다 ! editor를 ref로접근하고 있어서 몇 초마다 저장하는 명령을 해야 제대로 저장이 되더라고요

2022-10-19 02:32 UTC, merged