해시태그 검색이 되도록 한다
woowacourse-teams/2022-gong-seek pull request #796
Opened 2022-10-19 12:00 UTC by liswktjs

close #789 

- 해시태그 검색이 되도록 조취 
- 해시태그 검색이 되는 대상인 리스트는 항상 최신이여야 하기에 totalHashTag State와 동일하게 가져감 
- 해시태그 검색 결과 에서도 해시태그를 선택시 검색이 되도록 진행 
- 검색결과에 대해서도 색깔이 변하도록 하기 위해서 setSelectedTargets을 추가적으로 HashTagClickSearchBox에 넘김 
- > selected되는 것이 모두 useHandleHashTagState에서 관리되어 검색이 되어야 하기 때문에 해당 방식으로 처리함 
![Uploading 스크린샷 2022-10-19 오후 9.00.33.png…]()

2022-10-19 18:35 UTC, hwangstar156 requested changes

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +		}
map돌리는 로직이 둘이 동일한것 같은데 중복제거 부탁드려요! 이렇게 긴것은 추상화하여 관리하면 좋을것 같네요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +	}
테x -> 태 o

여기에는 EmptyMessage 컴포넌트를 이용하지 않나요?

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +				{targets.slice(0, 5).map((item) => (
5는 상수화 부탁드려요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +						}}
이벤트 핸들러 분리해주세요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +					))}
위에랑 완전히 똑같은것을 불러오는것 같은데 무슨차이죠?

차이가 있어서 분리한거라면 이것도 중복 처리 부탁드려요! 하나의 컴포넌트로 쪼개도 될것 같네요

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +		searchTargetHashTag();
한칸씩 띄워주세요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +	};
프론트단에서만 filter를 통해서 처리하는데 굳이 제출을 해서 검색할 필요가 있을까요? 주로 이러한 검색은 input이 입력될때마다 검색하는것으로 많이 구현하더라고요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +	};
if 끼리는 한칸씩 띄워주세요!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +		{ name: string; isChecked: boolean }[]
위에 타입을 작성했는데 왜 사용하고 있지 않죠?

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +type HashTagSearchResultType = { name: string; isChecked: boolean }[];
이런 경우는 뒤에 []은 빼고 사용하는 측에서 []를 붙히는것이 훨씬 좋다고 하더라고요.

```suggestion
type HashTagItem = { name: string; isChecked: boolean };
useState<HashTagItem[]>
```
이런느낌으로요! 사용하는측에서 이것이 리스트라는것을 알 수 있는것이 더 좋은방법이라고 합니다!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +					handleSubmitHashTagSearch();
사실 submit말고 change될때마다 구현됬으면 좋겠네요! 그래도 이러한 인라인 이벤트핸들러는 따로 빼서 관리합시다!

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +					isHashTagSearchResultType(hashTagSearchResult) && (
이 3개의 검증을 보고 어떤것을 의도하는지 모를것 같네요! 추상화해서 관리하면 좋을것 같네요

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/hooks/hashTag/useHandleHashTagState.tsx
> +		const selectedHashTagResult = new Set(selectedTargetHashTags.concat(selectedTotalHashTags));
오 Set을 쓴 이유가 있나요?

2022-10-19 18:35 UTC, hwangstar156 commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +					isHashTagSearchResultType(hashTagSearchResult) && (
그리고 `hashTagSearchResult.length < 1`이 아니면 무조건 `hashTagSearchResult.length >= 1`일텐데 삼항연산자를 이용하는것이 좋지 않을까요?

2022-10-19 18:41 UTC, hwangstar156 commented
반응형으로도 ui 문제없는것 확인했습니다! 혹시 대문자, 소문자 처리는 일부러 안하신건가요? 한다고 했었던것 같은데 안되어있어서요!

2022-10-20 01:44 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.styles.tsx
> +	color: ${({ isChecked, theme }) => (isChecked ? theme.colors.WHITE : theme.colors.BLACK_500)};
충돌 해결하면서 제거되야 하는 스타일이 있었네요

2022-10-20 01:50 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +		}
filterCheckedHashTags로 분리하였습니다

2022-10-20 01:52 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +	}
Empty로 통일 되는 것이 맞긴 한데 해당 로직이 2군데에서 사용되고 있다보니 뭔가.... 중복되어서 똑같이 보이는게 싫어서 안했기 했는데 Empty로 해봐야겠군요

2022-10-20 02:02 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagClickSearchBox/HashTagClickSearchBox.tsx
> +					))}
화살표를 눌러서 해시태그들을 펼칠때에 5개부터 보여주고 있어서 나머지 target들은 5이후 부터 보여줘야 하기 때문에 이렇게 처리하였습니다

2022-10-20 02:07 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +		{ name: string; isChecked: boolean }[]
수정했습니다!

2022-10-20 02:12 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +type HashTagSearchResultType = { name: string; isChecked: boolean }[];
기존에 prop에 선언된 타입을 재활용하는 것으로 수정하였습니다

2022-10-20 02:13 UTC, liswktjs commented on frontend/src/hooks/hashTag/useHandleHashTagState.tsx
> +		const selectedHashTagResult = new Set(selectedTargetHashTags.concat(selectedTotalHashTags));
검색된 해시태그 목록들에서와 전체 해시태그 목록에서 동일한 것을 클릭했을 때 서버에 요청이 동일한 항목이 들어가는 것을 방지하기 위해 set을 활용 했습니다

2022-10-20 02:26 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +					handleSubmitHashTagSearch();
change할때마다 검색되도록 구현하고, submit을 할때에도 구현하였습니다. 그런데 submit일 때만 e를 통해 기본 이벤트를 막고 handleSubmitHashTagSearch()는 검색버튼을 눌렀을 때에도 동일하게 사용하고 있어 submit의 경우에만 e를 따로 분리하였습니다

2022-10-20 02:29 UTC, liswktjs commented on frontend/src/components/hashTag/HashTagSearchBox/HashTagSearchBox.tsx
> +					isHashTagSearchResultType(hashTagSearchResult) && (
기존에 result에 검색결과가 없을때에 안내문구도 같이 넣어줬었는데 분리하면서 없어도 될 로직이였네요 관련된 것 모두 제거하였습니다

2022-10-20 04:43 UTC, hwangstar156 approved these changes

2022-10-20 04:46 UTC, merged