인기게시물에서 isLike여부에 따라서 보여주는 UI를 변경한다.
woowacourse-teams/2022-gong-seek pull request #896
Opened 2022-11-04 04:59 UTC by hwangstar156

close #894 

isLike를 통하여 누른경우만 차보이는 하트를 보여주도록 구현

+ Carousel에 대해 의도가 담긴 네이밍 추가

2022-11-04 05:54 UTC, liswktjs requested changes
몇가지 수정사항 남겼습니다! 확인해주세요~

2022-11-04 05:54 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +export const EmptyHeartIcon = styled(AiOutlineHeart)`
empty Heart도 font-size를 지정하면 좋을 것 같아요

2022-11-04 05:54 UTC, liswktjs commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.tsx
> +									<PopularS.EmptyHeartIcon />
aria-label을 emptyHearIcon에도 넣어주면 좋을 것같아요

2022-11-04 05:54 UTC, liswktjs commented on frontend/src/utils/converter.ts
> +	if (process.env.STORYBOOK) {
해당 부분 main에 반영되어있지 않았나요?

2022-11-04 13:54 UTC, hwangstar156 commented on frontend/src/utils/converter.ts
> +	if (process.env.STORYBOOK) {
보내는 브랜치가 develop 이였네요 Main으로 수정하였습니다!

2022-11-04 13:54 UTC, hwangstar156 commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.tsx
> +									<PopularS.EmptyHeartIcon />
수정했습니다!

2022-11-04 14:01 UTC, hwangstar156 commented on frontend/src/components/article/PopularArticleItem/PopularArticleItem.styles.tsx
> +export const EmptyHeartIcon = styled(AiOutlineHeart)`
지정되어있습니다!

2022-11-08 02:14 UTC, liswktjs approved these changes
웹접근성 👍

2022-11-08 02:18 UTC, merged